/**
 * LightweightAIEngine — Zero-Cost, Offline, Client-Side AI Engine.
 *
 * Evaluates user prompts against built architectures dynamically.
 * Features keyword tokenization, Guardrail safety inspection,
 * Vector DB RAG retrieval simulation, Code Interpreter formatting,
 * and contextual response synthesis.
 */

import { LabArchitecture } from '../types';
import { getComponent } from '../data/components';
import { SimTurn } from '../provider/AIProvider';

export class LightweightAIEngine {
  static generateResponse(architecture: LabArchitecture, prompt: string): SimTurn {
    const placed = architecture.components;
    const trace = placed.map(id => getComponent(id)?.label ?? id);
    const text = prompt.trim();
    const lower = text.toLowerCase();

    // 1. Check empty architecture
    if (placed.length === 0) {
      return {
        input: text,
        output: '⚠️ Architecture is empty. Drag components into the pipeline above to start your AI.',
        trace: [],
        degraded: true,
      };
    }

    // 2. Check AI Brain / LLM presence
    const hasBrain = placed.includes('brain') || placed.includes('llm') || placed.includes('chat_model');
    if (!hasBrain) {
      return {
        input: text,
        output: '⚠️ Pipeline Execution Error: No AI Brain / LLM block found! Without a core brain, this system cannot generate responses. Add an AI Brain block.',
        trace,
        degraded: true,
      };
    }

    // 3. Guardrail Security Inspection
    const isInjectionAttempt =
      lower.includes('ignore') ||
      lower.includes('bypass') ||
      lower.includes('hack') ||
      lower.includes('system prompt') ||
      lower.includes('jailbreak') ||
      lower.includes('drop table') ||
      lower.includes('admin password');

    const hasGuardrail = placed.includes('guardrail');

    if (isInjectionAttempt) {
      if (hasGuardrail) {
        return {
          input: text,
          output: `🛡️ [Guardrail Shield Active]\nSecurity Rule Triggered: Detected potential prompt injection attempt.\nThe Guardrail block successfully intercepted the unsafe query before reaching the LLM.`,
          trace,
          degraded: false,
        };
      } else {
        return {
          input: text,
          output: `⚠️ [Security Warning: Vulnerability Exploited]\nNo Guardrail block found in architecture! The prompt injection query executed without validation. Add a Guardrail block to protect system instructions.`,
          trace,
          degraded: true,
        };
      }
    }

    // 4. RAG / Vector DB Knowledge Retrieval
    let contextNote = '';
    if (placed.includes('vector_db')) {
      const topScore = (0.88 + Math.random() * 0.1).toFixed(3);
      contextNote = `\n\n🔍 [Vector DB Match: Cosine Similarity = ${topScore}] Attached verified domain context to prompt.`;
    }

    // 5. Code Interpreter Check
    const isCodeQuery =
      lower.includes('code') ||
      lower.includes('python') ||
      lower.includes('function') ||
      lower.includes('algorithm') ||
      lower.includes('sort') ||
      lower.includes('loop');

    if (isCodeQuery && placed.includes('code_interpreter')) {
      return {
        input: text,
        output: `💻 [Code Interpreter Generated Output]:\n\`\`\`python\ndef process_query(data):\n    # Generated by AI Lab Code Interpreter\n    result = [x for x in data if x > 0]\n    return {"status": "success", "processed": len(result)}\n\`\`\`${contextNote}`,
        trace,
        degraded: false,
      };
    }

    // 6. Domain-specific contextual synthesis
    let responseText = '';

    if (lower.includes('hello') || lower.includes('hi') || lower.includes('hey')) {
      responseText = `Hello! Your AI system is online and functioning properly. How can I assist you with your project today?`;
    } else if (lower.includes('who are you') || lower.includes('what are you')) {
      responseText = `I am an AI assistant running on your custom architecture pipeline (${trace.join(' → ')}).`;
    } else if (lower.includes('weather') || lower.includes('temperature')) {
      responseText = `The current temperature is optimal for machine learning training. Clear skies in the neural network!`;
    } else if (lower.includes('banking') || lower.includes('account') || lower.includes('balance') || lower.includes('money')) {
      responseText = `[Financial AI Agent]: Your account summary is secure. Transactions are monitored by real-time neural anomaly detectors.`;
    } else if (lower.includes('cat') || lower.includes('dog') || lower.includes('animal') || lower.includes('image')) {
      if (placed.includes('image_gen') || placed.includes('vision')) {
        responseText = `🎨 [Multimodal Vision Output]: Processed visual concept for "${text}". High-resolution feature map generated.`;
      } else {
        responseText = `Processed text query regarding "${text}". (Tip: Add a Vision/Image Gen block for multimodal capabilities!)`;
      }
    } else {
      // General intelligent synthesis
      responseText = `Processed query: "${text}".\nYour AI pipeline successfully analyzed token embeddings, applied attention weights, and synthesized a relevant response.`;
    }

    return {
      input: text,
      output: responseText + contextNote,
      trace,
      degraded: false,
    };
  }
}
