import { GlossaryTerm } from './types';

/**
 * AI glossary. Every term the curriculum leans on, in plain words first,
 * then the technical meaning, with a concrete example. Extend by appending.
 */
export const GLOSSARY: GlossaryTerm[] = [
  {
    slug: 'ai', name: 'Artificial Intelligence (AI)',
    simple: 'Software that does tasks which normally need human intelligence.',
    technical: 'Systems that perceive input, reason or learn patterns, and act — typically by learning from data rather than following only hand-written rules.',
    example: 'Your phone recognising your face to unlock.',
    icon: 'planet', related: ['machine-learning', 'deep-learning'],
  },
  {
    slug: 'machine-learning', name: 'Machine Learning (ML)',
    simple: 'Teaching computers to learn patterns from examples instead of being told every rule.',
    technical: 'A subset of AI where models improve on a task by optimising their parameters against data, minimising a loss over many examples.',
    example: 'A spam filter that learns junk mail from labelled examples.',
    icon: 'git-network', related: ['ai', 'training', 'deep-learning'],
  },
  {
    slug: 'deep-learning', name: 'Deep Learning',
    simple: 'Machine learning using neural networks with many layers.',
    technical: 'ML with multi-layer neural networks that learn hierarchical features directly from raw data, powering modern vision, speech and language systems.',
    example: 'The technology behind image recognition and modern chatbots.',
    icon: 'layers', related: ['machine-learning', 'neural-network'],
  },
  {
    slug: 'neural-network', name: 'Neural Network',
    simple: 'A flexible pattern-learner loosely inspired by how brain cells connect.',
    technical: 'Layers of interconnected units (neurons) with weighted connections; it learns by adjusting those weights to reduce prediction error.',
    example: 'A network that turns photo pixels into “cat” or “dog”.',
    icon: 'share-social', related: ['deep-learning', 'weights', 'training'],
  },
  {
    slug: 'weights', name: 'Weights',
    simple: 'The adjustable knobs a model tunes as it learns.',
    technical: 'Numerical parameters on a network’s connections; training adjusts them so the model maps inputs to correct outputs.',
    example: 'Turning “knobs” until the network reliably spots cats.',
    icon: 'options', related: ['neural-network', 'training'],
  },
  {
    slug: 'training', name: 'Training',
    simple: 'The process where a model learns from data by practising.',
    technical: 'Iteratively feeding examples, measuring error with a loss function, and updating parameters (e.g. via gradient descent) to reduce it.',
    example: 'Showing a model thousands of labelled photos until it learns.',
    icon: 'barbell', related: ['machine-learning', 'weights', 'inference'],
  },
  {
    slug: 'inference', name: 'Inference',
    simple: 'Using a trained model to make a prediction on new input.',
    technical: 'The forward pass at run time: the model applies its learned parameters to produce an output, without further learning.',
    example: 'Asking a trained model “is this email spam?” and getting an answer.',
    icon: 'flash', related: ['training', 'model'],
  },
  {
    slug: 'model', name: 'Model',
    simple: 'The trained “brain” that turns input into a prediction.',
    technical: 'The function defined by an architecture plus its learned parameters, mapping inputs to outputs for a task.',
    example: 'The saved file that powers a translation app.',
    icon: 'cube', related: ['training', 'inference'],
  },
  {
    slug: 'transformer', name: 'Transformer',
    simple: 'The AI design that reads a whole sentence at once and powers modern LLMs.',
    technical: 'A neural architecture built on self-attention that models relationships between all tokens in a sequence in parallel.',
    example: 'The architecture behind today’s large language models.',
    icon: 'grid', related: ['attention', 'llm', 'token'],
  },
  {
    slug: 'attention', name: 'Attention',
    simple: 'How a model decides which words matter most for the current word.',
    technical: 'A mechanism that computes weighted relevance between tokens, letting the model focus on the most informative parts of the input.',
    example: 'Linking “it” back to the right noun in a sentence.',
    icon: 'eye', related: ['transformer', 'token'],
  },
  {
    slug: 'token', name: 'Token',
    simple: 'A small chunk of text — a word or piece of a word — that a model reads.',
    technical: 'The unit of input/output for a language model; text is split into tokens, each mapped to an id and embedding.',
    example: '“unhappiness” might become tokens “un”, “happi”, “ness”.',
    icon: 'pricetag', related: ['llm', 'embedding', 'context-window'],
  },
  {
    slug: 'llm', name: 'Large Language Model (LLM)',
    simple: 'A big AI trained on huge amounts of text to understand and generate language.',
    technical: 'A transformer with billions of parameters trained to predict the next token, enabling text generation, reasoning and more.',
    example: 'The model that powers a chat assistant.',
    icon: 'chatbubbles', related: ['transformer', 'token', 'prompt'],
  },
  {
    slug: 'prompt', name: 'Prompt',
    simple: 'The instruction or question you give an AI to get a response.',
    technical: 'The input text conditioning an LLM’s generation; its wording strongly shapes the output.',
    example: '“Summarise this article in three bullet points.”',
    icon: 'create', related: ['llm', 'context-window', 'hallucination'],
  },
  {
    slug: 'context-window', name: 'Context Window',
    simple: 'How much text an AI can “keep in mind” at once.',
    technical: 'The maximum number of tokens a model can attend to in a single request, covering the prompt plus its response.',
    example: 'Paste a long document that fits in the window and ask about it.',
    icon: 'albums', related: ['token', 'llm', 'rag'],
  },
  {
    slug: 'temperature', name: 'Temperature',
    simple: 'A dial for how creative vs. predictable an AI’s answers are.',
    technical: 'A sampling parameter scaling output probabilities; low values make generation focused and deterministic, high values more random.',
    example: 'Low temperature for facts, higher for brainstorming.',
    icon: 'thermometer', related: ['llm', 'inference'],
  },
  {
    slug: 'hallucination', name: 'Hallucination',
    simple: 'When an AI states something false but sounds confident.',
    technical: 'Fluent, plausible output not grounded in facts or provided sources — a known failure mode of generative models.',
    example: 'An LLM inventing a book title that doesn’t exist.',
    icon: 'warning', related: ['llm', 'rag', 'prompt'],
  },
  {
    slug: 'embedding', name: 'Embedding',
    simple: 'Turning words or data into a list of numbers that captures meaning.',
    technical: 'A dense vector representation where semantically similar items sit close together in vector space.',
    example: '“King” and “queen” end up near each other as numbers.',
    icon: 'locate', related: ['vector', 'vector-search', 'token'],
  },
  {
    slug: 'vector', name: 'Vector',
    simple: 'An ordered list of numbers — how AI represents meaning.',
    technical: 'A point in high-dimensional space; distance/angle between vectors measures similarity.',
    example: '[0.12, -0.98, 0.34, …] representing a sentence.',
    icon: 'analytics', related: ['embedding', 'vector-search'],
  },
  {
    slug: 'vector-search', name: 'Vector Search',
    simple: 'Finding items by meaning instead of exact keywords.',
    technical: 'Nearest-neighbour search over embeddings, ranking items by similarity to a query vector.',
    example: 'Searching “cheap eats” and finding “affordable restaurants”.',
    icon: 'search', related: ['embedding', 'vector', 'rag'],
  },
  {
    slug: 'rag', name: 'Retrieval Augmented Generation (RAG)',
    simple: 'Letting an AI look up your documents before answering.',
    technical: 'A pattern that retrieves relevant context (often via vector search) and feeds it to an LLM to ground its response.',
    example: 'A support bot that answers from your product manuals.',
    icon: 'library', related: ['vector-search', 'llm', 'hallucination'],
  },
  {
    slug: 'fine-tuning', name: 'Fine-Tuning',
    simple: 'Further training a ready-made model on your own examples.',
    technical: 'Continuing training of a pretrained model on a narrower dataset to specialise its behaviour or style.',
    example: 'Adapting a general model to write in your brand’s voice.',
    icon: 'build', related: ['training', 'llm', 'model'],
  },
  {
    slug: 'agent', name: 'AI Agent',
    simple: 'An AI that can take actions and use tools to reach a goal, not just chat.',
    technical: 'A system that plans, calls tools, observes results and loops until a task is complete.',
    example: 'An assistant that searches, books and emails a summary for you.',
    icon: 'hardware-chip', related: ['tool-calling', 'llm', 'mcp'],
  },
  {
    slug: 'tool-calling', name: 'Tool Calling',
    simple: 'Letting an AI use external tools like search, code or a calculator.',
    technical: 'The model emits a structured call the app executes, then returns the result for the model to use.',
    example: 'An LLM calling a weather API to answer “will it rain today?”.',
    icon: 'construct', related: ['agent', 'mcp', 'llm'],
  },
  {
    slug: 'mcp', name: 'Model Context Protocol (MCP)',
    simple: 'A universal standard that lets any AI app plug into any tool or data source.',
    technical: 'An open protocol standardising how applications expose tools, resources and prompts to AI models over a common interface.',
    example: 'One connector that lets many AI apps read the same files.',
    icon: 'git-merge', related: ['agent', 'tool-calling'],
  },
];
