import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 11 — The Future of AI. Full lessons + question bank.
 * The finale of the curriculum: AGI, safety, ethics, robotics, careers and a
 * balanced look at the road ahead.
 */

const W = 'world-future-of-ai';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — AGI: The Dream of General AI
 * ================================================================== */
const l1 = bank('w11-l1', 'intermediate');
const w11l1Q: Question[] = [
  l1.mc('agi-def', 'What would Artificial General Intelligence (AGI) mean?',
    ['One system that can learn and do virtually any intellectual task a human can',
     'An AI that is slightly faster than today’s',
     'Any chatbot that writes well',
     'A robot with a metal body'],
    0, 'AGI is broad, flexible, human-like ability across tasks — not just being impressive at one thing.'),
  l1.tf('today', 'True AGI exists and is widely used today.', false,
    'No true general AI exists. Every system in use is narrow — great at specific tasks, not everything.'),
  l1.mc('gap', 'A big reason we’re not at AGI yet is that today’s AI…',
    ['Can’t flexibly transfer skills across very different tasks',
     'Runs too slowly to be useful',
     'Uses the wrong programming language',
     'Has never been connected to the internet'],
    0, 'A language model can’t suddenly learn to fold laundry. Real generality means adapting across unrelated domains.'),
  l1.mc('seems-general', 'Why can a modern chatbot SEEM close to general intelligence?',
    ['It handles huge variety within one domain — language',
     'It is secretly conscious',
     'It can already do any physical job',
     'It never makes mistakes'],
    0, 'Wide coverage inside language feels broad, but it’s still one domain. Breadth within a lane isn’t generality.'),
  l1.tf('common-sense', 'Lacking everyday common sense is one thing that separates today’s AI from AGI.', true,
    'Models have no lived experience, so they miss “obvious” things a person would catch — a real gap on the road to AGI.'),
  l1.mc('timeline', 'What’s the honest thing to say about WHEN AGI will arrive?',
    ['Nobody knows — expert predictions vary widely and are uncertain',
     'It definitely arrives next year',
     'It is scientifically impossible, forever',
     'It already arrived and was kept secret'],
    0, 'Serious researchers disagree by decades. Confident dates in either direction are hype, not knowledge.'),
  l1.match('terms', 'Match each term to its meaning.',
    [{ left: 'Narrow AI', right: 'Great at one specific task' },
     { left: 'AGI', right: 'Human-like ability across many tasks' },
     { left: 'Transfer', right: 'Reusing a skill on a different task' }],
    'Narrow AI is today’s reality; AGI is the goal; transfer is the ability that separates them.'),
  l1.mc('superhuman', 'An AI that is superhuman at chess is…',
    ['Still narrow — depth in one task isn’t general ability',
     'Automatically AGI because it beats humans',
     'Conscious',
     'Not really AI'],
    0, 'Superhuman-narrow is common. Generality is about breadth across tasks, not how deep one skill goes.'),
  l1.mc('scenario-claim', 'A headline claims “Company X has built true AGI.” A thoughtful reader should…',
    ['Stay sceptical and look for independent evidence across many tasks',
     'Assume it’s true because it’s a headline',
     'Panic that robots now rule us',
     'Conclude all jobs vanished overnight'],
    0, 'Extraordinary claims need strong, independent evidence. Marketing language often stretches “AGI” far past reality.', 'scenario'),
  l1.tf('progress', 'Progress toward more general AI can be real without today’s systems being AGI.', true,
    'Systems keep getting broader and more capable — genuine progress — yet still fall well short of true generality.'),
  l1.mc('view', 'The most realistic view of AGI is…',
    ['An open research goal — uncertain, not here yet, worth studying carefully',
     'A finished product you can buy today',
     'Pure fantasy that will never matter',
     'Something to either worship or fear'],
    0, 'Balanced beats hype and doom: AGI is unproven and uncertain, but a serious question worth thinking about clearly.'),
];

/* ================================================================== *
 * Lesson 2 — AI Safety: Keeping AI Helpful
 * ================================================================== */
const l2 = bank('w11-l2', 'intermediate');
const w11l2Q: Question[] = [
  l2.mc('safety-goal', 'What is “AI safety” mainly about?',
    ['Making sure AI systems behave helpfully and avoid causing harm',
     'Keeping AI hardware from overheating',
     'Making AI run faster',
     'Stopping people from using AI at all'],
    0, 'Safety is about behaviour: building systems that do what we intend and don’t cause harm along the way.'),
  l2.tf('alignment', 'Alignment means getting an AI’s behaviour to match what people actually want.', true,
    'A system can be capable yet misaligned — doing what you literally said, not what you meant. Alignment closes that gap.'),
  l2.mc('why-grows', 'Why does safety matter MORE as AI becomes more capable?',
    ['More capable systems can act at larger scale, so mistakes cost more',
     'Powerful AI never makes mistakes',
     'Safety only matters for small systems',
     'Capable systems don’t need any testing'],
    0, 'The more a system can do and the wider it’s deployed, the bigger the impact of any flaw — so care must scale too.'),
  l2.match('concepts', 'Match each safety idea to its meaning.',
    [{ left: 'Alignment', right: 'Behaviour matches human intent' },
     { left: 'Testing', right: 'Trying to find failures before release' },
     { left: 'Oversight', right: 'Humans monitoring and able to step in' }],
    'Alignment sets the target, testing hunts for problems, and oversight keeps humans in control.'),
  l2.tf('literal', 'An AI can follow instructions literally yet still do the wrong thing.', true,
    'Told to “maximise clicks”, a system might promote outrage. It obeyed the words but missed the real intent — a safety problem.'),
  l2.mc('testing', 'Before releasing an AI system, a key safety step is to…',
    ['Test it hard to find failures and harmful outputs early',
     'Skip testing to save time',
     'Assume it’s fine if it looks good once',
     'Hide any problems that show up'],
    0, 'Deliberately probing for failures before launch — including edge cases — catches harm before real users are affected.'),
  l2.mc('human-loop', 'For risky uses, a core safety practice is…',
    ['Keeping a human able to review, override or shut it down',
     'Removing all human involvement',
     'Trusting the most confident output',
     'Letting the AI decide with no limits'],
    0, 'Human oversight — the ability to step in and stop the system — is a foundational safeguard for higher-risk AI.'),
  l2.tf('solved', 'AI safety is a fully solved problem, so we can stop worrying about it.', false,
    'It’s an active, unfinished field. As systems grow more capable, new safety challenges keep appearing.'),
  l2.mc('scenario-tool', 'A team ships an AI assistant that sometimes gives dangerous instructions. The best fix is…',
    ['Add guardrails and testing so it refuses harmful requests',
     'Ignore it since it’s rare',
     'Remove all safety checks to reduce refusals',
     'Tell users it’s their fault'],
    0, 'Guardrails plus targeted testing reduce harmful outputs. Ignoring rare-but-serious failures is exactly the risk safety addresses.', 'scenario'),
  l2.order('process', 'Order a responsible release from earliest to latest.',
    ['Define what “safe and helpful” means for this system', 'Test hard for failures and harms', 'Add guardrails for the problems found', 'Release with human oversight in place', 'Monitor real use and improve'],
    'Safety is a lifecycle: set goals, test, mitigate, release carefully, then keep watching and improving.'),
  l2.tf('everyone', 'Safety is only the job of a few specialists, not everyday AI users.', false,
    'Specialists lead, but everyone using AI plays a part — reporting problems and using systems responsibly all help.'),
  l2.mc('balance', 'A balanced take on AI safety is that it…',
    ['Is a serious, practical engineering and ethics challenge — not sci-fi panic',
     'Is pointless because AI is harmless',
     'Is only about killer robots from movies',
     'Means we should ban all AI'],
    0, 'Real safety work is unglamorous and practical: testing, guardrails, oversight — grounded, not doom.'),
];

/* ================================================================== *
 * Lesson 3 — AI Ethics: Fairness, Bias & Responsibility
 * ================================================================== */
const l3 = bank('w11-l3', 'intermediate');
const w11l3Q: Question[] = [
  l3.mc('bias-source', 'Where does AI bias usually come from?',
    ['Patterns in the data the model learned from',
     'The colour of the app icon',
     'The brand of laptop used',
     'Random bad luck only'],
    0, 'A model learns whatever its data shows. If the data reflects unfair patterns, the model absorbs and can amplify them.'),
  l3.tf('inherit', 'AI can inherit and even amplify human biases present in its training data.', true,
    'Skewed history in, skewed predictions out — and at scale, a small bias can affect many people quickly.'),
  l3.mc('privacy', 'Why is privacy an ethical concern with AI?',
    ['AI systems often learn from and process large amounts of personal data',
     'AI dislikes being used',
     'Privacy only matters for phones',
     'AI cannot store any data at all'],
    0, 'Training and running AI can involve sensitive personal data, raising real questions about consent and protection.'),
  l3.match('ethics', 'Match each ethical idea to its meaning.',
    [{ left: 'Bias', right: 'Unfair skew learned from data' },
     { left: 'Privacy', right: 'Protecting people’s personal data' },
     { left: 'Accountability', right: 'Someone answerable for outcomes' }],
    'Fairness, privacy and accountability are three pillars of using AI responsibly.'),
  l3.tf('who', 'When an AI system causes harm, the people who build and deploy it share responsibility.', true,
    '“The algorithm did it” isn’t an excuse. Humans who design, choose and deploy a system are accountable for its impact.'),
  l3.mc('accountable', 'If a bank’s AI wrongly denies loans to one group, who is responsible?',
    ['The organisation that built and deployed the system',
     'Nobody — it’s just software',
     'The customers who applied',
     'The electricity company'],
    0, 'Accountability stays with the humans and organisations behind the system, not the code itself.'),
  l3.mc('reduce-bias', 'A practical way to reduce unfair bias is to…',
    ['Use more representative data and test outcomes across groups',
     'Use a fancier font',
     'Hide the results from users',
     'Add more colours to the interface'],
    0, 'Balanced, representative data plus checking results across different groups tackles bias at its root.'),
  l3.tf('neutral', 'AI is automatically neutral and objective, so it can’t be unfair.', false,
    'AI reflects its data and design choices, both made by people. “Neutral machine” is a myth — fairness must be built in.'),
  l3.mc('scenario-hiring', 'A hiring AI favours candidates from one background. The responsible response is…',
    ['Investigate the data, fix the bias, and add human review',
     'Keep using it because it’s automated',
     'Blame the rejected applicants',
     'Assume the machine must be right'],
    0, 'Audit the data and decisions, correct the skew, and keep humans in charge of consequential choices.', 'scenario'),
  l3.tf('transparency', 'Being able to explain how an AI reached a decision helps hold it accountable.', true,
    'Transparency lets people question and challenge outcomes — essential for fairness in high-stakes decisions.'),
  l3.mc('goal', 'The goal of AI ethics is best summarised as…',
    ['Building and using AI in ways that are fair, safe and accountable to people',
     'Making AI as fast as possible',
     'Avoiding all use of computers',
     'Letting AI decide everything unchecked'],
    0, 'Ethics keeps people at the centre: AI should serve human values, with someone answerable for its effects.'),
];

/* ================================================================== *
 * Lesson 4 — AI & Robotics: Minds Meet Machines
 * ================================================================== */
const l4 = bank('w11-l4', 'intermediate');
const w11l4Q: Question[] = [
  l4.mc('robotics-def', 'What do we mean by AI in robotics?',
    ['AI that senses and acts in the physical world through a machine body',
     'Any software running on a laptop',
     'A chatbot with no body',
     'A printed instruction manual'],
    0, 'Robotics puts AI into the physical world — perceiving surroundings and taking real, physical actions.'),
  l4.tf('harder', 'Acting in the messy physical world is often harder than working with pure data.', true,
    'The real world is unpredictable — lighting, obstacles, friction, surprises. Bodies must cope where pure software need not.'),
  l4.mc('self-driving', 'A self-driving car’s AI mainly has to…',
    ['Perceive its surroundings and make safe driving decisions in real time',
     'Write essays',
     'Play chess',
     'Translate languages'],
    0, 'It’s narrow AI for driving: reading sensors, predicting other road users, and steering safely — a hard physical task.'),
  l4.match('examples', 'Match each robot to what it does.',
    [{ left: 'Warehouse robot', right: 'Moves and sorts packages' },
     { left: 'Self-driving car', right: 'Navigates roads' },
     { left: 'Vacuum robot', right: 'Cleans floors autonomously' }],
    'Physical AI already helps in warehouses, roads and homes — narrow tasks, done in the real world.'),
  l4.tf('sci-fi', 'Today’s robots are conscious, general-purpose beings like in the movies.', false,
    'Real robots run narrow AI for specific jobs. They have no awareness or general ability — that’s science fiction.'),
  l4.mc('limit', 'A major limit of robots today is that they…',
    ['Struggle with unfamiliar situations and delicate, varied tasks',
     'Are too cheap to build',
     'Work perfectly in every situation',
     'Never need any sensors'],
    0, 'Robots do well on repetitive, structured tasks but stumble on the unexpected and the delicately dexterous.'),
  l4.mc('sensors', 'To act in the world, a robot first needs to…',
    ['Sense its environment with cameras or other sensors',
     'Connect to a printer',
     'Change its paint colour',
     'Play a sound'],
    0, 'Perception comes first: sensors turn the physical world into data the AI can reason about before acting.'),
  l4.tf('narrow', 'A robot’s AI is narrow — specialised for its particular job.', true,
    'A vacuum robot can’t drive a car. Like all today’s AI, physical robots are narrow specialists.'),
  l4.mc('scenario-warehouse', 'A warehouse robot handles standard boxes well but drops odd-shaped items. Why?',
    ['It was trained mostly on the common cases, so rare shapes are harder',
     'It dislikes odd shapes emotionally',
     'The lighting is too bright to work at all',
     'Robots can never grip anything'],
    0, 'Robots excel where the task is familiar and structured; unusual, under-seen cases are exactly where they falter.', 'scenario'),
  l4.order('pipeline', 'Order how a robot completes an action.',
    ['Sense the environment', 'Interpret the data', 'Decide what to do', 'Move to perform the action', 'Check the result and adjust'],
    'Sense → interpret → decide → act → check. Robotics is this loop running in the physical world, fast and repeatedly.'),
  l4.tf('progress', 'Physical AI is improving, but everyday general-purpose home robots aren’t here yet.', true,
    'Progress is real in narrow settings; a robot that does any household chore reliably remains out of reach for now.'),
  l4.mc('balance', 'A balanced view of AI robotics is that it…',
    ['Is genuinely useful in narrow, structured tasks but far from a sci-fi android',
     'Can already do anything a human can, physically',
     'Is useless and never works',
     'Is conscious and self-aware'],
    0, 'Robots help in real, specific ways today — while remaining narrow, unaware machines, not movie androids.'),
];

/* ================================================================== *
 * Lesson 5 — AI Careers: Working With AI
 * ================================================================== */
const l5 = bank('w11-l5', 'intermediate');
const w11l5Q: Question[] = [
  l5.mc('reshape', 'The most realistic view of AI and jobs is that AI…',
    ['Changes and automates parts of jobs, and creates new ones, over time',
     'Instantly replaces every job overnight',
     'Has no effect on any job ever',
     'Only destroys jobs and creates none'],
    0, 'AI reshapes work gradually — automating some tasks, changing others, and opening up brand-new roles.'),
  l5.tf('new-jobs', 'AI creates new kinds of jobs, not just removes old ones.', true,
    'New roles appear — building, guiding, checking and applying AI — alongside the tasks it automates.'),
  l5.mc('valuable-skills', 'Which human skills tend to stay valuable alongside AI?',
    ['Judgement, creativity, empathy and clear communication',
     'Only the ability to type fast',
     'Memorising facts a search engine can find',
     'Nothing — AI does it all'],
    0, 'Skills AI is weak at — judgement, creativity, human connection — become more valuable, not less.'),
  l5.match('roles', 'Match each AI-era role to what it involves.',
    [{ left: 'Prompt / AI user', right: 'Guides AI to do useful work' },
     { left: 'Reviewer', right: 'Checks AI output for errors' },
     { left: 'Domain expert', right: 'Applies AI wisely in a field' }],
    'Working with AI often means directing it, checking it, and pairing it with real-world expertise.'),
  l5.tf('replace-fear', 'The healthiest mindset is to fear AI and avoid learning it.', false,
    'Fear-and-avoid leaves you behind. Learning to use AI as a tool keeps you adaptable and more capable.'),
  l5.mc('augment', 'For most workers, AI is best thought of as…',
    ['A tool that augments what they do, handling routine parts',
     'A total replacement for all their skills',
     'Something to ignore completely',
     'A threat with no upside'],
    0, 'AI as an assistant — taking the repetitive load so people focus on judgement and creativity — is the common pattern.'),
  l5.mc('adapt', 'The best way to stay employable as AI grows is to…',
    ['Learn to work alongside AI and keep building human strengths',
     'Refuse to touch any AI tools',
     'Assume your job can never change',
     'Wait and hope nothing changes'],
    0, 'Adaptability wins: use AI where it helps, and double down on the human skills it can’t replicate.'),
  l5.tf('oversight-jobs', 'Checking and correcting AI output is itself becoming valuable work.', true,
    'Because AI can be confidently wrong, human review and quality control are real, growing responsibilities.'),
  l5.mc('scenario-worker', 'A writer worries AI will take their job. A balanced response is…',
    ['Use AI to draft and speed up work, focusing their skill on judgement and voice',
     'Quit writing entirely',
     'Refuse to learn any new tools',
     'Assume AI can fully replace human voice'],
    0, 'Pairing AI’s speed with irreplaceable human judgement and voice is how many workers stay ahead, not behind.', 'scenario'),
  l5.tf('history', 'New technologies have historically shifted jobs rather than ending work entirely.', true,
    'Past shifts (from farms to factories to offices) moved and reshaped work. AI is likely another shift, not the end of jobs.'),
  l5.mc('mindset', 'The most useful attitude toward AI and your career is…',
    ['Curious and proactive — learn it, use it, and grow the human skills it lacks',
     'Panicked and avoidant',
     'Certain that nothing will change',
     'Convinced AI makes all effort pointless'],
    0, 'Curiosity beats fear: understanding AI turns it from a threat into a tool that amplifies your own strengths.'),
];

/* ================================================================== *
 * Lesson 6 — The Road Ahead: The Future of AI
 * ================================================================== */
const l6 = bank('w11-l6', 'advanced');
const w11l6Q: Question[] = [
  l6.mc('balanced', 'After everything you’ve learned, the wisest overall view of AI is…',
    ['Powerful and useful, but limited — worth neither hype nor doom',
     'A magical solution to every problem',
     'A useless fad with no real value',
     'A conscious mind that will rule us'],
    0, 'The whole course points here: AI is a strong, imperfect tool. Clear eyes — not hype, not fear — use it best.'),
  l6.tf('recap-narrow', 'All AI in use today is still narrow — great at specific tasks, not everything.', true,
    'From the very first world to this one, the throughline holds: today’s AI is narrow, however impressive it looks.'),
  l6.mc('thoughtful-user', 'What does being a “thoughtful AI user” mean?',
    ['Using AI’s strengths while checking its output and knowing its limits',
     'Trusting every AI answer blindly',
     'Refusing to use AI at all',
     'Believing AI is always wrong'],
    0, 'Thoughtful use means leaning on what AI does well, verifying what matters, and staying aware of where it fails.'),
  l6.match('recap', 'Match each big idea to its one-line summary.',
    [{ left: 'How AI works', right: 'Learns patterns from data' },
     { left: 'Its limits', right: 'Can be biased and confidently wrong' },
     { left: 'Using it well', right: 'Verify, and keep humans in charge' }],
    'Learns from data; has real limits; use it with human judgement — the heart of the whole course.'),
  l6.tf('verify', 'Even a fluent, confident AI answer is worth sanity-checking for important decisions.', true,
    'Fluency isn’t truth. For anything that matters, verify — that habit is the mark of a skilled AI user.'),
  l6.mc('uncertain-future', 'The honest thing to say about AI’s long-term future is…',
    ['It’s uncertain — shaped by the choices people make along the way',
     'It’s fully known and fixed',
     'It’s guaranteed to be a disaster',
     'It’s guaranteed to be utopia'],
    0, 'The future isn’t written. How we build, govern and use AI will shape where it goes — that’s the hopeful part.'),
  l6.mc('role', 'What role do everyday people play in AI’s future?',
    ['A real one — how we use, question and demand from AI shapes its direction',
     'None at all — it’s decided by machines',
     'None — only governments matter',
     'None — the future is predetermined'],
    0, 'Users, voters and workers all influence how AI develops. Being informed and thoughtful is itself a contribution.'),
  l6.tf('hope-doom', 'A balanced outlook avoids both blind hype and helpless doom.', true,
    'Both extremes distort. Hopeful-but-realistic — clear about benefits AND risks — is the grounded, useful stance.'),
  l6.mc('scenario-friend', 'A friend says “AI will either save the world or destroy it.” The wisest reply is…',
    ['“It’s a powerful tool — the outcome depends on how we choose to use it”',
     '“You’re right, it’s definitely one or the other”',
     '“AI is magic, so who knows”',
     '“AI does nothing, so ignore it”'],
    0, 'Rejecting the either/or framing — and pointing to human choices — is exactly the balanced thinking this course builds.', 'scenario'),
  l6.order('journey', 'Order the mindset of a thoughtful AI user, start to finish.',
    ['Understand what AI is and how it learns', 'Know its strengths and its limits', 'Use it for what it does well', 'Verify important outputs', 'Stay curious as AI keeps changing'],
    'Understand → know limits → apply → verify → keep learning. That loop keeps you a wise user as AI evolves.'),
  l6.tf('finale', 'Understanding AI clearly is the best foundation for using it well in the years ahead.', true,
    'That’s the whole point of the journey: clear understanding turns AI from a mystery — or a threat — into a tool you command.'),
  l6.mc('closing', 'The single best takeaway from this entire course is…',
    ['See AI clearly — powerful, limited, and shaped by how people choose to use it',
     'AI is magic beyond understanding',
     'AI is always right and should decide everything',
     'AI is worthless and should be ignored'],
    0, 'Clear-eyed and balanced: that understanding is what lets you use AI wisely, safely and confidently. Well done.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD11_LESSONS: Lesson[] = [
  {
    id: 'w11-l1', worldId: W, order: 1,
    title: 'AGI: The Dream of General AI',
    subtitle: 'What “general” intelligence would really mean',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 60, coins: 8,
    description: 'Artificial General Intelligence — one system as flexible as a human mind — is AI’s biggest dream. See what it would mean, and why we’re not there yet.',
    realWorld: 'A chess engine can crush a grandmaster but can’t make you a sandwich or hold a conversation. Being brilliant at one thing says nothing about being generally intelligent.',
    explanation: 'AGI would be a single system that learns and performs almost any intellectual task a person can. Today’s AI is narrow — powerful in a lane, helpless outside it. Whether and when AGI arrives is genuinely uncertain, so the honest stance is careful curiosity, not hype or panic.',
    objectives: [
      'Define AGI and contrast it with narrow AI',
      'Explain why today’s systems fall short of general ability',
      'Hold a realistic, uncertain view of AGI',
    ],
    activity: {
      kind: 'bucket',
      title: 'Realistic Soon or Far Off?',
      instructions: 'Sort each capability by how close today’s AI really is to it.',
      config: {
        buckets: ['Realistic today / soon', 'Far off or unproven'],
        items: [
          { label: 'Translating between languages', bucket: 0 },
          { label: 'Recommending videos', bucket: 0 },
          { label: 'Recognising faces', bucket: 0 },
          { label: 'One system that does ANY human task', bucket: 1 },
          { label: 'Truly understanding like a person', bucket: 1 },
          { label: 'Learning any new skill on its own', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AGI = human-like flexibility across many tasks — not here yet.',
      'Today’s AI is narrow, however impressive it looks.',
      'When (or if) AGI arrives is genuinely uncertain.',
    ],
    commonMistakes: [
      'Calling a very capable chatbot “AGI” — breadth within one domain is still narrow.',
      'Trusting confident predictions about AGI’s exact arrival date.',
      'Treating AGI as either certain doom or certain utopia.',
    ],
    summary: 'AGI is a real research goal but an unproven one — today’s AI stays narrow and specialised.',
    prerequisiteLessonIds: ['w10-l6'],
    nextLessonId: 'w11-l2',
  },
  {
    id: 'w11-l2', worldId: W, order: 2,
    title: 'AI Safety: Keeping AI Helpful',
    subtitle: 'Building AI that does what we intend',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 65, coins: 9,
    description: 'As AI grows more capable, making sure it stays helpful — and doesn’t cause harm — becomes essential. That’s the practical, unglamorous work of AI safety.',
    realWorld: 'Tell a system to “maximise clicks” and it might push outrage and misinformation. It did what you said — not what you meant. Closing that gap is what safety is about.',
    explanation: 'AI safety is about behaviour: alignment (matching human intent), testing (finding failures early), and oversight (humans able to step in). It matters more as systems get more capable, because their mistakes reach further. It’s an active, unfinished field — grounded engineering, not sci-fi panic.',
    objectives: [
      'Explain alignment, testing and oversight',
      'Say why safety scales with capability',
      'Describe a responsible release process',
    ],
    activity: {
      kind: 'steps',
      title: 'A Responsible Release',
      instructions: 'Drag the steps into the order a careful team ships an AI system.',
      config: {
        steps: [
          'Define what “safe and helpful” means here',
          'Test hard for failures and harms',
          'Add guardrails for the problems found',
          'Release with human oversight in place',
          'Monitor real use and keep improving',
        ],
      },
    },
    keyTakeaways: [
      'Safety = alignment, testing and human oversight.',
      'Bigger capability means bigger impact from mistakes.',
      'It’s an active field — not a solved problem.',
    ],
    commonMistakes: [
      'Assuming a system that follows instructions literally is automatically safe.',
      'Skipping testing because the system “looks fine”.',
      'Thinking safety is only about sci-fi killer robots.',
    ],
    summary: 'AI safety is the practical work of keeping capable systems aligned, tested and under human control.',
    prerequisiteLessonIds: ['w11-l1'],
    nextLessonId: 'w11-l3',
  },
  {
    id: 'w11-l3', worldId: W, order: 3,
    title: 'AI Ethics: Fairness, Bias & Responsibility',
    subtitle: 'Keeping people at the centre',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'AI makes decisions that affect real people. Fairness, privacy and accountability decide whether that’s a force for good — and “the algorithm did it” is never an excuse.',
    realWorld: 'A hiring tool that quietly favours one background isn’t “neutral” — it learned a bias from its data, and the people who deployed it are responsible for the outcome.',
    explanation: 'AI reflects its data and its makers’ choices, so it can be biased, invade privacy, or make unfair decisions. Ethics keeps humans accountable: use representative data, protect personal information, explain decisions, and remember that people — not code — answer for the results.',
    objectives: [
      'Identify where AI bias comes from',
      'Explain privacy and accountability concerns',
      'Say who is responsible for AI decisions',
    ],
    activity: {
      kind: 'bucket',
      title: 'Ethical Concern or Myth?',
      instructions: 'Sort each statement about AI ethics into concern or myth.',
      config: {
        buckets: ['Real ethical concern', 'Myth / false comfort'],
        items: [
          { label: 'AI can inherit bias from its data', bucket: 0 },
          { label: 'AI can misuse personal data', bucket: 0 },
          { label: 'Humans stay accountable for AI harm', bucket: 0 },
          { label: 'AI is automatically neutral and fair', bucket: 1 },
          { label: '“The algorithm did it” excuses everyone', bucket: 1 },
          { label: 'Bias fixes itself with no effort', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Bias comes from data; it can be tested for and reduced.',
      'Privacy and fair treatment are core ethical duties.',
      'Humans, not algorithms, are accountable for outcomes.',
    ],
    commonMistakes: [
      'Believing AI is neutral just because it’s a machine.',
      'Blaming “the algorithm” instead of the people behind it.',
      'Assuming bias will disappear without deliberate work.',
    ],
    summary: 'Responsible AI means fairness, privacy and clear human accountability for every decision it touches.',
    prerequisiteLessonIds: ['w11-l2'],
    nextLessonId: 'w11-l4',
  },
  {
    id: 'w11-l4', worldId: W, order: 4,
    title: 'AI & Robotics: Minds Meet Machines',
    subtitle: 'When AI steps into the physical world',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 65, coins: 9,
    description: 'Robotics gives AI a body — sensors to perceive and motors to act. It’s genuinely useful in narrow tasks, but far from the conscious androids of the movies.',
    realWorld: 'A warehouse robot sorts standard boxes all day, then fumbles an odd-shaped item. Self-driving cars handle highways yet struggle with the unexpected. The physical world is hard.',
    explanation: 'Physical AI runs a loop: sense the world, interpret it, decide, act, and check the result. It shines in structured, repetitive tasks but stumbles on the unfamiliar and the delicate. Like all today’s AI, robots are narrow specialists — no awareness, no general ability.',
    objectives: [
      'Describe how AI perceives and acts in the world',
      'Explain why the physical world is hard for AI',
      'Judge what robots can and can’t do today',
    ],
    activity: {
      kind: 'steps',
      title: 'The Robot Action Loop',
      instructions: 'Order the steps a robot runs to complete a physical action.',
      config: {
        steps: [
          'Sense the environment',
          'Interpret the data',
          'Decide what to do',
          'Move to perform the action',
          'Check the result and adjust',
        ],
      },
    },
    keyTakeaways: [
      'Robotics = AI that senses and acts in the physical world.',
      'The real world is messy — it’s harder than pure data.',
      'Robots are narrow specialists, not sci-fi androids.',
    ],
    commonMistakes: [
      'Expecting today’s robots to be general-purpose or conscious.',
      'Assuming a robot good at one task can handle any task.',
      'Forgetting robots struggle most with rare, unfamiliar cases.',
    ],
    summary: 'AI robotics is useful in narrow, structured tasks — impressive, but still narrow and unaware.',
    prerequisiteLessonIds: ['w11-l3'],
    nextLessonId: 'w11-l5',
  },
  {
    id: 'w11-l5', worldId: W, order: 5,
    title: 'AI Careers: Working With AI',
    subtitle: 'Thriving alongside AI, not fearing it',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 70, coins: 10,
    description: 'AI reshapes work — automating some tasks, creating new roles, and raising the value of human judgement, creativity and empathy. The winning move is to work with it, not against it.',
    realWorld: 'A writer who uses AI to draft faster — then applies their own judgement and voice — gets more done than someone who either refuses AI or lets it write unchecked.',
    explanation: 'AI changes jobs gradually rather than erasing them overnight, and it creates new work: guiding AI, checking its output, and applying it wisely in a field. The skills that stay valuable are the ones AI is weak at — judgement, creativity, communication and human connection. Curiosity beats fear.',
    objectives: [
      'Explain how AI reshapes jobs over time',
      'Identify human skills that stay valuable',
      'Adopt a proactive mindset for working with AI',
    ],
    activity: {
      kind: 'bucket',
      title: 'What AI Does vs What Humans Do Best',
      instructions: 'Sort each strength into who handles it best today.',
      config: {
        buckets: ['AI handles well', 'Humans do best'],
        items: [
          { label: 'Fast first drafts', bucket: 0 },
          { label: 'Sorting huge amounts of data', bucket: 0 },
          { label: 'Repetitive routine tasks', bucket: 0 },
          { label: 'Judgement on tricky calls', bucket: 1 },
          { label: 'Genuine empathy and connection', bucket: 1 },
          { label: 'Original creative direction', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AI reshapes and creates jobs — it doesn’t simply erase them.',
      'Judgement, creativity and empathy stay valuable.',
      'Learn to work with AI as a tool, not fear it.',
    ],
    commonMistakes: [
      'Assuming AI will instantly replace whole jobs overnight.',
      'Refusing to learn AI tools and falling behind.',
      'Letting AI work go unchecked instead of adding human judgement.',
    ],
    summary: 'The best career move is to pair AI’s speed with the human strengths it can’t replicate.',
    prerequisiteLessonIds: ['w11-l4'],
    nextLessonId: 'w11-l6',
  },
  {
    id: 'w11-l6', worldId: W, order: 6,
    title: 'The Road Ahead: The Future of AI',
    subtitle: 'Your journey, and what comes next',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'This is the finish line. Pull everything together into one clear, balanced view — AI is powerful and limited, its future uncertain, and shaped by the choices thoughtful people make. Including you.',
    realWorld: 'When a friend says “AI will either save us or destroy us,” you now have a better answer: it’s a powerful tool, and the outcome depends on how we choose to build and use it.',
    explanation: 'Across every world you’ve learned how AI works (patterns from data), where it fails (bias, overconfidence, narrowness), and how to use it well (play to its strengths, verify what matters, keep humans in charge). The future isn’t written — it’s shaped by our choices. A thoughtful user understands AI, knows its limits, applies it wisely, verifies, and stays curious as it evolves.',
    objectives: [
      'Summarise a balanced, realistic view of AI',
      'Describe what it means to be a thoughtful AI user',
      'Recognise your own role in shaping AI’s future',
    ],
    activity: {
      kind: 'steps',
      title: 'The Thoughtful AI User',
      instructions: 'Arrange the mindset of a thoughtful AI user, from first step to lasting habit.',
      config: {
        steps: [
          'Understand what AI is and how it learns',
          'Know its strengths and its limits',
          'Use it for what it does well',
          'Verify important outputs',
          'Stay curious as AI keeps changing',
        ],
      },
    },
    keyTakeaways: [
      'AI is powerful and limited — neither hype nor doom fits.',
      'Being a thoughtful user means verifying and knowing the limits.',
      'The future is uncertain and shaped by human choices — including yours.',
    ],
    commonMistakes: [
      'Swinging to either blind hype or helpless doom.',
      'Trusting fluent, confident AI answers without checking.',
      'Believing the future is fixed and beyond anyone’s influence.',
    ],
    summary: 'You’ve reached the end: see AI clearly, use it wisely, and help shape where it goes next.',
    prerequisiteLessonIds: ['w11-l5'],
    nextLessonId: null,
  },
];

export const WORLD11_QUESTIONS: Question[] = [
  ...w11l1Q, ...w11l2Q, ...w11l3Q,
  ...w11l4Q, ...w11l5Q, ...w11l6Q,
];
