import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 1 — Understanding AI. Full lessons + question bank.
 * This file is the reference template for authoring every other world.
 */

const W = 'world-understanding-ai';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — What Is Artificial Intelligence?
 * ================================================================== */
const l1 = bank('w1-l1', 'beginner');
const w1l1Q: Question[] = [
  l1.mc('definition', 'Which statement best describes Artificial Intelligence?',
    ['Software that performs tasks that normally need human intelligence',
     'Any program written in Python',
     'A very fast calculator',
     'A robot with a metal body'],
    0, 'AI is about the task — perception, language, decisions — not the language it’s written in or whether it has a body.'),
  l1.tf('scope', 'AI always requires a physical robot body.', false,
    'Most AI is pure software: spam filters, translators and recommendations have no body at all.'),
  l1.mc('vs-software', 'What makes AI different from ordinary software?',
    ['It handles messy, real-world input like images or language',
     'It runs faster',
     'It uses more colours',
     'It never needs electricity'],
    0, 'Ordinary software follows exact rules on tidy input. AI copes with fuzzy, real-world input where no exact rule exists.'),
  l1.mc('everyday', 'Your phone unlocks by recognising your face. Is this AI?',
    ['Yes — recognising a face from a camera is a classic AI task',
     'No — phones are not intelligent',
     'No — it is just a password',
     'Only if the phone can talk'],
    0, 'Face recognition turns raw pixels into “this is you”. Learning to see patterns in messy input is exactly what AI does.', 'scenario'),
  l1.tf('calculator', 'A calculator adding 2 + 2 is an example of AI.', false,
    'A calculator follows one fixed rule with no learning or judgement — that is ordinary software, not AI.'),
  l1.mc('sign', 'Which is the clearest sign that something uses AI?',
    ['It improves with more data or handles inputs it was never explicitly programmed for',
     'It has a touchscreen',
     'It is connected to the internet',
     'It was expensive'],
    0, 'A hallmark of AI is generalising to new, unseen inputs — not price, screens or connectivity.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'AI', right: 'Machines doing tasks that need intelligence' },
     { left: 'Algorithm', right: 'A step-by-step recipe a computer follows' },
     { left: 'Data', right: 'The examples a system learns or works from' }],
    'AI is the goal, an algorithm is the recipe, and data is the raw material it works with.'),
  l1.mc('goal', 'The goal of AI is best summarised as:',
    ['Getting machines to do things that would need human intelligence',
     'Replacing all electricity with software',
     'Making websites load faster',
     'Storing files in the cloud'],
    0, 'Intelligence here means perceiving, understanding language, deciding — human-like tasks, done by machines.'),
  l1.tf('narrowness', 'Today’s AI can do one narrow job well, not everything a person can do.', true,
    'Every AI system today is specialised. A chess AI can’t drive a car. Broad, human-like ability doesn’t exist yet.'),
  l1.mc('example', 'Which of these is the best example of AI?',
    ['A spam filter that learns which emails are junk',
     'A light switch',
     'A printed calendar',
     'A stopwatch'],
    0, 'The spam filter improves from examples of junk vs. real mail — learning from data is the AI part.'),
  l1.mc('misconception', 'Which statement about AI is TRUE?',
    ['AI finds patterns in data to make useful guesses',
     'AI understands the world exactly like a human',
     'AI is always correct',
     'AI thinks and feels emotions'],
    0, 'AI is a powerful pattern-matcher. It doesn’t truly understand, isn’t always right, and has no feelings.'),
  l1.mc('input', 'AI is especially useful when the input is…',
    ['Messy and varied, like photos, speech or free text',
     'A single fixed number',
     'Always identical every time',
     'Already sorted alphabetically'],
    0, 'When inputs vary hugely and no rule fits all cases, learning from examples shines.'),
  l1.tf('written', 'Something is AI only if it is written in a special “AI language”.', false,
    'AI can be built in many languages. What matters is that the system learns or reasons — not the language used.'),
];

/* ================================================================== *
 * Lesson 2 — AI Isn’t Magic: Rules vs Learning
 * ================================================================== */
const l2 = bank('w1-l2', 'beginner');
const w1l2Q: Question[] = [
  l2.mc('two-approaches', 'What are the two main ways to make a computer “decide” something?',
    ['Hand-written rules, or learning patterns from data',
     'Magic and luck',
     'Faster chips and more colours',
     'Louder speakers and bigger screens'],
    0, 'Traditional software uses rules a human writes. AI instead learns the patterns from examples.'),
  l2.tf('rules-limit', 'Hand-written rules struggle when there are too many exceptions to list.', true,
    'You can’t write a rule for every way a cat can look in a photo. That’s exactly where learning wins.'),
  l2.mc('learning-when', 'Learning from data is the better approach when…',
    ['The pattern is complex and hard to describe with exact rules',
     'The task is a simple fixed calculation',
     'You only ever have one input',
     'You want the answer to never change'],
    0, 'If you can’t neatly write the rule (recognising speech, spotting spam), let the machine learn it from examples.'),
  l2.match('classify', 'Match each system to how it decides.',
    [{ left: 'Thermostat: if temp < 20, heat on', right: 'Hand-written rule' },
     { left: 'Recognising a friend in a photo', right: 'Learned from data' },
     { left: 'Tax form arithmetic', right: 'Hand-written rule' }],
    'Clear, listable logic → rules. Fuzzy perception with endless variety → learning.'),
  l2.tf('ai-magic', 'AI is a kind of magic that no one can explain.', false,
    'AI is math and data. It can be surprising, but every step — from data to prediction — is explainable in principle.'),
  l2.mc('spam', 'Why is learning better than rules for spam detection?',
    ['Spammers constantly change tactics, so fixed rules quickly go stale',
     'Rules are illegal for email',
     'Learning uses no computer power',
     'Email cannot be filtered with rules at all'],
    0, 'A learned filter adapts to new spam patterns from fresh examples; a fixed rule list falls behind.'),
  l2.mc('traditional', 'In traditional programming, the human provides…',
    ['The exact rules; the computer just follows them',
     'Only the data, never the rules',
     'Nothing at all',
     'The electricity only'],
    0, 'Traditional code = human writes rules. Machine learning flips this: human gives examples, machine finds the rule.'),
  l2.tf('ml-flip', 'In machine learning, the computer works out the rule from examples instead of being told it.', true,
    'That inversion — data in, rule out — is the core idea that separates ML from ordinary programming.'),
  l2.mc('bad-fit-rules', 'Which task is HARDEST to solve with hand-written rules?',
    ['Telling whether a photo contains a dog',
     'Adding two numbers',
     'Converting metres to centimetres',
     'Sorting names alphabetically'],
    0, 'Dogs vary endlessly in pose, breed and lighting — impossible to fully capture in rules, ideal for learning.'),
  l2.mc('good-fit-rules', 'Which task is a GOOD fit for simple rules (no AI needed)?',
    ['Calculating 8% sales tax on a price',
     'Understanding a spoken sentence',
     'Recognising handwriting',
     'Detecting sarcasm in a review'],
    0, 'Sales tax is one exact formula — a rule is perfect. The others are fuzzy and need learning.'),
  l2.tf('both', 'Real products often combine hand-written rules AND learned models.', true,
    'Many systems use rules for the clear parts and learned models for the messy parts — the best of both.'),
  l2.mc('explainable', 'Saying “AI isn’t magic” mainly means…',
    ['Its behaviour comes from data and math we can study',
     'It runs without any computer',
     'It always gives perfect answers',
     'It has secret feelings'],
    0, 'Understanding that AI is data + math (not magic) is what lets us improve it, debug it and trust it appropriately.'),
];

/* ================================================================== *
 * Lesson 3 — How Machines Learn From Examples
 * ================================================================== */
const l3 = bank('w1-l3', 'beginner');
const w1l3Q: Question[] = [
  l3.mc('core-idea', 'How does a machine “learn” in AI?',
    ['It sees many examples and adjusts itself to make better guesses',
     'It memorises a single answer',
     'It is given the final rule by a human',
     'It waits for the internet to tell it'],
    0, 'Learning = repeatedly guessing, checking against the right answer, and adjusting to reduce mistakes.'),
  l3.order('loop', 'Put the learning loop in the right order.',
    ['Show the model labelled examples', 'Model makes a guess', 'Compare the guess to the correct answer', 'Adjust the model to reduce the error', 'Repeat until it’s good enough'],
    'Guess → check → adjust, over and over. Each pass nudges the model closer to the right pattern.'),
  l3.tf('feedback', 'A model improves by comparing its guesses to the correct answers.', true,
    'That feedback signal — how wrong was I? — is what tells the model which way to adjust.'),
  l3.mc('child', 'Learning from examples is most like…',
    ['A child learning “dog” after seeing many dogs',
     'Reading one rule in a manual',
     'Rolling dice',
     'Copying a file'],
    0, 'Nobody defines “dog” with rules for a toddler — they generalise from many examples. Models do the same.'),
  l3.mc('generalise', 'The real test of learning is that the model…',
    ['Works on new examples it never saw during training',
     'Only repeats the exact examples it memorised',
     'Runs quickly',
     'Uses a large screen'],
    0, 'Generalisation — doing well on unseen data — is the goal. Just memorising the training set isn’t learning.'),
  l3.tf('memorise', 'A model that only repeats its training examples has truly learned.', false,
    'That’s memorising, not learning. Real learning generalises to inputs it hasn’t seen before.'),
  l3.mc('error', 'What does the model use the “error” for?',
    ['To know how much, and in which direction, to adjust',
     'To delete the data',
     'To change its colour',
     'Nothing — error is ignored'],
    0, 'Error is the compass. A big error means adjust more; the sign tells it which way.'),
  l3.match('terms', 'Match the learning term to its meaning.',
    [{ left: 'Example', right: 'One input paired with its correct answer' },
     { left: 'Guess', right: 'The model’s current prediction' },
     { left: 'Adjust', right: 'Change the model to reduce error' }],
    'Examples teach, guesses are attempts, and adjusting is how the model improves each round.'),
  l3.mc('more-rounds', 'Generally, more good practice rounds lead to…',
    ['A model that makes fewer mistakes — up to a point',
     'A model that forgets everything',
     'No change at all',
     'A heavier phone'],
    0, 'More rounds of guess-check-adjust usually reduce error, until the model has learned what the data can teach.'),
  l3.tf('human', 'Once trained, a model can make guesses without a human writing new rules.', true,
    'After learning, the model applies the pattern itself — no human hand-coding for each new input.'),
  l3.mc('practice', 'A student doing practice questions and checking answers is like…',
    ['A model training: guess, check, adjust, repeat',
     'A calculator',
     'A printed book that never changes',
     'A light switch'],
    0, 'Practice with feedback is exactly the training loop — that’s why the analogy holds so well.'),
  l3.mc('goal', 'The point of training is to end up with a model that…',
    ['Makes accurate guesses on new, real inputs',
     'Has seen the fewest examples possible',
     'Never changes during training',
     'Only works on the training examples'],
    0, 'We train so the model performs in the real world, on data it’s never encountered before.'),
];

/* ================================================================== *
 * Lesson 4 — Data: The Fuel of AI
 * ================================================================== */
const l4 = bank('w1-l4', 'beginner');
const w1l4Q: Question[] = [
  l4.mc('why-data', 'Why is data so important to AI?',
    ['Models learn their patterns from data — it’s what they learn from',
     'Data makes the screen brighter',
     'Data replaces the need for electricity',
     'Data is only used for decoration'],
    0, 'No data, nothing to learn from. The examples in the data literally shape what the model becomes.'),
  l4.tf('more-data', 'More high-quality, relevant data usually helps a model learn better.', true,
    'Up to a point, more good examples give the model a clearer, more reliable picture of the pattern.'),
  l4.mc('quality', 'Which matters MORE for a good model?',
    ['High-quality, relevant, correctly-labelled data',
     'Data in a prettier font',
     'Data stored on a newer laptop',
     'The colour of the folder it’s in'],
    0, 'Garbage in, garbage out. Clean, relevant, correctly-labelled data beats simply having more of it.'),
  l4.mc('garbage', 'What does “garbage in, garbage out” mean for AI?',
    ['Bad training data leads to a bad model',
     'Computers produce literal garbage',
     'You must recycle old data',
     'Data has a smell'],
    0, 'A model can only be as good as what it learns from. Flawed data teaches flawed patterns.'),
  l4.tf('bias', 'If the training data is one-sided, the model can become biased.', true,
    'A model learns whatever the data shows. Skewed data → skewed, unfair predictions.'),
  l4.mc('labels', 'In many learning tasks, each example includes…',
    ['An input and its correct answer (a label)',
     'Only a price',
     'Only the date',
     'Nothing at all'],
    0, 'For supervised learning, examples pair an input with the right answer so the model can learn the mapping.'),
  l4.match('data-terms', 'Match the term to its meaning.',
    [{ left: 'Label', right: 'The correct answer attached to an example' },
     { left: 'Dataset', right: 'A collection of examples' },
     { left: 'Bias', right: 'Skew learned from unbalanced data' }],
    'Labels teach the answer, a dataset is the pile of examples, and bias is what leaks in when that pile is lopsided.'),
  l4.mc('amount-scenario', 'A photo app recognises faces poorly for some groups of people. The most likely cause is…',
    ['Those groups were under-represented in the training data',
     'The camera is too new',
     'The app icon is the wrong colour',
     'Phones dislike photos'],
    0, 'Under-representation in data is a classic source of unfair performance — the model simply saw too few examples.', 'scenario'),
  l4.tf('free', 'Collecting good, correctly-labelled data usually takes real effort.', true,
    'Gathering, cleaning and labelling data is often the hardest, most time-consuming part of building AI.'),
  l4.mc('relevance', 'To predict house prices, the most useful data would be…',
    ['Past house sales with size, location and price',
     'A list of everyone’s favourite colour',
     'Random song lyrics',
     'The weather on Mars'],
    0, 'Data must be relevant to the task. Irrelevant data teaches nothing useful about house prices.'),
  l4.mc('representative', 'Good training data should be…',
    ['Representative of the real cases the model will face',
     'As unusual as possible',
     'Always about a single example',
     'Kept secret from the model'],
    0, 'If the data reflects real-world variety, the model generalises well. If it doesn’t, it fails on real inputs.'),
  l4.tf('fuel', 'Calling data the “fuel” of AI means models can’t run or learn without it.', true,
    'Just like an engine needs fuel, a learning system needs data to learn from and improve.'),
];

/* ================================================================== *
 * Lesson 5 — Narrow AI vs General AI
 * ================================================================== */
const l5 = bank('w1-l5', 'beginner');
const w1l5Q: Question[] = [
  l5.mc('narrow-def', 'What is “narrow AI”?',
    ['AI that is very good at one specific task',
     'AI that can do absolutely anything a human can',
     'AI that only runs at night',
     'AI with a small screen'],
    0, 'Narrow AI masters a single job — chess, translation, face unlock. It can’t transfer that skill to unrelated tasks.'),
  l5.tf('today', 'Every AI system in use today is narrow AI.', true,
    'From chatbots to self-driving cars, all current AI is specialised. General, human-like AI does not exist yet.'),
  l5.mc('general-def', 'What would “general AI” (AGI) mean?',
    ['One system that can learn and do virtually any intellectual task a human can',
     'AI that is slightly faster',
     'AI that works offline',
     'AI that only plays chess'],
    0, 'AGI would flexibly handle any task, like a person. It’s a research goal, not a shipping product.'),
  l5.mc('chatbot', 'A powerful chatbot that writes essays and code is…',
    ['Still narrow AI — impressive, but specialised in language tasks',
     'General AI, because it seems smart',
     'Not AI at all',
     'A calculator'],
    0, 'Breadth within language is still narrow. It can’t, say, physically repair a car — general ability it isn’t.'),
  l5.match('examples', 'Match each system to its type.',
    [{ left: 'Chess engine', right: 'Narrow AI' },
     { left: 'Spam filter', right: 'Narrow AI' },
     { left: 'A mind that can do any human task', right: 'General AI (doesn’t exist yet)' }],
    'Real systems are narrow specialists. The “do anything” mind is still hypothetical.'),
  l5.tf('agi-exists', 'General AI already exists and is widely used.', false,
    'No true general AI exists today. Claims otherwise usually confuse a very capable narrow system for AGI.'),
  l5.mc('transfer', 'The key limitation of narrow AI is that it…',
    ['Can’t transfer its skill to unrelated tasks',
     'Uses too little electricity',
     'Is always slow',
     'Can never be useful'],
    0, 'A face-recognition model can’t suddenly translate French. Each narrow system is boxed into its trained task.'),
  l5.mc('why-seems', 'Why do some narrow systems SEEM general?',
    ['They handle many variations within one domain, like language',
     'They are secretly conscious',
     'They can do any physical job',
     'They never make mistakes'],
    0, 'Wide coverage inside one domain feels broad, but it’s still one domain — that’s narrow AI doing a lot.'),
  l5.tf('super', 'Being superhuman at one task (like chess) makes an AI general.', false,
    'Superhuman-narrow is common (chess, Go). Generality is about breadth across tasks, not depth in one.'),
  l5.mc('spectrum', 'The honest way to describe modern AI is…',
    ['Narrow systems, some extremely capable within their domain',
     'Fully general human-like minds',
     'Conscious beings',
     'Useless toys'],
    0, 'Modern AI is narrow but often remarkable inside its lane — a fair, accurate framing.'),
  l5.mc('driving', 'A self-driving car’s AI is…',
    ['Narrow AI focused on driving-related perception and decisions',
     'General AI',
     'Not AI',
     'A simple calculator'],
    0, 'It’s highly specialised for driving. Outside that task it has no ability — classic narrow AI.'),
  l5.tf('goal', 'Understanding narrow vs general helps set realistic expectations of AI.', true,
    'Knowing today’s AI is narrow keeps hype in check and helps you judge what a system can and can’t do.'),
];

/* ================================================================== *
 * Lesson 6 — AI You Already Use Every Day
 * ================================================================== */
const l6 = bank('w1-l6', 'beginner');
const w1l6Q: Question[] = [
  l6.mc('recommendations', 'When a streaming app suggests what to watch next, it’s using…',
    ['AI that learned your taste from viewing patterns',
     'A human choosing for you live',
     'Pure random chance',
     'A printed TV guide'],
    0, 'Recommendation systems learn patterns from what people watch to predict what you’ll like.'),
  l6.tf('autocomplete', 'Predictive text and autocomplete on your phone use AI.', true,
    'They predict the next word from patterns in language and your habits — a small but real AI feature.'),
  l6.match('daily', 'Match the everyday feature to what AI does in it.',
    [{ left: 'Photo app “people” albums', right: 'Recognises faces' },
     { left: 'Email spam folder', right: 'Classifies junk vs real' },
     { left: 'Maps arrival time', right: 'Predicts traffic' }],
    'Perception (faces), classification (spam) and prediction (traffic) are everyday AI you already rely on.'),
  l6.mc('voice', 'A voice assistant understanding “set a timer” relies on…',
    ['Speech recognition and language understanding — both AI',
     'A hidden human listening',
     'A mechanical spring',
     'Nothing — it guesses randomly'],
    0, 'Turning your audio into text and then into intent are two AI tasks working together.'),
  l6.tf('everywhere', 'AI is only found in expensive, specialised gadgets.', false,
    'AI is woven into everyday apps — search, keyboards, cameras, maps — most of it invisible.'),
  l6.mc('not-ai', 'Which everyday tool most likely does NOT need AI?',
    ['A basic calculator app',
     'Photo face-tagging',
     'Video recommendations',
     'Voice-to-text'],
    0, 'A calculator runs fixed formulas — no learning needed. The others learn patterns from data.'),
  l6.mc('search', 'When search understands what you MEAN, not just exact words, that’s…',
    ['AI matching meaning, not just keywords',
     'A coincidence',
     'A faster hard drive',
     'A brighter screen'],
    0, 'Modern search uses AI to match intent and meaning, so “cheap eats near me” finds affordable restaurants.'),
  l6.tf('bank', 'Banks use AI to flag unusual transactions as possible fraud.', true,
    'Fraud detection learns your normal spending pattern and flags anomalies — a widespread, useful AI application.'),
  l6.mc('camera', 'Your phone camera brightening a dark photo automatically is…',
    ['AI enhancing the image based on learned patterns',
     'The lens physically changing shape',
     'Magic',
     'A human editing it for you'],
    0, 'Computational photography uses AI to improve shots — recognising scenes and adjusting them intelligently.'),
  l6.mc('scenario-shop', 'An online shop shows you products “you might like”. This is…',
    ['A recommendation model predicting your preferences',
     'A random product each time',
     'A staff member picking manually for you',
     'Not related to AI'],
    0, 'It predicts what you’ll want from patterns across many shoppers and your own history — AI at work.', 'scenario'),
  l6.tf('invisible', 'Most AI you use day to day is invisible, running quietly inside apps.', true,
    'You rarely see “AI” labelled — it just makes features like autocorrect, filters and suggestions work.'),
];

/* ================================================================== *
 * Lesson 7 — What AI Gets Wrong
 * ================================================================== */
const l7 = bank('w1-l7', 'intermediate');
const w1l7Q: Question[] = [
  l7.mc('not-perfect', 'A realistic view of AI is that it…',
    ['Is powerful but makes mistakes and has real limits',
     'Is always correct',
     'Never has any use',
     'Understands everything perfectly'],
    0, 'AI is a strong tool, not an oracle. Knowing its failure modes is part of using it well.'),
  l7.tf('bias-again', 'AI can inherit human bias from the data it learns on.', true,
    'If historical data reflects unfair patterns, a model can learn and even amplify them.'),
  l7.mc('confident-wrong', 'A tricky failure of AI is that it can be…',
    ['Confidently wrong — giving a wrong answer that sounds certain',
     'Too quiet to hear',
     'Unable to produce any output',
     'Only wrong when unplugged'],
    0, 'Models often express no doubt even when mistaken, which is why human review matters for important decisions.'),
  l7.match('limits', 'Match the limitation to an example.',
    [{ left: 'Bias', right: 'Worse results for under-represented groups' },
     { left: 'Overconfidence', right: 'A sure-sounding but wrong answer' },
     { left: 'Data gaps', right: 'Fails on cases it never saw' }],
    'Bias, overconfidence and missing data are three of the most common ways AI goes wrong.'),
  l7.tf('common-sense', 'AI can lack common sense that humans take for granted.', true,
    'Models have no lived experience. They can miss “obvious” things that any person would catch.'),
  l7.mc('high-stakes', 'For high-stakes decisions (medical, legal), the safest approach is…',
    ['Use AI to assist, but keep a human in charge of the decision',
     'Let AI decide alone with no review',
     'Never use computers at all',
     'Trust whichever answer sounds most confident'],
    0, 'AI as an assistant with human oversight captures the benefits while guarding against its mistakes.'),
  l7.mc('edge-case', 'AI tends to struggle most with…',
    ['Rare or unusual cases it saw little of in training',
     'The exact examples it trained on',
     'Very common, typical inputs',
     'Being switched on'],
    0, 'Rare “edge cases” are under-learned. Familiar, common inputs are where models do best.'),
  l7.tf('never-wrong', 'A confident AI answer is guaranteed to be correct.', false,
    'Confidence and correctness are different. AI can sound certain and still be wrong — always sanity-check.'),
  l7.mc('scenario-medical', 'An AI flags a scan as “healthy” with high confidence. A doctor should…',
    ['Treat it as a helpful second opinion, not the final word',
     'Ignore their own training entirely',
     'Accept it without any review',
     'Assume the machine can’t be questioned'],
    0, 'AI can support experts, but a human must own high-stakes calls — the model can be confidently wrong.', 'scenario'),
  l7.mc('improve', 'How can many AI mistakes be reduced?',
    ['Better, more representative data and human oversight',
     'A shinier case',
     'Turning the brightness up',
     'Using more emojis'],
    0, 'Fixing data gaps and bias, plus keeping humans in the loop, addresses the root causes of many failures.'),
  l7.tf('understand', 'AI produces answers by matching patterns, not by truly understanding meaning.', true,
    'This is why it can be fluent yet wrong — it’s predicting plausible patterns, not comprehending like a human.'),
];

/* ================================================================== *
 * Lesson 8 — AI Myths vs Reality
 * ================================================================== */
const l8 = bank('w1-l8', 'intermediate');
const w1l8Q: Question[] = [
  l8.mc('conscious', 'Myth or reality: “Today’s AI is conscious and has feelings.”',
    ['Myth — AI has no awareness or emotions',
     'Reality — AI feels happy and sad',
     'Reality — AI is alive',
     'Myth — but only on weekends'],
    0, 'AI processes patterns in data. It has no inner experience, awareness or emotions.'),
  l8.tf('learns', 'Reality check: modern AI learns patterns from data.', true,
    'This one is true — learning patterns from examples is exactly how modern AI works.'),
  l8.mc('replace-all', 'Myth or reality: “AI will instantly replace every human job.”',
    ['Myth — AI changes and automates parts of jobs, gradually',
     'Reality — all jobs vanished last year',
     'Reality — humans are now banned from working',
     'Myth — AI can’t do anything at all'],
    0, 'AI automates tasks and reshapes work over time; the “instant total replacement” story is a myth.'),
  l8.match('sort', 'Sort each statement.',
    [{ left: 'AI can be biased', right: 'Reality' },
     { left: 'AI understands like a human', right: 'Myth' },
     { left: 'AI predicts using patterns', right: 'Reality' }],
    'Bias and pattern-prediction are real; human-like understanding is the myth.'),
  l8.tf('sci-fi', 'The evil, self-aware robots of movies reflect how real AI works today.', false,
    'That’s science fiction. Real AI is narrow, unaware software — no goals, plots or self-awareness.'),
  l8.mc('mistakes', 'Myth or reality: “AI never makes mistakes.”',
    ['Myth — AI regularly makes errors',
     'Reality — AI is flawless',
     'Reality — only humans err',
     'Myth — AI makes mistakes only when asked'],
    0, 'AI makes plenty of mistakes, especially on unusual inputs or biased data.'),
  l8.mc('magic-again', 'Myth or reality: “AI is magic no one can explain.”',
    ['Myth — AI is data and math we can study',
     'Reality — it truly is magic',
     'Reality — it runs on wishes',
     'Myth — but only to experts'],
    0, 'AI is built from data and mathematics. Complex, yes; magic, no.'),
  l8.tf('data-driven', 'Reality: an AI’s behaviour is shaped by the data it was trained on.', true,
    'Change the data, change the model. Its strengths, weaknesses and biases all trace back to its training data.'),
  l8.mc('understanding', 'Myth or reality: “AI understands language the way people do.”',
    ['Myth — it predicts likely patterns without human understanding',
     'Reality — it fully understands meaning',
     'Reality — it has memories of a childhood',
     'Myth — it understands only spoken words'],
    0, 'AI generates fluent text by pattern prediction, not by grasping meaning the way a person does.'),
  l8.mc('scenario-claim', 'A headline says “AI has become self-aware.” The wise response is…',
    ['Be sceptical — no evidence supports AI self-awareness today',
     'Panic immediately',
     'Assume it must be true because it’s a headline',
     'Conclude robots now rule the world'],
    0, 'Extraordinary claims need extraordinary evidence. Current AI shows no signs of awareness.', 'scenario'),
  l8.tf('useful', 'Reality: despite its limits, AI is genuinely useful across many fields.', true,
    'Seeing AI clearly — powerful but limited, no magic, no consciousness — lets you use it wisely and confidently.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD1_LESSONS: Lesson[] = [
  {
    id: 'w1-l1', worldId: W, order: 1,
    title: 'What Is Artificial Intelligence?',
    subtitle: 'The big picture, in plain words',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'Strip away the hype and see what AI actually is: software that tackles tasks which normally need human intelligence.',
    realWorld: 'When your phone unlocks by seeing your face, it’s doing something no fixed rule could — turning messy pixels into “that’s you”. That’s AI.',
    objectives: [
      'Define AI in one clear sentence',
      'Tell AI apart from ordinary software',
      'Spot everyday examples of AI',
    ],
    activity: {
      kind: 'bucket',
      title: 'AI or Not AI?',
      instructions: 'Tap each item and drop it into the right bucket. Which of these actually use AI?',
      config: {
        buckets: ['Uses AI', 'Not AI'],
        items: [
          { label: 'Face unlock', bucket: 0 },
          { label: 'Spam filter', bucket: 0 },
          { label: 'Voice assistant', bucket: 0 },
          { label: 'Netflix recommendations', bucket: 0 },
          { label: 'A calculator', bucket: 1 },
          { label: 'A light switch', bucket: 1 },
          { label: 'A printed calendar', bucket: 1 },
          { label: 'A stopwatch', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AI = machines doing tasks that normally need human intelligence.',
      'It’s software, not necessarily a robot.',
      'The AI part is coping with messy, real-world input — not following fixed rules.',
    ],
    prerequisiteLessonIds: [],
    nextLessonId: 'w1-l2',
  },
  {
    id: 'w1-l2', worldId: W, order: 2,
    title: 'AI Isn’t Magic: Rules vs Learning',
    subtitle: 'Two ways a computer can decide',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 5,
    description: 'Every computer decision comes from one of two places: rules a human wrote, or patterns a machine learned. Knowing which is which demystifies AI.',
    realWorld: 'A thermostat follows a rule: if it’s cold, turn on heat. Recognising your friend in a photo can’t be written as rules — the machine has to learn it.',
    objectives: [
      'Contrast hand-written rules with learning from data',
      'Decide which approach fits a given task',
      'Explain why “AI isn’t magic”',
    ],
    activity: {
      kind: 'bucket',
      title: 'Rules or Learned?',
      instructions: 'Sort each system by how it makes decisions.',
      config: {
        buckets: ['Hand-written rules', 'Learned from data'],
        items: [
          { label: 'Thermostat (if cold → heat)', bucket: 0 },
          { label: 'Sales-tax calculation', bucket: 0 },
          { label: 'Sorting names A–Z', bucket: 0 },
          { label: 'Recognising a face', bucket: 1 },
          { label: 'Spam detection', bucket: 1 },
          { label: 'Translating a sentence', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Traditional software: humans write the rules.',
      'Machine learning: the machine finds the rule from examples.',
      'Use learning when the pattern is too complex to write down.',
    ],
    prerequisiteLessonIds: ['w1-l1'],
    nextLessonId: 'w1-l3',
  },
  {
    id: 'w1-l3', worldId: W, order: 3,
    title: 'How Machines Learn From Examples',
    subtitle: 'Guess, check, adjust, repeat',
    difficulty: 'beginner', estimatedMinutes: 7, xp: 50, coins: 5,
    description: 'Learning isn’t memorising — it’s a loop of guessing, checking against the right answer, and adjusting to do better next time.',
    realWorld: 'A toddler learns “dog” not from a definition but from seeing many dogs. Show enough labelled examples and a model generalises the same way.',
    objectives: [
      'Describe the guess–check–adjust learning loop',
      'Explain why generalising beats memorising',
      'Relate model training to human practice',
    ],
    activity: {
      kind: 'steps',
      title: 'Build the Learning Loop',
      instructions: 'Drag the steps into the order a model actually learns in.',
      config: {
        steps: [
          'Show the model labelled examples',
          'Model makes a guess',
          'Compare the guess to the correct answer',
          'Adjust the model to reduce the error',
          'Repeat until it’s good enough',
        ],
      },
    },
    keyTakeaways: [
      'Learning = guess → check → adjust, many times.',
      'The error signal tells the model how to improve.',
      'Success means working on new, unseen inputs — not memorising.',
    ],
    prerequisiteLessonIds: ['w1-l2'],
    nextLessonId: 'w1-l4',
  },
  {
    id: 'w1-l4', worldId: W, order: 4,
    title: 'Data: The Fuel of AI',
    subtitle: 'Better data, better model',
    difficulty: 'beginner', estimatedMinutes: 7, xp: 60, coins: 8,
    description: 'A model is only as good as what it learns from. Data quality, relevance and balance shape everything the model becomes.',
    realWorld: 'Teach someone to cook using only photos of burnt food, and that’s what they’ll make. Feed a model skewed data and it learns skewed patterns.',
    objectives: [
      'Explain why data is central to AI',
      'Judge what makes data good or bad',
      'Connect biased data to biased results',
    ],
    activity: {
      kind: 'slider',
      title: 'Data & Accuracy',
      instructions: 'Slide to change how many good training examples the model sees. Watch what happens to its performance.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Training examples',
        stops: [
          { upTo: 5, title: 'Almost none', detail: 'The model barely learns — it’s basically guessing.' },
          { upTo: 30, title: 'A little', detail: 'It grasps the basics but stumbles on anything unusual.' },
          { upTo: 70, title: 'A good amount', detail: 'Now it’s reliable on most everyday inputs.' },
          { upTo: 100, title: 'Plenty (and clean)', detail: 'Strong, dependable performance — good data pays off.' },
        ],
      },
    },
    keyTakeaways: [
      'Models learn their patterns from data — no data, no learning.',
      'Quality and relevance matter more than raw quantity.',
      'Skewed data leads to biased, unfair models.',
    ],
    prerequisiteLessonIds: ['w1-l3'],
    nextLessonId: 'w1-l5',
  },
  {
    id: 'w1-l5', worldId: W, order: 5,
    title: 'Narrow AI vs General AI',
    subtitle: 'Why every AI today is a specialist',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 60, coins: 8,
    description: 'All AI in use today is “narrow” — brilliant at one job, useless at unrelated ones. The all-purpose “general AI” of movies doesn’t exist yet.',
    realWorld: 'A chess engine can crush a grandmaster but can’t make you a sandwich. Being superhuman at one task says nothing about the next.',
    objectives: [
      'Define narrow AI and general AI',
      'Explain why today’s systems are all narrow',
      'Avoid mistaking a capable narrow system for AGI',
    ],
    activity: {
      kind: 'bucket',
      title: 'Narrow or General?',
      instructions: 'Sort each system. Remember — general AI doesn’t exist yet.',
      config: {
        buckets: ['Narrow AI', 'General AI (doesn’t exist yet)'],
        items: [
          { label: 'Chess engine', bucket: 0 },
          { label: 'Chatbot that writes essays', bucket: 0 },
          { label: 'Self-driving car', bucket: 0 },
          { label: 'Spam filter', bucket: 0 },
          { label: 'A mind that can do ANY human task', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Narrow AI = great at one specific task.',
      'General AI = human-like flexibility across tasks — not here yet.',
      'A very capable narrow system is still narrow.',
    ],
    prerequisiteLessonIds: ['w1-l4'],
    nextLessonId: 'w1-l6',
  },
  {
    id: 'w1-l6', worldId: W, order: 6,
    title: 'AI You Already Use Every Day',
    subtitle: 'The invisible AI all around you',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 60, coins: 8,
    description: 'You already rely on AI dozens of times a day — usually without noticing. Learn to spot it in the apps you use.',
    realWorld: 'Autocomplete finishing your sentence, maps predicting traffic, your camera brightening a dark photo — all quiet, everyday AI.',
    objectives: [
      'Recognise common everyday AI features',
      'Separate AI features from plain software',
      'Appreciate how invisible most AI is',
    ],
    activity: {
      kind: 'bucket',
      title: 'Spot the Everyday AI',
      instructions: 'Which of these features are powered by AI, and which are just plain software?',
      config: {
        buckets: ['Powered by AI', 'Just plain software'],
        items: [
          { label: 'Autocomplete / predictive text', bucket: 0 },
          { label: 'Photo face-tagging', bucket: 0 },
          { label: 'Maps traffic prediction', bucket: 0 },
          { label: 'Video recommendations', bucket: 0 },
          { label: 'A basic calculator', bucket: 1 },
          { label: 'A PDF viewer', bucket: 1 },
          { label: 'A digital clock', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AI powers search, keyboards, cameras, maps and feeds.',
      'Fixed-formula tools (calculators, clocks) aren’t AI.',
      'Most AI is invisible — it just makes features work.',
    ],
    prerequisiteLessonIds: ['w1-l5'],
    nextLessonId: 'w1-l7',
  },
  {
    id: 'w1-l7', worldId: W, order: 7,
    title: 'What AI Gets Wrong',
    subtitle: 'Powerful, but far from perfect',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Using AI wisely means knowing how it fails: bias, overconfidence, missing common sense and trouble with rare cases.',
    realWorld: 'An AI can label a scan “healthy” with total confidence and still be wrong. That’s why a human expert stays in charge of big decisions.',
    objectives: [
      'List common ways AI fails',
      'Explain why AI can be confidently wrong',
      'Choose when to keep a human in the loop',
    ],
    activity: {
      kind: 'bucket',
      title: 'Reliable or Risky?',
      instructions: 'Where can AI be trusted, and where should we be careful? Sort each task.',
      config: {
        buckets: ['AI is usually reliable', 'Be careful — higher risk'],
        items: [
          { label: 'Recognising common objects', bucket: 0 },
          { label: 'Filtering obvious spam', bucket: 0 },
          { label: 'Suggesting a song', bucket: 0 },
          { label: 'Diagnosing illness alone', bucket: 1 },
          { label: 'Deciding someone’s loan by itself', bucket: 1 },
          { label: 'Judging sarcasm or nuance', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AI can be biased, overconfident and weak on rare cases.',
      'Confidence is not the same as correctness.',
      'For high-stakes calls, keep a human in charge.',
    ],
    prerequisiteLessonIds: ['w1-l6'],
    nextLessonId: 'w1-l8',
  },
  {
    id: 'w1-l8', worldId: W, order: 8,
    title: 'AI Myths vs Reality',
    subtitle: 'Separating hype from fact',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 70, coins: 10,
    description: 'Cut through the headlines. Sort what’s true about AI from what’s science fiction — and finish World 1 seeing AI clearly.',
    realWorld: 'Movies show conscious, scheming robots. Real AI is unaware software predicting patterns — powerful, but nothing like the sci-fi version.',
    objectives: [
      'Debunk common AI myths',
      'Confirm what is actually true about AI',
      'Form a clear, realistic mental model of AI',
    ],
    activity: {
      kind: 'bucket',
      title: 'Myth or Reality?',
      instructions: 'Sort each statement into Myth or Reality.',
      config: {
        buckets: ['Myth', 'Reality'],
        items: [
          { label: 'AI is conscious and has feelings', bucket: 0 },
          { label: 'AI understands exactly like a human', bucket: 0 },
          { label: 'AI never makes mistakes', bucket: 0 },
          { label: 'AI learns patterns from data', bucket: 1 },
          { label: 'AI can be biased', bucket: 1 },
          { label: 'AI makes useful predictions', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'AI isn’t conscious and doesn’t understand like we do.',
      'It does learn from data, can be biased, and is genuinely useful.',
      'Seeing AI clearly lets you use it wisely.',
    ],
    prerequisiteLessonIds: ['w1-l7'],
    nextLessonId: 'w2-l1',
  },
];

export const WORLD1_QUESTIONS: Question[] = [
  ...w1l1Q, ...w1l2Q, ...w1l3Q, ...w1l4Q,
  ...w1l5Q, ...w1l6Q, ...w1l7Q, ...w1l8Q,
];
