import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 2 — Machine Learning. Full lessons + question bank.
 * Structure, builder pattern and quality bar mirror world1.ts (the template).
 */

const W = 'world-machine-learning';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — What Is Machine Learning?
 * ================================================================== */
const l1 = bank('w2-l1', 'beginner');
const w2l1Q: Question[] = [
  l1.mc('bridge', 'In World 1 you saw two ways a computer decides. Machine learning is the one where…',
    ['The computer learns the pattern from examples instead of being told the rule',
     'A human writes every rule by hand',
     'The computer guesses randomly forever',
     'Nothing is learned at all'],
    0, 'Traditional software follows rules a human wrote. Machine learning flips that — it learns the rule from data.'),
  l1.mc('definition', 'What is machine learning, in one line?',
    ['Programs that improve at a task by learning patterns from data',
     'Any program stored on a large disk',
     'A robot that moves on wheels',
     'Software that only does arithmetic'],
    0, 'ML is about learning from examples to get better at a task — not about hardware or fixed formulas.'),
  l1.tf('vs-rules', 'In machine learning, the computer works out the rule itself from examples.', true,
    'That inversion — data in, rule out — is the heart of ML, and what separates it from hand-coded software.'),
  l1.mc('patterns', 'The “thing” a machine-learning model actually captures is…',
    ['A pattern that connects inputs to outputs',
     'A single fixed number',
     'A photograph of the programmer',
     'A list of every possible answer typed by hand'],
    0, 'A model learns a general pattern (input → output) so it can handle new inputs it was never shown.'),
  l1.mc('when-use', 'Machine learning is the right tool when…',
    ['The pattern is too complex or varied to write as exact rules',
     'The task is one fixed formula',
     'You have exactly one input, forever',
     'You never want the answer to change'],
    0, 'If you can neatly write the rule, just write it. ML earns its keep when the rule is fuzzy and hard to describe.'),
  l1.tf('subfield', 'Machine learning is a part of the wider field of AI.', true,
    'AI is the broad goal of intelligent behaviour; ML is one powerful approach to it — learning from data.'),
  l1.mc('example', 'Which of these is the clearest example of machine learning?',
    ['An email app that learns to catch spam from examples of junk mail',
     'A calculator adding two numbers',
     'A light switch turning on',
     'A stopwatch counting seconds'],
    0, 'The spam catcher improves from labelled examples. Learning from data is exactly the ML part.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Machine learning', right: 'Learning a pattern from examples' },
     { left: 'Model', right: 'The learned pattern the computer uses to predict' },
     { left: 'Data', right: 'The examples the model learns from' }],
    'ML is the approach, the model is the result of learning, and data is the raw material it learns from.'),
  l1.mc('model-word', 'When people say a “model”, they mean…',
    ['The learned pattern the computer uses to make predictions',
     'A fashion mannequin',
     'The computer’s screen',
     'A printed instruction manual'],
    0, 'A model is what training produces: a compact pattern that maps new inputs to sensible outputs.'),
  l1.tf('improve', 'A machine-learning system can get better as it sees more examples.', true,
    'More good examples usually sharpen the pattern the model has learned — up to a point.'),
  l1.mc('spot-pattern', 'A model sees: 2→4, 3→6, 4→8. What pattern did it likely learn?',
    ['Multiply the input by two',
     'Add one to the input',
     'Always output seven',
     'Subtract the input from ten'],
    0, 'From examples the model infers “times two”. Learning that hidden rule is what ML does.', 'predict-output'),
  l1.mc('not-magic', 'Saying ML “learns” really means…',
    ['It adjusts itself from data to make better predictions',
     'It becomes conscious',
     'It reads minds',
     'It works without any data'],
    0, 'Learning here is mechanical: tune the model from examples so its guesses improve. No magic, no awareness.'),
  l1.tf('needs-data', 'A machine-learning model can learn without any data.', false,
    'Data is the fuel. With no examples to learn from, there is no pattern to capture — and no model.'),
];

/* ================================================================== *
 * Lesson 2 — Supervised vs Unsupervised Learning
 * ================================================================== */
const l2 = bank('w2-l2', 'beginner');
const w2l2Q: Question[] = [
  l2.mc('supervised-def', 'What is supervised learning?',
    ['Learning from examples that already have the correct answers attached',
     'Learning with no examples at all',
     'Learning only at night',
     'Learning by copying one file'],
    0, 'Supervised = a teacher’s answer key. Each example comes with its correct answer, so the model learns the mapping.'),
  l2.mc('unsupervised-def', 'What is unsupervised learning?',
    ['Finding structure or groups in data that has no answers attached',
     'Learning from a full answer key',
     'Learning without any data',
     'Writing rules by hand'],
    0, 'Unsupervised = no answer key. The model discovers patterns or clusters on its own, with no labels to guide it.'),
  l2.tf('labels', 'Supervised learning needs examples with known correct answers.', true,
    'Those known answers (labels) are the “supervision”. Without them, it isn’t supervised learning.'),
  l2.mc('clustering', 'Grouping customers into similar segments, with no pre-set categories, is…',
    ['Unsupervised learning',
     'Supervised learning',
     'Hand-written rules',
     'Not learning at all'],
    0, 'No answer key exists — the model finds natural groupings itself. That’s the classic unsupervised task, clustering.'),
  l2.mc('spam-type', 'Training a filter on emails already marked “spam” or “not spam” is…',
    ['Supervised learning',
     'Unsupervised learning',
     'Random guessing',
     'A fixed formula'],
    0, 'Each email carries its correct label. The model learns to map email → label — textbook supervised learning.'),
  l2.match('sort', 'Match each task to its learning type.',
    [{ left: 'Predict tomorrow’s temperature from past data', right: 'Supervised' },
     { left: 'Group songs into moods with no labels', right: 'Unsupervised' },
     { left: 'Tell spam from real using labelled mail', right: 'Supervised' }],
    'If the examples come with answers, it’s supervised. If the model must find structure alone, it’s unsupervised.'),
  l2.tf('unsup-labels', 'Unsupervised learning uses examples that already have the right answers.', false,
    'The opposite: unsupervised learning has no answers. It finds patterns in unlabelled data.'),
  l2.mc('teacher', 'A helpful analogy for supervised learning is…',
    ['A student studying with an answer key',
     'A student with no book and no answers',
     'Rolling dice',
     'A locked door'],
    0, 'The label is the answer key. The model checks its guesses against known answers and improves — like guided study.'),
  l2.mc('no-teacher', 'A helpful analogy for unsupervised learning is…',
    ['Sorting a messy drawer into groups with no instructions',
     'Copying answers from a key',
     'Following a printed recipe exactly',
     'Reading a rulebook'],
    0, 'With no labels, the model must find its own groupings — like tidying a drawer into piles that “just go together”.'),
  l2.tf('both-useful', 'Both supervised and unsupervised learning are useful, just for different problems.', true,
    'Supervised shines when you have labels and want predictions; unsupervised helps you explore and find hidden structure.'),
  l2.mc('scenario-photos', 'You have thousands of unlabelled photos and want to auto-group similar ones. This is…',
    ['Unsupervised learning — grouping without predefined answers',
     'Supervised learning',
     'Hand-written rules',
     'Not possible with ML'],
    0, 'No labels exist, and the goal is to discover groups. That’s unsupervised clustering.', 'scenario'),
  l2.mc('label-cost', 'A practical reason unsupervised learning is attractive is…',
    ['Labelling data by hand is often slow and expensive',
     'It never needs any data',
     'It always beats supervised learning',
     'It requires no computer'],
    0, 'Unlabelled data is usually plentiful; labelling it is the costly part. Unsupervised methods skip that step.'),
  l2.tf('which-first', 'You should pick supervised vs unsupervised based on whether your data has labels.', true,
    'Have labels and a clear target? Supervised. Only raw, unlabelled data and want to explore it? Unsupervised.'),
];

/* ================================================================== *
 * Lesson 3 — Features and Labels
 * ================================================================== */
const l3 = bank('w2-l3', 'beginner');
const w2l3Q: Question[] = [
  l3.mc('feature-def', 'What is a “feature” in machine learning?',
    ['An input the model reads to make a prediction',
     'The answer the model outputs',
     'The colour of the app',
     'A type of computer chip'],
    0, 'Features are the inputs — the measurable facts about each example that the model reads.'),
  l3.mc('label-def', 'What is a “label”?',
    ['The correct answer the model is trying to predict',
     'An input fact about the example',
     'The name of the dataset file',
     'The speed of the computer'],
    0, 'The label is the target — the thing you want the model to output for each example.'),
  l3.tf('reads-predicts', 'The model reads the features and predicts the label.', true,
    'Features in, label out. Keeping that direction straight is the key to reading any dataset.'),
  l3.mc('house-features', 'To predict a house’s price, which of these is a feature?',
    ['The number of bedrooms',
     'The final sale price',
     'Nothing — houses have no features',
     'The buyer’s favourite colour, always'],
    0, 'Bedrooms, size and location are input features. The price is the label you’re predicting.'),
  l3.mc('house-label', 'For that same house-price task, the label is…',
    ['The sale price',
     'The number of bedrooms',
     'The floor area',
     'The postcode'],
    0, 'The label is what you predict — the price. The rest are features the model reads to get there.'),
  l3.match('sort', 'Match each item to what it is in a spam task.',
    [{ left: 'Words in the email', right: 'Feature' },
     { left: 'Has a suspicious link', right: 'Feature' },
     { left: '“Spam” or “Not spam”', right: 'Label' }],
    'Everything the model reads about the email is a feature; the spam/not-spam answer is the label.'),
  l3.tf('more-features', 'Adding relevant features can help a model make better predictions.', true,
    'Good, relevant features give the model more useful signal. Irrelevant ones just add noise.'),
  l3.mc('irrelevant', 'Which feature is LEAST useful for predicting house price?',
    ['The colour of the front door',
     'The floor area',
     'The location',
     'The number of bedrooms'],
    0, 'Door colour barely affects price. Great features carry real signal about the label; weak ones don’t.'),
  l3.mc('unsup-note', 'In unsupervised learning, examples usually have…',
    ['Features but no labels',
     'Labels but no features',
     'Neither features nor data',
     'A guaranteed correct answer'],
    0, 'Unsupervised data still has features to read — it just lacks labels, which is why the model must find structure itself.'),
  l3.tf('label-only-sup', 'Only supervised learning uses labels.', true,
    'Labels are the answer key. Supervised learning needs them; unsupervised works without them.'),
  l3.mc('table', 'In a data table, features are usually the… and the label is the…',
    ['Input columns … column you want to predict',
     'Answer column … input columns',
     'File name … folder',
     'Row count … column count'],
    0, 'Each row is an example; most columns are input features, and one special column is the label you predict.'),
  l3.mc('scenario-weather', 'To predict “will it rain tomorrow?”, humidity and cloud cover are…',
    ['Features the model reads',
     'The label being predicted',
     'Irrelevant to weather',
     'The name of the model'],
    0, 'Humidity and cloud cover are input features. The label is the rain/no-rain answer you want.', 'scenario'),
  l3.tf('good-features', 'Choosing good features is an important part of building a useful model.', true,
    'The right features hand the model the signal it needs. Poor features can cap how well any model can do.'),
];

/* ================================================================== *
 * Lesson 4 — Training vs Testing
 * ================================================================== */
const l4 = bank('w2-l4', 'beginner');
const w2l4Q: Question[] = [
  l4.mc('why-split', 'Why do we hold back some data as a test set?',
    ['To check the model on examples it never saw during training',
     'To make training slower',
     'To save disk space',
     'Because data expires'],
    0, 'The test set is unseen data — the only honest way to measure whether the model truly generalises.'),
  l4.mc('generalise', 'Generalisation means the model…',
    ['Performs well on new, unseen inputs',
     'Only repeats its training examples perfectly',
     'Runs on a bigger screen',
     'Uses less electricity'],
    0, 'The goal is real-world performance on data it hasn’t met. That’s generalisation — the point of the whole exercise.'),
  l4.tf('same-data', 'Testing a model on the exact data it trained on gives an honest score.', false,
    'It has already seen those answers, so it can look great yet fail on real data. You must test on unseen examples.'),
  l4.mc('cheating', 'Scoring a model on its training data is a bit like…',
    ['Giving a student the exam questions to study beforehand',
     'A surprise pop quiz',
     'Testing on a brand-new topic',
     'Not studying at all'],
    0, 'If a student memorises the exact exam, a top score proves nothing. Unseen tests reveal real understanding.'),
  l4.tf('unseen-honest', 'A test set works because it contains examples the model has never seen.', true,
    'Unseen data is the fair exam. It shows whether the model learned the pattern or just memorised the answers.'),
  l4.mc('typical-split', 'A common way to split data is…',
    ['Most for training, a smaller portion held out for testing',
     'All of it for testing, none for training',
     'One example for training, the rest ignored',
     'Split it by file colour'],
    0, 'You train on the bulk of the data and keep a slice aside, untouched, to test honestly at the end.'),
  l4.match('sort', 'Match each set to its job.',
    [{ left: 'Training set', right: 'Data the model learns from' },
     { left: 'Test set', right: 'Unseen data to measure real performance' },
     { left: 'Generalisation', right: 'Doing well on new inputs' }],
    'Learn from the training set, judge on the test set, and generalisation is the quality you’re measuring.'),
  l4.mc('good-train-bad-test', 'A model scores great on training but poorly on the test set. This means…',
    ['It likely memorised instead of learning the general pattern',
     'The test set is broken',
     'The model is perfect',
     'Training data is unnecessary'],
    0, 'A big gap between training and test scores is the classic warning sign of memorising, not generalising.', 'scenario'),
  l4.tf('leak', 'Letting test examples sneak into training makes the test score misleading.', true,
    'If the model has secretly seen the test data, the score is inflated — a common, costly mistake called leakage.'),
  l4.mc('purpose', 'The real purpose of testing is to…',
    ['Estimate how the model will do on future real-world data',
     'Make the model bigger',
     'Delete the training data',
     'Change the app’s colour'],
    0, 'The test score is your best honest guess at real-world performance before you rely on the model.'),
  l4.mc('never-touch', 'Best practice with the test set is to…',
    ['Keep it untouched until the very end, then evaluate once',
     'Train on it repeatedly',
     'Peek at it during every training round',
     'Throw it away before training'],
    0, 'The moment you tune to the test set, it stops being unseen. Guard it, and use it for a final, honest check.'),
  l4.tf('goal', 'Splitting data helps us trust that a good score reflects real ability.', true,
    'A separate test set is what turns “looks good on paper” into “will probably work in the real world”.'),
];

/* ================================================================== *
 * Lesson 5 — Classification: Predicting a Category
 * ================================================================== */
const l5 = bank('w2-l5', 'intermediate');
const w2l5Q: Question[] = [
  l5.mc('def', 'What is classification?',
    ['Predicting which category an input belongs to',
     'Predicting an exact number',
     'Sorting files alphabetically by hand',
     'Deleting old data'],
    0, 'Classification answers “which class?” — spam or not, cat or dog, approve or deny. The output is a category.'),
  l5.mc('example', 'Which of these is a classification task?',
    ['Deciding if an email is spam or not spam',
     'Predicting a house’s exact price in dollars',
     'Measuring today’s temperature',
     'Counting words in a document'],
    0, 'Spam-or-not is a category choice — classification. Predicting an exact price is regression, a different task.'),
  l5.tf('categories', 'The output of a classifier is a category, not a precise number.', true,
    'Classifiers pick from a set of classes. If you need a continuous number instead, that’s regression.'),
  l5.mc('threshold', 'Many classifiers output a probability, then apply a threshold to…',
    ['Turn that probability into a yes/no decision',
     'Make the model run faster',
     'Delete uncertain examples',
     'Change the input features'],
    0, 'A model might say “0.8 spam”. A threshold (say 0.5) converts that score into a firm decision: spam or not.'),
  l5.mc('binary', 'A classifier with exactly two classes is called…',
    ['A binary classifier',
     'A number predictor',
     'An unsupervised model',
     'A clustering model'],
    0, 'Two classes (yes/no, spam/not) is binary classification — the most common and simplest case.'),
  l5.match('sort', 'Match each output to its task type.',
    [{ left: '“Cat” or “Dog”', right: 'Classification' },
     { left: 'Tomorrow’s temperature in °C', right: 'Regression' },
     { left: '“Approve” or “Deny”', right: 'Classification' }],
    'Categories → classification. A precise number → regression. The output type tells you the task.'),
  l5.tf('threshold-move', 'Raising the decision threshold makes a classifier more cautious about saying “yes”.', true,
    'A higher bar means the model only says “yes” when very confident — fewer false alarms, but it may miss some real cases.'),
  l5.mc('precision-recall', 'Lowering the threshold so the model says “yes” more often tends to…',
    ['Catch more true cases, but also raise false alarms',
     'Catch fewer of everything',
     'Have no effect on results',
     'Make the model unsupervised'],
    0, 'A lower bar catches more real positives (higher recall) but flags more wrongly too — the classic trade-off.'),
  l5.mc('scenario-medical', 'For a disease screen where missing a case is dangerous, you’d likely…',
    ['Lower the threshold to catch more possible cases, accepting extra false alarms',
     'Raise the threshold to say “yes” as rarely as possible',
     'Remove the threshold and never decide',
     'Ignore the probabilities entirely'],
    0, 'When a miss is costly, you tune the threshold to catch more cases — a follow-up test can rule out false alarms.', 'scenario'),
  l5.tf('multi', 'Classification can have more than two categories.', true,
    'Sorting a photo into “cat”, “dog” or “bird” is multi-class classification — same idea, more than two options.'),
  l5.mc('predict-out', 'A spam model outputs 0.9 for an email, with a threshold of 0.5. The decision is…',
    ['Spam',
     'Not spam',
     'Undecided forever',
     'Delete the email'],
    0, '0.9 is above the 0.5 threshold, so the email is classified as spam. The threshold turns the score into a decision.', 'predict-output'),
  l5.mc('vs-regression', 'The key difference between classification and regression is…',
    ['Classification predicts a category; regression predicts a number',
     'Classification is unsupervised; regression is supervised',
     'Classification needs no data',
     'They are exactly the same task'],
    0, 'Both are supervised. The difference is the output: a discrete category versus a continuous number.'),
  l5.tf('threshold-tradeoff', 'There is one perfect threshold that is best for every situation.', false,
    'The best threshold depends on the costs of each mistake. A cancer screen and a spam filter tune it very differently.'),
];

/* ================================================================== *
 * Lesson 6 — Regression: Predicting a Number
 * ================================================================== */
const l6 = bank('w2-l6', 'intermediate');
const w2l6Q: Question[] = [
  l6.mc('def', 'What is regression?',
    ['Predicting a continuous number',
     'Predicting a category label',
     'Grouping data with no labels',
     'Deleting old records'],
    0, 'Regression answers “how much?” — a price, a temperature, a duration. The output is a number, not a category.'),
  l6.mc('example', 'Which of these is a regression task?',
    ['Predicting a house’s price in dollars',
     'Deciding if an email is spam',
     'Sorting photos into “cat” or “dog”',
     'Choosing “approve” or “deny”'],
    0, 'A dollar amount is a continuous number — regression. The others pick a category, which is classification.'),
  l6.tf('number', 'The output of a regression model is a number, not a category.', true,
    'Regression predicts continuous values. If the answer is a class instead, that’s classification.'),
  l6.match('sort', 'Match each task to its type.',
    [{ left: 'Predict a car’s fuel cost per month', right: 'Regression' },
     { left: 'Predict if a review is positive or negative', right: 'Classification' },
     { left: 'Predict how many minutes a trip takes', right: 'Regression' }],
    'A number to predict → regression. A category to pick → classification. Look at the output.'),
  l6.mc('error', 'A regression model’s error is usually measured as…',
    ['How far its predicted number is from the true number',
     'Whether it picked the right category',
     'The colour of the chart',
     'How fast it runs'],
    0, 'Regression cares about distance: a prediction of 95 when the truth is 100 is close; 40 is far off.'),
  l6.tf('classification-diff', 'Regression and classification are both supervised, differing mainly in output type.', true,
    'Both learn from labelled examples. Regression outputs a number; classification outputs a category.'),
  l6.mc('scenario-delivery', 'An app predicts your food will arrive “in 27 minutes”. That model is doing…',
    ['Regression — predicting a number',
     'Classification — predicting a category',
     'Clustering',
     'Nothing to do with ML'],
    0, '“27 minutes” is a continuous number, so it’s a regression prediction.', 'scenario'),
  l6.mc('close-counts', 'In regression, a prediction of 98 when the truth is 100 is…',
    ['A small error — close is good',
     'Completely wrong — only exact counts',
     'Impossible',
     'A category mistake'],
    0, 'Unlike categories, closeness matters. Being near the true value is a good regression prediction.'),
  l6.tf('exact', 'A regression model must hit the exact true value to be useful.', false,
    'Being close is usually enough. Regression is judged by how small the errors are, not by exact hits.'),
  l6.mc('features-still', 'To predict rent (a number) from size and location, size and location are…',
    ['Features the model reads',
     'The label being predicted',
     'Irrelevant noise',
     'The model’s name'],
    0, 'Features and labels apply here too: size and location are inputs; the rent amount is the numeric label.'),
  l6.mc('which-task', 'You want to predict a student’s exam score out of 100. This is best framed as…',
    ['Regression — the score is a number',
     'Classification — pass or fail',
     'Clustering',
     'Unsupervised learning'],
    0, 'Predicting a numeric score is regression. (If you only cared about pass/fail, that would be classification.)'),
  l6.tf('goal', 'Choosing regression vs classification depends on whether you need a number or a category.', true,
    'Ask what the answer looks like. A number means regression; a category means classification.'),
];

/* ================================================================== *
 * Lesson 7 — Overfitting vs Underfitting
 * ================================================================== */
const l7 = bank('w2-l7', 'intermediate');
const w2l7Q: Question[] = [
  l7.mc('overfit-def', 'What is overfitting?',
    ['The model memorises the training data and fails on new data',
     'The model is too simple to learn anything',
     'The model runs too slowly',
     'The model has no data'],
    0, 'An overfit model clings to every quirk of the training set, so it aces training but stumbles on unseen data.'),
  l7.mc('underfit-def', 'What is underfitting?',
    ['The model is too simple to capture the real pattern',
     'The model memorises every detail',
     'The model is exactly right',
     'The model has too much data'],
    0, 'An underfit model is too simple — it misses the real pattern and does poorly on both training and test data.'),
  l7.tf('overfit-signs', 'Overfitting shows up as great training scores but poor test scores.', true,
    'That gap is the signature of overfitting: the model learned the noise, not the general pattern.'),
  l7.mc('underfit-signs', 'Underfitting typically shows up as…',
    ['Poor scores on BOTH training and test data',
     'Perfect scores everywhere',
     'Great training, poor test',
     'No effect at all'],
    0, 'If the model is too simple, it can’t even fit the training data well — both scores stay low.'),
  l7.mc('complexity', 'As model complexity increases from very low, performance usually…',
    ['Improves at first, then test performance worsens as it starts overfitting',
     'Only ever gets worse',
     'Stays exactly flat',
     'Instantly becomes perfect'],
    0, 'There’s a sweet spot: too simple underfits, too complex overfits. The best model sits in between.'),
  l7.match('sort', 'Match each symptom to its cause.',
    [{ left: 'Great on training, poor on test', right: 'Overfitting' },
     { left: 'Poor on both training and test', right: 'Underfitting' },
     { left: 'Good on both', right: 'A well-fit model' }],
    'The pattern of scores tells the story: memorising noise, missing the pattern, or getting it just right.'),
  l7.tf('memorise', 'Overfitting is a bit like memorising exam answers instead of understanding the subject.', true,
    'Memorised answers fail on new questions. An overfit model fails on new data for the very same reason.'),
  l7.mc('fix-overfit', 'A sensible way to reduce overfitting is…',
    ['Use more training data or a simpler model',
     'Memorise even harder',
     'Delete the test set',
     'Turn up the brightness'],
    0, 'More representative data and reining in complexity both push the model back toward the general pattern.'),
  l7.mc('fix-underfit', 'A sensible way to reduce underfitting is…',
    ['Use a more capable model or better features',
     'Make the model even simpler',
     'Remove all the data',
     'Shrink the screen'],
    0, 'If the model is too simple to catch the pattern, give it more capacity or richer features so it can learn more.'),
  l7.tf('sweet-spot', 'The best model balances complexity — not too simple, not too complex.', true,
    'That balance is the goal: complex enough to learn the pattern, simple enough to generalise to new data.'),
  l7.mc('scenario', 'A model gets 99% on training but 60% on the test set. The likely problem is…',
    ['Overfitting',
     'Underfitting',
     'The model is perfect',
     'Too little complexity'],
    0, 'A large train-minus-test gap points straight at overfitting — the model memorised rather than generalised.', 'scenario'),
  l7.mc('both-low', 'A model scores 55% on training AND 54% on test. The likely problem is…',
    ['Underfitting — the model is too simple',
     'Overfitting',
     'Data leakage',
     'A perfect fit'],
    0, 'Low scores on both, close together, mean the model never captured the pattern — that’s underfitting.', 'predict-output'),
];

/* ================================================================== *
 * Lesson 8 — The Machine-Learning Workflow
 * ================================================================== */
const l8 = bank('w2-l8', 'advanced');
const w2l8Q: Question[] = [
  l8.mc('first-step', 'What comes first in a machine-learning project?',
    ['Collecting relevant data for the problem',
     'Deploying the model',
     'Monitoring the model',
     'Deleting the data'],
    0, 'It all starts with data. Without relevant examples, there is nothing for the model to learn from.'),
  l8.order('workflow', 'Put the ML workflow in the right order.',
    ['Collect data', 'Prepare and clean the data', 'Train the model', 'Evaluate on unseen data', 'Deploy the model', 'Monitor in the real world'],
    'Collect → prepare → train → evaluate → deploy → monitor. Each stage feeds the next; monitoring can loop you back.'),
  l8.mc('prepare', 'Why is preparing and cleaning data important?',
    ['Messy or wrong data teaches the model bad patterns',
     'It makes the screen brighter',
     'It deletes the need for training',
     'Clean data is just for looks'],
    0, 'Garbage in, garbage out. Cleaning and organising data before training directly shapes how good the model can be.'),
  l8.tf('evaluate-unseen', 'Evaluation should use data the model did not train on.', true,
    'Only unseen data gives an honest measure — the same lesson as training vs testing, now a workflow stage.'),
  l8.mc('deploy', 'What does “deploying” a model mean?',
    ['Putting it to work making predictions in the real product',
     'Throwing the model away',
     'Collecting more data',
     'Cleaning the training set'],
    0, 'Deployment is where the model starts doing its real job — serving predictions to actual users.'),
  l8.mc('monitor', 'Why monitor a model after deployment?',
    ['The real world changes, and performance can drift over time',
     'Models never change once deployed',
     'To make it run slower',
     'Monitoring is only decorative'],
    0, 'Data shifts, behaviour drifts. Monitoring catches drops in performance so you can retrain before it hurts users.'),
  l8.match('sort', 'Match each workflow stage to what happens in it.',
    [{ left: 'Prepare', right: 'Clean and organise the data' },
     { left: 'Train', right: 'Let the model learn the pattern' },
     { left: 'Evaluate', right: 'Measure it on unseen data' }],
    'Each stage has a clear job; getting them in the right order is what makes an ML project work.'),
  l8.tf('iterative', 'The ML workflow is often a loop, not a one-time straight line.', true,
    'Monitoring often reveals problems that send you back to collect fresh data and retrain — the loop keeps models healthy.'),
  l8.mc('drift-scenario', 'A deployed model that was accurate slowly gets worse over months. This is likely…',
    ['Drift — the real-world data has changed since training',
     'The model getting bored',
     'A broken screen',
     'Proof monitoring is pointless'],
    0, 'As the world shifts, yesterday’s pattern fits less well. Monitoring spots this drift so you can retrain.', 'scenario'),
  l8.mc('most-time', 'In practice, which stage often takes the MOST effort?',
    ['Collecting, cleaning and preparing the data',
     'Pressing the deploy button',
     'Naming the model',
     'Choosing an app colour'],
    0, 'Data work is famously the largest chunk of real ML projects — good data is hard-won, and it decides everything.'),
  l8.order('recover', 'Monitoring flags a drop in accuracy. Put the recovery steps in order.',
    ['Notice the accuracy drop while monitoring', 'Collect fresh, up-to-date data', 'Retrain the model on it', 'Evaluate the new model', 'Redeploy the improved model'],
    'Monitoring closes the loop: spot the problem, gather new data, retrain, re-check, and ship the improved model.'),
  l8.tf('workflow-goal', 'Following a clear workflow makes ML projects more reliable and repeatable.', true,
    'A disciplined pipeline — collect, prepare, train, evaluate, deploy, monitor — is what turns a demo into a dependable product.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD2_LESSONS: Lesson[] = [
  {
    id: 'w2-l1', worldId: W, order: 1,
    title: 'What Is Machine Learning?',
    subtitle: 'From written rules to learned patterns',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'World 1 showed that computers decide by rules or by learning. This world is all about the second path: machine learning.',
    realWorld: 'Nobody wrote a rule for every way a face can look. Your phone learned the pattern from examples — that’s machine learning at work.',
    objectives: [
      'Define machine learning in one clear sentence',
      'Explain how ML differs from hand-written rules',
      'Spot when learning from data is the right tool',
    ],
    activity: {
      kind: 'sequence',
      title: 'Spot the Learned Pattern',
      instructions: 'The model has learned a hidden rule from these examples. What comes next?',
      config: {
        shown: ['2 → 4', '3 → 6', '4 → 8', '5 → ?'],
        options: ['10', '9', '7', '25'],
        correctIndex: 0,
        reveal: 'The examples all follow “multiply by two”. The model infers that pattern from data — no rule was written by hand.',
      },
    },
    keyTakeaways: [
      'Machine learning = learning a pattern from examples, not being told the rule.',
      'Use it when the pattern is too complex to write down.',
      'ML is one powerful approach inside the wider field of AI.',
    ],
    prerequisiteLessonIds: ['w1-l8'],
    nextLessonId: 'w2-l2',
  },
  {
    id: 'w2-l2', worldId: W, order: 2,
    title: 'Supervised vs Unsupervised Learning',
    subtitle: 'Learning with, or without, an answer key',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 55, coins: 6,
    description: 'The two big families of machine learning split on one question: does your data come with the right answers, or not?',
    realWorld: 'Studying with an answer key is supervised. Tidying a messy drawer into piles that “just go together”, with no instructions, is unsupervised.',
    objectives: [
      'Define supervised and unsupervised learning',
      'Match a task to the right learning type',
      'Explain why labels matter (and cost effort)',
    ],
    activity: {
      kind: 'bucket',
      title: 'Supervised or Unsupervised?',
      instructions: 'Sort each task by whether the data comes with answers (labels) or not.',
      config: {
        buckets: ['Supervised (has labels)', 'Unsupervised (no labels)'],
        items: [
          { label: 'Spam / not-spam from labelled mail', bucket: 0 },
          { label: 'Predict price from past sales', bucket: 0 },
          { label: 'Diagnose from labelled scans', bucket: 0 },
          { label: 'Group similar customers, no categories', bucket: 1 },
          { label: 'Cluster songs into moods', bucket: 1 },
          { label: 'Find hidden groups in raw data', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Supervised learning uses examples with known answers (labels).',
      'Unsupervised learning finds structure in unlabelled data.',
      'Whether your data has labels decides which family you’re in.',
    ],
    prerequisiteLessonIds: ['w2-l1'],
    nextLessonId: 'w2-l3',
  },
  {
    id: 'w2-l3', worldId: W, order: 3,
    title: 'Features and Labels',
    subtitle: 'What the model reads, what it predicts',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 60, coins: 7,
    description: 'Every supervised example has two parts: the features it reads and the label it predicts. Keep them straight and datasets stop being scary.',
    realWorld: 'To guess a house’s price, you look at its size, rooms and location (the features) to estimate the price (the label). The model does the same.',
    objectives: [
      'Define features and labels',
      'Identify features vs labels in a real task',
      'Explain why good features matter',
    ],
    activity: {
      kind: 'bucket',
      title: 'Feature or Label?',
      instructions: 'For predicting a house’s price, sort each item into feature (an input) or label (the answer).',
      config: {
        buckets: ['Feature (input)', 'Label (answer)'],
        items: [
          { label: 'Number of bedrooms', bucket: 0 },
          { label: 'Floor area', bucket: 0 },
          { label: 'Location', bucket: 0 },
          { label: 'Age of the house', bucket: 0 },
          { label: 'The sale price', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Features are the inputs the model reads.',
      'The label is the answer the model predicts.',
      'Relevant features give the model the signal it needs.',
    ],
    prerequisiteLessonIds: ['w2-l2'],
    nextLessonId: 'w2-l4',
  },
  {
    id: 'w2-l4', worldId: W, order: 4,
    title: 'Training vs Testing',
    subtitle: 'Why we hold data back',
    difficulty: 'beginner', estimatedMinutes: 7, xp: 65, coins: 8,
    description: 'A model that only repeats what it memorised hasn’t really learned. We hold out unseen data to check it can handle the real world.',
    realWorld: 'Give a student the exam answers to memorise and their top score means nothing. A fair test uses questions they haven’t seen.',
    objectives: [
      'Explain why we split data into train and test sets',
      'Define generalisation',
      'Recognise the warning sign of memorising',
    ],
    activity: {
      kind: 'slider',
      title: 'Train vs Test Score',
      instructions: 'Slide from memorising toward true learning, and watch the honest test score behave.',
      config: {
        min: 0, max: 100, step: 10, valueLabel: 'How much the model generalises (vs memorises)',
        stops: [
          { upTo: 20, title: 'Pure memorising', detail: 'Perfect on training, poor on the test set — it just parroted the answers.' },
          { upTo: 50, title: 'Mostly memorising', detail: 'Still a big gap between training and test — it hasn’t grasped the pattern.' },
          { upTo: 80, title: 'Learning the pattern', detail: 'Training and test scores move closer — real generalisation is kicking in.' },
          { upTo: 100, title: 'Generalising well', detail: 'Strong on unseen data too — this is the model you can actually trust.' },
        ],
      },
    },
    keyTakeaways: [
      'Test on unseen data — never on the exact training examples.',
      'Generalisation = doing well on new, real inputs.',
      'A big train-vs-test gap means memorising, not learning.',
    ],
    prerequisiteLessonIds: ['w2-l3'],
    nextLessonId: 'w2-l5',
  },
  {
    id: 'w2-l5', worldId: W, order: 5,
    title: 'Classification: Predicting a Category',
    subtitle: 'Which class does this belong to?',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Classification answers “which category?” — spam or not, cat or dog. Often the model gives a probability, and a threshold turns it into a decision.',
    realWorld: 'A smoke alarm sets a threshold: enough smoke and it decides “fire!”. Set it too twitchy and it cries wolf; too dull and it misses real danger.',
    objectives: [
      'Define classification and give examples',
      'Explain how a threshold turns a score into a decision',
      'Reason about the precision–recall trade-off',
    ],
    activity: {
      kind: 'slider',
      title: 'Move the Decision Threshold',
      instructions: 'Slide the threshold for a spam filter and watch the trade-off between missing spam and flagging good mail.',
      config: {
        min: 0, max: 100, step: 10, valueLabel: 'Decision threshold (how sure before it says “spam”)',
        stops: [
          { upTo: 20, title: 'Very low threshold', detail: 'Catches almost all spam, but wrongly flags many real emails too.' },
          { upTo: 50, title: 'Low–medium', detail: 'Catches most spam; still some good mail lands in the spam folder.' },
          { upTo: 80, title: 'Medium–high', detail: 'Real mail is rarely flagged, but a little spam now slips through.' },
          { upTo: 100, title: 'Very high threshold', detail: 'Almost never flags good mail — but lets plenty of spam reach your inbox.' },
        ],
      },
    },
    keyTakeaways: [
      'Classification predicts a category, not a number.',
      'A threshold turns a probability into a firm yes/no.',
      'Lowering the threshold catches more, but raises false alarms.',
    ],
    prerequisiteLessonIds: ['w2-l4'],
    nextLessonId: 'w2-l6',
  },
  {
    id: 'w2-l6', worldId: W, order: 6,
    title: 'Regression: Predicting a Number',
    subtitle: 'How much, not which',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 75, coins: 11,
    description: 'When the answer is a number — a price, a temperature, a delivery time — the task is regression, and being close counts.',
    realWorld: 'Guessing a food delivery will take “about 27 minutes” is regression: a number, where near-enough is good and being wildly off is bad.',
    objectives: [
      'Define regression and give examples',
      'Tell regression apart from classification',
      'Explain why closeness matters for regression',
    ],
    activity: {
      kind: 'bucket',
      title: 'Number or Category?',
      instructions: 'Sort each task into regression (predict a number) or classification (predict a category).',
      config: {
        buckets: ['Regression (a number)', 'Classification (a category)'],
        items: [
          { label: 'Predict a house price in dollars', bucket: 0 },
          { label: 'Predict a trip’s minutes', bucket: 0 },
          { label: 'Predict tomorrow’s temperature', bucket: 0 },
          { label: 'Email: spam or not spam', bucket: 1 },
          { label: 'Photo: cat or dog', bucket: 1 },
          { label: 'Review: positive or negative', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Regression predicts a continuous number.',
      'It’s judged by how close the prediction is to the truth.',
      'Number to predict → regression; category → classification.',
    ],
    prerequisiteLessonIds: ['w2-l5'],
    nextLessonId: 'w2-l7',
  },
  {
    id: 'w2-l7', worldId: W, order: 7,
    title: 'Overfitting vs Underfitting',
    subtitle: 'The complexity balancing act',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 75, coins: 11,
    description: 'Too simple and a model misses the pattern; too complex and it memorises noise. The best model lives in the balanced middle.',
    realWorld: 'A student who only memorises past exams (overfit) flunks new questions; one who barely studies (underfit) flunks everything. Real understanding sits between.',
    objectives: [
      'Define overfitting and underfitting',
      'Read train-vs-test scores to diagnose each',
      'Find the balanced sweet spot of complexity',
    ],
    activity: {
      kind: 'slider',
      title: 'Model Complexity Dial',
      instructions: 'Turn up model complexity and watch training and test accuracy split apart.',
      config: {
        min: 0, max: 100, step: 10, valueLabel: 'Model complexity',
        stops: [
          { upTo: 25, title: 'Too simple (underfitting)', detail: 'Both training and test scores are low — the model misses the real pattern.' },
          { upTo: 55, title: 'Getting there', detail: 'Both scores climb together as the model starts capturing the pattern.' },
          { upTo: 75, title: 'The sweet spot', detail: 'Training and test scores are both high and close — this is the model to keep.' },
          { upTo: 100, title: 'Too complex (overfitting)', detail: 'Training score soars but test score drops — it’s memorising noise, not learning.' },
        ],
      },
    },
    keyTakeaways: [
      'Overfitting: great on training, poor on test — memorised the noise.',
      'Underfitting: poor on both — too simple to learn the pattern.',
      'Aim for balanced complexity: high, close train and test scores.',
    ],
    prerequisiteLessonIds: ['w2-l6'],
    nextLessonId: 'w2-l8',
  },
  {
    id: 'w2-l8', worldId: W, order: 8,
    title: 'The Machine-Learning Workflow',
    subtitle: 'From raw data to a running model',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'A real ML project is a pipeline: collect, prepare, train, evaluate, deploy, monitor. And it loops — monitoring sends you back to improve.',
    realWorld: 'Like running a kitchen: source ingredients, prep them, cook, taste-test, serve, then watch reviews and adjust. Skip a step and quality slips.',
    objectives: [
      'Order the stages of the ML workflow',
      'Explain the purpose of each stage',
      'Describe why the workflow is a loop',
    ],
    activity: {
      kind: 'steps',
      title: 'Build the ML Workflow',
      instructions: 'Drag the stages into the order a real machine-learning project runs.',
      config: {
        steps: [
          'Collect data',
          'Prepare and clean the data',
          'Train the model',
          'Evaluate on unseen data',
          'Deploy the model',
          'Monitor in the real world',
        ],
      },
    },
    keyTakeaways: [
      'The workflow: collect → prepare → train → evaluate → deploy → monitor.',
      'Data work often takes the most effort and shapes everything.',
      'It’s a loop — monitoring sends you back to collect and retrain.',
    ],
    prerequisiteLessonIds: ['w2-l7'],
    nextLessonId: null,
  },
];

export const WORLD2_QUESTIONS: Question[] = [
  ...w2l1Q, ...w2l2Q, ...w2l3Q, ...w2l4Q,
  ...w2l5Q, ...w2l6Q, ...w2l7Q, ...w2l8Q,
];
