import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 9 — AI Agents. Full lessons + question bank.
 * Structure and style mirror world1.ts exactly.
 */

const W = 'world-agents';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — From Chatbots to Agents
 * ================================================================== */
const l1 = bank('w9-l1', 'intermediate');
const w9l1Q: Question[] = [
  l1.mc('definition', 'What best describes an AI agent?',
    ['AI that takes actions to reach a goal, not just answers a question',
     'A chatbot that only replies with text',
     'A search box on a website',
     'A faster version of a calculator'],
    0, 'A chatbot answers. An agent goes further — it decides on and performs steps to actually accomplish a goal.'),
  l1.tf('vs-chatbot', 'A plain chatbot can send an email, book a flight and update a file on its own.', false,
    'A plain chatbot only produces a reply. Taking real actions in the world is what makes something an agent.'),
  l1.mc('key-shift', 'The main shift from chatbot to agent is…',
    ['From answering to acting toward a goal',
     'From English to another language',
     'From slow to fast responses',
     'From text to pictures'],
    0, 'The defining leap is agency: the AI can choose and carry out actions, not merely describe them.'),
  l1.match('roles', 'Match each system to what it mainly does.',
    [{ left: 'Chatbot', right: 'Answers your question' },
     { left: 'Agent', right: 'Takes steps to finish a goal' },
     { left: 'Tool', right: 'A single action the agent can use' }],
    'A chatbot responds, an agent pursues a goal, and tools are the individual actions an agent reaches for.'),
  l1.mc('goal-driven', 'What does “goal-driven” mean for an agent?',
    ['It works toward an outcome, taking whatever steps are needed',
     'It always uses the fewest words',
     'It only runs once per day',
     'It ignores what the user wants'],
    0, 'Give an agent a goal — “plan my trip” — and it figures out and performs the steps to get there.'),
  l1.tf('still-llm', 'Most agents are still built around a language model at their core.', true,
    'The model is the “brain” that decides what to do; the agent adds the ability to act on those decisions.'),
  l1.mc('example', 'Which of these is the clearest example of an AGENT?',
    ['An assistant that searches flights, compares them and books one for you',
     'A model that defines the word “flight”',
     'A page that lists airline names',
     'A translator that turns “flight” into French'],
    0, 'Searching, comparing and then booking are actions toward a goal — that is agent behaviour, not just answering.'),
  l1.mc('scenario-assistant', 'You ask an AI to “clear my inbox of spam.” It reads emails, marks junk and deletes it. This is…',
    ['An agent — it took actions to complete the goal',
     'A chatbot — it only wrote a reply',
     'Not AI at all',
     'A calculator'],
    0, 'It didn’t just describe what to do; it actually did it. Acting to reach the goal makes it an agent.', 'scenario'),
  l1.tf('autonomy', 'Agents can carry out several steps without asking you to approve each one.', true,
    'A degree of autonomy is the point — but that same power is why guardrails (later) matter so much.'),
  l1.mc('why-now', 'Why are agents useful beyond a normal chatbot?',
    ['They can complete multi-step tasks in the real world, not just talk about them',
     'They use brighter colours',
     'They never need a model',
     'They only work offline'],
    0, 'Real value comes from getting things done — booking, editing, fetching — across several steps.'),
  l1.match('capabilities', 'Match the capability to who has it.',
    [{ left: 'Give a text answer', right: 'Both chatbot and agent' },
     { left: 'Use a tool to act', right: 'Agent' },
     { left: 'Chain several steps to a goal', right: 'Agent' }],
    'Answering is shared, but using tools and chaining steps toward a goal are what set agents apart.'),
  l1.mc('misconception', 'Which statement about agents is TRUE?',
    ['An agent decides and acts, but can still make mistakes',
     'An agent is always correct',
     'An agent needs no goal',
     'An agent never uses a language model'],
    0, 'Agents are powerful but fallible — they can pick wrong actions, which is why oversight matters.'),
];

/* ================================================================== *
 * Lesson 2 — Tool Calling: Giving AI Hands
 * ================================================================== */
const l2 = bank('w9-l2', 'intermediate');
const w9l2Q: Question[] = [
  l2.mc('what-is-tool', 'In agent terms, a “tool” is…',
    ['An external function the model can call to do something, like search or calculate',
     'A physical screwdriver',
     'A brighter screen',
     'Another word for the model itself'],
    0, 'Tools are actions wired up for the model: web search, a calculator, an API, sending an email — its “hands”.'),
  l2.tf('why-tools', 'Tools let a model do things it can’t do from words alone, like fetch live data.', true,
    'A model’s own knowledge is frozen and can’t act. Tools give it fresh data and the ability to affect the world.'),
  l2.mc('calculator', 'Why give a language model a calculator tool?',
    ['Models are unreliable at exact arithmetic, so a real calculator is more accurate',
     'Calculators make the model talk faster',
     'It changes the model’s colour',
     'Models cannot read numbers at all'],
    0, 'Rather than guess a sum, the model calls a calculator and gets the exact answer — offloading what it’s weak at.'),
  l2.match('tools', 'Match each tool to what it’s for.',
    [{ left: 'Web search', right: 'Find up-to-date information' },
     { left: 'Calculator', right: 'Do exact arithmetic' },
     { left: 'Email API', right: 'Send a message' }],
    'Each tool covers a specific job the model can’t do well or at all on its own.'),
  l2.mc('how-call', 'How does a model typically “call” a tool?',
    ['It outputs a structured request naming the tool and its inputs',
     'It physically presses a button',
     'It emails a human to do it',
     'It cannot request tools'],
    0, 'The model emits a structured call — tool name plus arguments — which the system runs, returning the result.'),
  l2.tf('result-back', 'After a tool runs, its result is fed back to the model to use.', true,
    'The loop is: model asks for a tool, the tool runs, the result returns, and the model continues with that new info.'),
  l2.mc('fresh-data', 'A user asks today’s weather. The best move for an agent is to…',
    ['Call a weather tool for live data instead of guessing',
     'Make up a temperature',
     'Refuse to answer anything',
     'Report last year’s weather from memory'],
    0, 'Live facts change. A tool fetches current data; relying on the model’s frozen memory would be wrong.', 'scenario'),
  l2.tf('any-action', 'Tools can include actions that change the world, like posting or deleting.', true,
    'Tools aren’t only for reading. Because some can act destructively, they must be granted carefully.'),
  l2.mc('function-calling', 'Another common name for tool calling is…',
    ['Function calling',
     'Screen dimming',
     'Data mining',
     'Cloud storage'],
    0, 'The model “calls a function” with arguments — hence “function calling”, the same idea as tool use.'),
  l2.mc('choose-tool', 'How does an agent decide WHICH tool to use?',
    ['The model reasons about the goal and picks the tool that fits',
     'It always uses the first tool alphabetically',
     'It picks at random every time',
     'A human names the tool for every step'],
    0, 'Given the goal and available tools, the model reasons about which one moves it closer, then calls it.'),
  l2.tf('limits', 'An agent can only use the specific tools it has been given access to.', true,
    'Tools are explicitly provided. Limiting the toolset is a key way to keep an agent safe and predictable.'),
  l2.mc('why-hands', 'Calling tools “giving AI hands” means…',
    ['Tools let the model act on the world, not just talk about it',
     'The model grows a physical body',
     'Tools make the model sleepy',
     'It’s only a figure of speech with no real effect'],
    0, 'Words are the model’s voice; tools are its hands — the means to actually do things.'),
];

/* ================================================================== *
 * Lesson 3 — The Agent Loop: Plan, Act, Observe
 * ================================================================== */
const l3 = bank('w9-l3', 'intermediate');
const w9l3Q: Question[] = [
  l3.mc('loop-core', 'The agent loop is best described as…',
    ['Plan a step, act, observe the result, then decide what to do next — repeat',
     'Answer once and stop',
     'Wait for the user to type each command',
     'Randomly pick outputs forever'],
    0, 'Agents cycle: reason about the next step, take it, look at the result, and use it to choose the next move.'),
  l3.order('cycle', 'Put one turn of the agent loop in order.',
    ['Plan the next step toward the goal', 'Act — use a tool or take an action', 'Observe the result that comes back', 'Decide whether the goal is done', 'Repeat until finished'],
    'Plan → act → observe → decide, over and over, until the goal is reached. That cycle is the heart of an agent.'),
  l3.tf('iterative', 'An agent usually repeats the plan–act–observe cycle several times for one task.', true,
    'Most real tasks need many small steps. The agent loops until the goal is met or it decides to stop.'),
  l3.mc('observe-why', 'Why is the “observe” step so important?',
    ['The result tells the agent whether its last step worked and what to do next',
     'It makes the screen brighter',
     'It is only for decoration',
     'It deletes the goal'],
    0, 'Observing the outcome is the feedback that lets the agent adapt instead of blindly repeating a plan.'),
  l3.mc('react', 'The reasoning-and-acting pattern behind agents is often called…',
    ['Reason then act, in a repeating loop',
     'Answer then quit',
     'Guess then ignore',
     'Sleep then wake'],
    0, 'Agents interleave reasoning (planning) and acting (tools), looping so each action informs the next thought.'),
  l3.tf('one-shot', 'A good agent always finishes any task in a single step with no looping.', false,
    'Single steps handle only trivial tasks. Real goals need repeated plan–act–observe cycles.'),
  l3.mc('stop-condition', 'When should the loop stop?',
    ['When the goal is achieved, or a limit or failure says to stop',
     'Never — it should loop forever',
     'After exactly one second',
     'Only when the screen turns off'],
    0, 'A loop needs an exit: goal met, step limit reached, or an unrecoverable error. Otherwise it can run away.'),
  l3.match('phases', 'Match each phase of the loop to what happens.',
    [{ left: 'Plan', right: 'Decide the next step' },
     { left: 'Act', right: 'Use a tool or take action' },
     { left: 'Observe', right: 'Read the result that came back' }],
    'Plan sets the intent, act does it, observe checks the outcome — then the agent decides again.'),
  l3.mc('scenario-fix', 'An agent runs a search, but the result is empty. In the loop it should…',
    ['Observe the empty result and plan a different search',
     'Repeat the exact same search endlessly',
     'Crash and give up on everything',
     'Pretend it found the answer'],
    0, 'Observing failure is the point: the agent adapts its plan and tries a better step next time.', 'scenario'),
  l3.tf('feedback', 'Each pass of the loop feeds the result back into the next round of planning.', true,
    'That feedback is what makes agents flexible — every observation shapes the next decision.'),
  l3.mc('why-loop', 'The loop lets an agent…',
    ['Adapt step by step instead of committing to one fixed plan',
     'Avoid ever using tools',
     'Answer without any reasoning',
     'Forget the goal immediately'],
    0, 'Because it observes and re-plans each round, an agent can handle surprises rather than following a rigid script.'),
];

/* ================================================================== *
 * Lesson 4 — Memory & State
 * ================================================================== */
const l4 = bank('w9-l4', 'advanced');
const w9l4Q: Question[] = [
  l4.mc('why-memory', 'Why does an agent need memory?',
    ['To remember earlier steps and results so it can keep making progress',
     'To make the screen brighter',
     'To replace the need for a goal',
     'To slow itself down'],
    0, 'A multi-step task needs the agent to recall what it already did and learned, so it doesn’t start over each step.'),
  l4.tf('state', 'An agent’s “state” is what it currently knows and has done so far in the task.', true,
    'State is the running record — the goal, past steps, results and notes — that guides the next decision.'),
  l4.mc('no-memory', 'What happens if an agent forgets earlier steps?',
    ['It may repeat work or lose track of the goal',
     'It always finishes faster',
     'It becomes more accurate',
     'Nothing changes at all'],
    0, 'Without memory the agent can loop on the same step or contradict itself — progress falls apart.'),
  l4.match('memory-types', 'Match the memory idea to its meaning.',
    [{ left: 'Short-term memory', right: 'The current task’s steps and context' },
     { left: 'Long-term memory', right: 'Facts kept across many sessions' },
     { left: 'State', right: 'What the agent knows right now' }],
    'Short-term holds the task at hand, long-term persists across sessions, and state is the live snapshot.'),
  l4.mc('context-window', 'A model’s context window is…',
    ['The limited amount of text it can consider at once',
     'A physical window on a screen',
     'The colour of the app',
     'Unlimited memory'],
    0, 'The context window is finite, so agents must manage what to keep in it — this is why memory is a real challenge.'),
  l4.tf('unlimited', 'A language model can hold unlimited history in its context with no limit.', false,
    'Context is limited. As tasks grow long, agents must summarise or store history outside the window.'),
  l4.mc('summarise', 'When a task gets too long for the context window, a common fix is to…',
    ['Summarise older steps so key facts fit in less space',
     'Delete the goal',
     'Ignore all past steps',
     'Buy a bigger screen'],
    0, 'Summarising compresses history into the essentials, keeping the agent on track within its context limits.'),
  l4.match('store', 'Match each thing an agent might remember to its type.',
    [{ left: 'The user’s original goal', right: 'Keep for the whole task' },
     { left: 'A tool result from step 2', right: 'Short-term working memory' },
     { left: 'A user preference across chats', right: 'Long-term memory' }],
    'The goal anchors the task, working results guide the next step, and preferences persist across sessions.'),
  l4.mc('scenario-booking', 'An agent booking a trip forgot it already reserved the hotel and books a second one. The cause is…',
    ['Poor memory of earlier steps — it lost track of its own actions',
     'Too much memory',
     'The screen was too dim',
     'It had no goal'],
    0, 'Losing track of completed steps causes duplicated or conflicting actions — exactly why state matters.', 'scenario'),
  l4.tf('external', 'Agents can store memory outside the model, like in a database, to recall it later.', true,
    'External stores let agents remember far more than a context window holds and persist facts across sessions.'),
  l4.mc('good-state', 'Well-managed state helps an agent…',
    ['Stay consistent and build on what it has already done',
     'Forget the goal on purpose',
     'Use no tools ever',
     'Answer more slowly for no reason'],
    0, 'Good state tracking keeps the agent coherent across many steps instead of contradicting or repeating itself.'),
];

/* ================================================================== *
 * Lesson 5 — Multi-Step Reasoning
 * ================================================================== */
const l5 = bank('w9-l5', 'advanced');
const w9l5Q: Question[] = [
  l5.mc('decompose', 'What is the core skill in multi-step reasoning?',
    ['Breaking a big goal into smaller, ordered steps',
     'Answering in one word',
     'Avoiding all planning',
     'Using the biggest font'],
    0, 'Big goals become doable when split into a sequence of smaller steps the agent can tackle one at a time.'),
  l5.tf('adapt', 'A good agent can change its plan when a step fails.', true,
    'Plans meet reality. Observing a failure and adjusting the next steps is what separates robust agents from brittle ones.'),
  l5.order('plan', 'Order these steps for “research a topic and write a summary.”',
    ['Break the goal into subtasks', 'Search for sources', 'Read and extract key points', 'Draft the summary', 'Check it against the goal'],
    'Decompose first, gather, extract, draft, then verify — a typical multi-step plan an agent follows.'),
  l5.mc('failure', 'When a step fails, a strong agent should…',
    ['Notice the failure and try a different approach',
     'Repeat the same failing step forever',
     'Delete the whole goal',
     'Pretend it succeeded'],
    0, 'Detecting failure and re-planning is essential; blindly repeating or faking success leads nowhere.'),
  l5.tf('linear', 'Every task can be solved with one fixed straight-line plan that never changes.', false,
    'Real tasks throw surprises. Agents often revise the plan mid-task based on what they observe.'),
  l5.mc('subgoals', 'Breaking a goal into subgoals helps because…',
    ['Each small step is easier to reason about and check',
     'It uses more electricity',
     'It hides the goal',
     'It makes the model forget'],
    0, 'Smaller subgoals are simpler to plan, act on and verify — reducing errors on complex tasks.'),
  l5.match('reasoning', 'Match the term to its meaning.',
    [{ left: 'Decompose', right: 'Split a goal into subtasks' },
     { left: 'Re-plan', right: 'Change the plan after a failure' },
     { left: 'Verify', right: 'Check the result against the goal' }],
    'Decomposing, re-planning and verifying are three habits behind reliable multi-step reasoning.'),
  l5.mc('scenario-retry', 'An agent’s API call fails with a timeout. The best next step is…',
    ['Retry or pick another route, then continue the plan',
     'Abandon the entire task instantly',
     'Repeat the timeout call nonstop',
     'Claim the data was received'],
    0, 'Handling the failure — retry or reroute — then resuming the plan is robust multi-step behaviour.', 'scenario'),
  l5.tf('verify', 'Checking whether the result actually meets the goal is part of good reasoning.', true,
    'Verification catches steps that “ran” but didn’t truly satisfy the goal, preventing confident wrong finishes.'),
  l5.mc('dependency', 'Why does step order matter in a plan?',
    ['Some steps depend on the results of earlier ones',
     'Order never matters',
     'Later steps are always easier',
     'The model prefers alphabetical order'],
    0, 'You can’t summarise sources before finding them. Dependencies force a sensible sequence.'),
  l5.mc('robust', 'The mark of a robust agent is that it…',
    ['Adapts its plan as it learns what works and what fails',
     'Ignores every result it gets',
     'Uses exactly one step for everything',
     'Never checks its own work'],
    0, 'Robustness comes from planning, observing, and revising — not from a rigid, unchecked script.'),
];

/* ================================================================== *
 * Lesson 6 — Building a Safe, Useful Agent
 * ================================================================== */
const l6 = bank('w9-l6', 'advanced');
const w9l6Q: Question[] = [
  l6.mc('guardrails', 'What are guardrails for an agent?',
    ['Limits and rules that keep it from doing harmful or unwanted actions',
     'Decorations on the screen',
     'A way to make it faster',
     'Extra tools with no restrictions'],
    0, 'Guardrails constrain what an agent may do — which tools, which actions, which limits — to keep it safe.'),
  l6.tf('human-oversight', 'For risky actions, keeping a human in the loop to approve is a good safety practice.', true,
    'Human approval for high-impact steps (spending money, deleting data) catches mistakes before they cause harm.'),
  l6.mc('runaway', 'A “runaway” agent is one that…',
    ['Keeps taking actions without stopping or oversight, possibly causing harm',
     'Runs slightly slowly',
     'Refuses to use any tool',
     'Only answers in short sentences'],
    0, 'Without limits an agent can loop or act endlessly. Step limits and stop conditions prevent runaway behaviour.'),
  l6.match('safety', 'Match each safety measure to what it does.',
    [{ left: 'Step limit', right: 'Stops endless looping' },
     { left: 'Human approval', right: 'Reviews risky actions first' },
     { left: 'Restricted tools', right: 'Limits what the agent can do' }],
    'Step limits, human approval and restricted tools are core ways to keep an agent safe and predictable.'),
  l6.mc('least-privilege', 'Giving an agent only the tools it truly needs is an example of…',
    ['Limiting its power to reduce risk',
     'Making it slower on purpose',
     'Removing its goal',
     'Adding random tools'],
    0, 'The fewer and safer the tools, the less damage a mistaken action can do — minimal access is safer.'),
  l6.tf('trust-blindly', 'Because agents are automated, we should let them run important tasks with zero review.', false,
    'Automation doesn’t mean infallible. Important or irreversible actions still need review and limits.'),
  l6.mc('irreversible', 'Which action most deserves a human check before an agent does it?',
    ['Permanently deleting a customer database',
     'Reading a public web page',
     'Doing a simple calculation',
     'Summarising a paragraph'],
    0, 'Irreversible, high-impact actions carry the most risk, so they warrant human approval before proceeding.', 'scenario'),
  l6.tf('limits-useful', 'Well-chosen limits can make an agent more trustworthy and useful, not less.', true,
    'Guardrails let people rely on an agent, because its actions stay within safe, predictable bounds.'),
  l6.mc('testing', 'Before letting an agent act freely, a wise step is to…',
    ['Test it on safe cases and watch its behaviour',
     'Give it every possible tool immediately',
     'Remove all limits to see what happens',
     'Skip testing to save time'],
    0, 'Testing on low-risk cases reveals mistakes early, before the agent is trusted with important actions.'),
  l6.match('good-agent', 'Match each trait of a good agent to its benefit.',
    [{ left: 'Clear goal', right: 'Knows what success means' },
     { left: 'Guardrails', right: 'Stays safe' },
     { left: 'Human oversight', right: 'Catches mistakes' }],
    'A useful agent pairs a clear goal with guardrails and oversight — capable, but kept in check.'),
  l6.mc('balance', 'Building a good agent is mainly about balancing…',
    ['Usefulness with safety — capable, but controlled',
     'Speed with screen brightness',
     'Colour with font size',
     'Noise with silence'],
    0, 'The goal is an agent that gets real work done while staying safe, limited and open to human oversight.'),
  l6.tf('done', 'Understanding agents means seeing them as powerful tools that still need careful design.', true,
    'Agents can act toward goals, but their power makes thoughtful design, limits and oversight essential.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD9_LESSONS: Lesson[] = [
  {
    id: 'w9-l1', worldId: W, order: 1,
    title: 'From Chatbots to Agents',
    subtitle: 'When AI stops answering and starts doing',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 60, coins: 6,
    description: 'A chatbot answers your question. An agent takes actions to reach a goal. That leap — from talking to doing — is what World 9 is all about.',
    explanation: 'An agent is built around a language model but adds something new: the ability to act. Instead of just replying, it can search, calculate, send messages and more, chaining steps until a goal is done.',
    realWorld: 'Ask a chatbot “how do I book a flight?” and it explains the steps. Ask an agent “book me a flight,” and it actually searches, compares and books one — doing the steps, not just describing them.',
    objectives: [
      'Define what an AI agent is',
      'Contrast an agent with a plain chatbot',
      'Spot goal-driven, action-taking behaviour',
    ],
    activity: {
      kind: 'bucket',
      title: 'Chatbot or Agent?',
      instructions: 'Sort each behaviour by whether a plain chatbot could do it, or it needs an agent that acts.',
      config: {
        buckets: ['Plain chatbot', 'Needs an agent'],
        items: [
          { label: 'Explain how to book a flight', bucket: 0 },
          { label: 'Define a word', bucket: 0 },
          { label: 'Write a poem when asked', bucket: 0 },
          { label: 'Actually book the flight for you', bucket: 1 },
          { label: 'Search, then delete spam emails', bucket: 1 },
          { label: 'Compare prices and buy the cheapest', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'An agent takes actions toward a goal, not just answers.',
      'Agents are usually built around a language model as their “brain”.',
      'The shift from chatbot to agent is answering → acting.',
    ],
    commonMistakes: [
      'Thinking any chatbot is an agent — only acting toward a goal counts.',
      'Assuming agents are always right; they can pick wrong actions.',
    ],
    summary: 'Agents move from talking about tasks to actually doing them, step by step, to reach a goal.',
    prerequisiteLessonIds: ['w8-l6'],
    nextLessonId: 'w9-l2',
  },
  {
    id: 'w9-l2', worldId: W, order: 2,
    title: 'Tool Calling: Giving AI Hands',
    subtitle: 'How a model reaches out and acts',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 65, coins: 7,
    description: 'On its own, a model can only produce words. Tools — search, a calculator, APIs — give it hands to fetch fresh data and act on the world.',
    explanation: 'The model outputs a structured request naming a tool and its inputs. The system runs the tool and hands the result back, so the model can continue with real, up-to-date information.',
    realWorld: 'A model guessing today’s weather might be wrong. Give it a weather tool and it looks up the real answer — just like you’d check an app instead of guessing out the window.',
    objectives: [
      'Explain what a tool is in agent terms',
      'Describe how a model calls a tool and uses the result',
      'Match tools to the jobs they handle',
    ],
    activity: {
      kind: 'bucket',
      title: 'Which Tool Fits?',
      instructions: 'Match each need to the kind of tool an agent would reach for.',
      config: {
        buckets: ['Needs a live/data tool', 'Model can do it alone'],
        items: [
          { label: 'Today’s weather', bucket: 0 },
          { label: 'Exact multiplication of big numbers', bucket: 0 },
          { label: 'Latest news headline', bucket: 0 },
          { label: 'Send an email', bucket: 0 },
          { label: 'Rephrase a sentence', bucket: 1 },
          { label: 'Explain a simple idea', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Tools are external actions a model can call — its “hands”.',
      'The model requests a tool; the result is fed back to continue.',
      'An agent can only use the tools it’s been given.',
    ],
    commonMistakes: [
      'Thinking a model can fetch live data without a tool — it can’t.',
      'Forgetting that some tools take real actions, so access must be limited.',
    ],
    summary: 'Tools let a model do and fetch things words alone can’t — the model calls them and builds on the results.',
    prerequisiteLessonIds: ['w9-l1'],
    nextLessonId: 'w9-l3',
  },
  {
    id: 'w9-l3', worldId: W, order: 3,
    title: 'The Agent Loop: Plan, Act, Observe',
    subtitle: 'Reason, do, look, repeat',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 8,
    description: 'Agents don’t finish in one shot. They cycle: plan a step, act, observe the result, decide what’s next — looping until the goal is done.',
    explanation: 'Each round the agent reasons about the next step, takes it (often with a tool), reads what came back, and uses that to plan the next step. This feedback loop lets it adapt instead of following a rigid script.',
    realWorld: 'Like cooking from a new recipe: you do a step, taste it, and adjust the next step based on how it turned out — rather than blindly following every line no matter what.',
    objectives: [
      'Describe the plan–act–observe–decide loop',
      'Explain why observing results enables adapting',
      'Identify when the loop should stop',
    ],
    activity: {
      kind: 'steps',
      title: 'Build the Agent Loop',
      instructions: 'Drag the phases into the order an agent runs, then repeats until the goal is done.',
      config: {
        steps: [
          'Plan the next step toward the goal',
          'Act — use a tool or take an action',
          'Observe the result that comes back',
          'Decide whether the goal is done',
          'Repeat until finished',
        ],
      },
    },
    keyTakeaways: [
      'Agents loop: plan → act → observe → decide, repeatedly.',
      'Observing results is the feedback that lets an agent adapt.',
      'The loop needs a stop condition to avoid running away.',
    ],
    commonMistakes: [
      'Expecting an agent to finish complex tasks in one step.',
      'Forgetting a stop condition, letting the loop run forever.',
    ],
    summary: 'The plan–act–observe cycle, repeated with feedback, is the engine that drives every agent.',
    prerequisiteLessonIds: ['w9-l2'],
    nextLessonId: 'w9-l4',
  },
  {
    id: 'w9-l4', worldId: W, order: 4,
    title: 'Memory & State',
    subtitle: 'How an agent remembers what it’s done',
    difficulty: 'advanced', estimatedMinutes: 7, xp: 75, coins: 10,
    description: 'A multi-step task falls apart if the agent forgets earlier steps. Memory and state let it keep track and build on what it already did.',
    explanation: 'State is the running record of the goal, the steps taken and their results. Because a model’s context window is limited, agents summarise older steps or store facts externally to remember more than fits at once.',
    realWorld: 'Like taking notes while running errands: you jot down what’s done so you don’t buy milk twice or forget the bank. The notes are the agent’s memory of its own progress.',
    objectives: [
      'Explain why agents need memory and state',
      'Distinguish short-term from long-term memory',
      'Understand context-window limits and how agents cope',
    ],
    activity: {
      kind: 'bucket',
      title: 'Which Memory Holds This?',
      instructions: 'Sort each item by where an agent would keep it.',
      config: {
        buckets: ['Short-term (this task)', 'Long-term (across sessions)'],
        items: [
          { label: 'The current goal being worked on', bucket: 0 },
          { label: 'A tool result from two steps ago', bucket: 0 },
          { label: 'Which steps are already done', bucket: 0 },
          { label: 'The user’s preferred language', bucket: 1 },
          { label: 'A saved profile from last week', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'State tracks the goal, steps taken and results so far.',
      'A model’s context window is limited, so memory must be managed.',
      'Agents summarise or store history externally to remember more.',
    ],
    commonMistakes: [
      'Assuming a model can hold unlimited history — context is finite.',
      'Ignoring state, so the agent repeats or contradicts its own steps.',
    ],
    summary: 'Memory and state keep an agent coherent across many steps, so it builds on progress instead of losing it.',
    prerequisiteLessonIds: ['w9-l3'],
    nextLessonId: 'w9-l5',
  },
  {
    id: 'w9-l5', worldId: W, order: 5,
    title: 'Multi-Step Reasoning',
    subtitle: 'Break the goal down, adapt when it breaks',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 75, coins: 11,
    description: 'Big goals become doable when split into ordered steps. A strong agent also notices when a step fails and changes its plan instead of giving up or faking it.',
    explanation: 'Multi-step reasoning means decomposing a goal into subtasks, respecting the order in which they depend on each other, verifying results against the goal, and re-planning whenever something fails.',
    realWorld: 'Planning a party: you split it into invites, food and music, do them in a sensible order, and if the caterer cancels you find another — you adapt rather than abandon the party.',
    objectives: [
      'Break a big goal into ordered subtasks',
      'Explain why order and dependencies matter',
      'Adapt the plan when a step fails',
    ],
    activity: {
      kind: 'sequence',
      title: 'What Comes Next?',
      instructions: 'An agent is researching a topic to write a summary. Which step should come next?',
      config: {
        shown: ['Break the goal into subtasks', 'Search for sources', 'Read and extract key points'],
        options: ['Draft the summary from the key points', 'Delete the goal', 'Start over from scratch', 'Buy a bigger screen'],
        correctIndex: 0,
        reveal: 'Once you’ve gathered and extracted the key points, the next dependent step is to draft the summary — then verify it against the goal.',
      },
    },
    keyTakeaways: [
      'Decompose big goals into smaller, ordered steps.',
      'Some steps depend on earlier ones, so order matters.',
      'Robust agents re-plan when a step fails.',
    ],
    commonMistakes: [
      'Assuming one fixed straight-line plan always works.',
      'Repeating a failing step instead of trying a new approach.',
    ],
    summary: 'Multi-step reasoning is decompose, order, act, verify — and adapt the plan whenever reality pushes back.',
    prerequisiteLessonIds: ['w9-l4'],
    nextLessonId: 'w9-l6',
  },
  {
    id: 'w9-l6', worldId: W, order: 6,
    title: 'Building a Safe, Useful Agent',
    subtitle: 'Capable, but kept in check',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'The power to act means the power to make mistakes at scale. Guardrails, limits and human oversight keep an agent useful without letting it run away.',
    explanation: 'Safe agents get only the tools they need, run under step limits and stop conditions, and route risky or irreversible actions through a human for approval. Good limits make an agent more trustworthy, not less.',
    realWorld: 'Like a new employee: you give them the access they need, not the keys to everything, and you review big decisions before they’re final. Trust grows with proven, limited responsibility.',
    objectives: [
      'Describe guardrails, limits and human oversight',
      'Explain how to prevent runaway or harmful actions',
      'Balance usefulness against safety',
    ],
    activity: {
      kind: 'bucket',
      title: 'Approve or Auto-Run?',
      instructions: 'Sort each action by whether an agent can just do it, or a human should approve it first.',
      config: {
        buckets: ['Safe to auto-run', 'Needs human approval'],
        items: [
          { label: 'Read a public web page', bucket: 0 },
          { label: 'Do a calculation', bucket: 0 },
          { label: 'Summarise a document', bucket: 0 },
          { label: 'Permanently delete a database', bucket: 1 },
          { label: 'Spend money on a purchase', bucket: 1 },
          { label: 'Email all customers at once', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Guardrails and step limits stop harmful or runaway actions.',
      'Route risky, irreversible actions through human approval.',
      'Give an agent only the tools it truly needs.',
    ],
    commonMistakes: [
      'Trusting an automated agent to run important tasks with no review.',
      'Giving an agent every tool instead of the minimum it needs.',
    ],
    summary: 'A great agent balances usefulness with safety — capable enough to help, controlled enough to trust.',
    prerequisiteLessonIds: ['w9-l5'],
    nextLessonId: 'w10-l1',
  },
];

export const WORLD9_QUESTIONS: Question[] = [
  ...w9l1Q, ...w9l2Q, ...w9l3Q,
  ...w9l4Q, ...w9l5Q, ...w9l6Q,
];
