import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 3 — Neural Networks. Full lessons + question bank.
 * Structure mirrors world1.ts (the reference template).
 */

const W = 'world-neural-networks';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — What Is a Neuron?
 * ================================================================== */
const l1 = bank('w3-l1', 'beginner');
const w3l1Q: Question[] = [
  l1.mc('definition', 'What is an artificial neuron?',
    ['A tiny unit that takes in numbers and produces one output number',
     'A living brain cell inside the computer',
     'A wire that carries electricity',
     'A screen that shows results'],
    0, 'An artificial neuron is just a small math unit: it receives some input numbers, combines them, and passes out a single value.'),
  l1.tf('inspiration', 'Artificial neurons were loosely inspired by brain cells.', true,
    'The name comes from biology. A real neuron receives signals and fires; the artificial version copies that idea with math, not biology.'),
  l1.mc('inputs', 'A neuron starts by doing what with its inputs?',
    ['Combining them into a single number',
     'Deleting them',
     'Printing them on screen',
     'Ignoring them completely'],
    0, 'A neuron gathers all its incoming numbers and combines them into one value before deciding what to output.'),
  l1.mc('output', 'How many outputs does a single neuron produce?',
    ['One',
     'Zero',
     'Exactly ten',
     'One per input'],
    0, 'No matter how many inputs come in, a neuron squeezes them down to a single output number.'),
  l1.tf('building-block', 'A neuron is the basic building block of a neural network.', true,
    'Just like bricks build a wall, many neurons connect together to build a whole neural network.'),
  l1.mc('scenario-fruit', 'You feed a neuron the weight and colour of a fruit. What does it give back?',
    ['One number, like a score for “how likely this is an apple”',
     'A photo of the fruit',
     'The fruit itself',
     'A list of every fruit in the world'],
    0, 'The neuron blends its inputs into a single output number — here, a score the network can use to make a guess.', 'scenario'),
  l1.match('anatomy', 'Match each part of a neuron to its job.',
    [{ left: 'Inputs', right: 'The numbers coming in' },
     { left: 'Neuron', right: 'Combines inputs into one value' },
     { left: 'Output', right: 'The single number sent out' }],
    'Inputs go in, the neuron combines them, and one output comes out — that is the whole flow.'),
  l1.mc('not-brain', 'Which statement about artificial neurons is TRUE?',
    ['They are math, not real biological cells',
     'They are alive and can feel',
     'They are made of the same stuff as your brain',
     'They think for themselves'],
    0, 'An artificial neuron is pure mathematics running on a computer — it only borrows the name and idea from biology.'),
  l1.tf('single', 'A single neuron on its own can solve any complex problem.', false,
    'One neuron is very limited. Its power only appears when many neurons are connected together into a network.'),
  l1.mc('purpose', 'The main purpose of a neuron is to…',
    ['Turn several input numbers into one useful output number',
     'Store photos',
     'Charge the battery',
     'Connect to the internet'],
    0, 'A neuron is a little decision-maker: it takes inputs, mixes them, and returns one number others can build on.'),
  l1.mc('everyday', 'Thinking of a neuron as a “tiny voting machine” works because…',
    ['It weighs its inputs and produces one combined result',
     'It has a physical lever',
     'It counts real ballots',
     'It needs a human to vote'],
    0, 'Each input gets a say, the neuron tallies them, and out comes one result — a handy way to picture what it does.'),
  l1.tf('many', 'Real neural networks contain many neurons working together.', true,
    'Modern networks have thousands, millions, even billions of neurons — the single neuron is just where we start.'),
];

/* ================================================================== *
 * Lesson 2 — Layers: Input, Hidden & Output
 * ================================================================== */
const l2 = bank('w3-l2', 'beginner');
const w3l2Q: Question[] = [
  l2.mc('layers-def', 'What is a “layer” in a neural network?',
    ['A group of neurons working at the same stage',
     'A single neuron',
     'The computer’s screen',
     'A type of battery'],
    0, 'A layer is just a row of neurons that all process information at the same step before passing it on.'),
  l2.mc('three-kinds', 'The three main kinds of layers are…',
    ['Input, hidden and output',
     'Top, middle and bottom',
     'Fast, slow and medium',
     'Red, green and blue'],
    0, 'Data enters the input layer, gets processed in hidden layers, and the answer comes out of the output layer.'),
  l2.mc('input-layer', 'What does the input layer do?',
    ['Receives the raw data you give the network',
     'Prints the final answer',
     'Stores the network on disk',
     'Charges the phone'],
    0, 'The input layer is the front door — it takes in the raw numbers (pixels, features, values) to be processed.'),
  l2.mc('output-layer', 'What does the output layer do?',
    ['Gives the network’s final answer',
     'Takes in the raw data',
     'Deletes the hidden layers',
     'Nothing at all'],
    0, 'The output layer is the last stage — it delivers the network’s prediction, like “cat” or “dog”.'),
  l2.tf('hidden-middle', 'Hidden layers sit between the input and output layers.', true,
    'Hidden layers are in the middle, doing the real processing. They are “hidden” because you don’t see their values directly.'),
  l2.match('layer-jobs', 'Match each layer to its job.',
    [{ left: 'Input layer', right: 'Takes in raw data' },
     { left: 'Hidden layer', right: 'Processes and finds patterns' },
     { left: 'Output layer', right: 'Gives the final answer' }],
    'Input takes it in, hidden layers do the thinking, and the output layer delivers the result.'),
  l2.order('flow', 'Put the flow of information through a network in order.',
    ['Data enters the input layer', 'It passes through the hidden layers', 'The output layer produces the answer'],
    'Information always flows the same way: in through the input, through the hidden middle, and out as the answer.'),
  l2.tf('more-complex', 'Stacking neurons into layers lets a network learn more complex patterns.', true,
    'A single layer can only do so much. Extra layers let the network build up complicated patterns step by step.'),
  l2.mc('scenario-image', 'A network recognises a handwritten “7”. Where do the raw pixels go first?',
    ['Into the input layer',
     'Into the output layer',
     'Straight to the answer',
     'They skip the network'],
    0, 'Raw data — here, the pixels of the digit — always enters through the input layer before any processing happens.', 'scenario'),
  l2.mc('why-hidden', 'Why are hidden layers useful?',
    ['They find deeper patterns between input and output',
     'They make the screen brighter',
     'They save electricity',
     'They store your password'],
    0, 'Hidden layers do the heavy lifting, transforming raw inputs step by step into patterns the output can use.'),
  l2.tf('no-hidden', 'A network can have more than one hidden layer.', true,
    'Networks often stack several hidden layers. More hidden layers can capture richer, more detailed patterns.'),
  l2.mc('picture', 'A good picture of a neural network is…',
    ['Columns of neurons, information flowing left to right',
     'A single dot',
     'A straight wire with no parts',
     'A blank page'],
    0, 'Think of layers as columns of neurons, with data flowing from the input column through to the output column.'),
];

/* ================================================================== *
 * Lesson 3 — Weights & Biases
 * ================================================================== */
const l3 = bank('w3-l3', 'beginner');
const w3l3Q: Question[] = [
  l3.mc('weight-def', 'What is a “weight” in a neural network?',
    ['A number that says how important an input is',
     'How heavy the computer is',
     'The size of the screen',
     'The number of neurons'],
    0, 'A weight is a number that scales each input, telling the neuron how much that input should matter.'),
  l3.mc('bias-def', 'What does a “bias” do?',
    ['Shifts the neuron’s result up or down',
     'Makes the network unfair on purpose',
     'Deletes an input',
     'Turns off the computer'],
    0, 'A bias is an extra number added in that nudges the neuron’s output, giving it a little head start or offset.'),
  l3.tf('knobs', 'Weights and biases are the “knobs” a network tunes as it learns.', true,
    'Learning is really just adjusting these numbers. Turn the knobs the right way and the network gets better.'),
  l3.mc('big-weight', 'If an input has a large weight, it means…',
    ['That input strongly affects the neuron’s output',
     'That input is ignored',
     'The neuron is broken',
     'The input is deleted'],
    0, 'A big weight gives an input a loud voice; a small weight makes it a whisper the neuron barely hears.'),
  l3.mc('small-weight', 'An input with a weight near zero…',
    ['Has almost no effect on the output',
     'Controls the whole network',
     'Is the most important input',
     'Breaks the neuron'],
    0, 'A near-zero weight mutes an input — the neuron treats it as barely relevant to its decision.'),
  l3.match('terms', 'Match each term to its meaning.',
    [{ left: 'Weight', right: 'How important an input is' },
     { left: 'Bias', right: 'A shift added to the result' },
     { left: 'Learning', right: 'Adjusting weights and biases' }],
    'Weights set importance, bias shifts the result, and learning means tuning both until answers improve.'),
  l3.tf('learned', 'Weights and biases are set by hand by programmers.', false,
    'They are not hand-set. The network learns them automatically by adjusting them during training.'),
  l3.mc('scenario-loan', 'A network judges loan risk. Income gets a big weight, favourite colour gets near-zero. Why?',
    ['Income matters for risk; favourite colour does not',
     'Colours are always important',
     'The network prefers numbers over words',
     'Weights are chosen randomly forever'],
    0, 'The network learns to give useful inputs large weights and irrelevant ones tiny weights — importance in action.', 'scenario'),
  l3.mc('tuning', 'During training, what happens to the weights?',
    ['They get adjusted to reduce mistakes',
     'They stay frozen forever',
     'They are erased each round',
     'They turn into biases'],
    0, 'Each round of training nudges the weights so the network’s guesses get a little closer to correct.'),
  l3.tf('millions', 'A large network can have millions of weights.', true,
    'Big networks have huge numbers of weights and biases — all tuned together during training.'),
  l3.mc('analogy', 'Weights are most like…',
    ['Volume knobs deciding how loud each input is',
     'A power cable',
     'A phone case',
     'A random dice roll'],
    0, 'Picture each input on its own volume knob: weights turn some inputs up and others down before they’re combined.'),
  l3.mc('together', 'Weights and biases together let a neuron…',
    ['Combine inputs and shift the result to fit the data',
     'Only add numbers with no flexibility',
     'Ignore all inputs',
     'Choose its own colour'],
    0, 'Weights decide how inputs mix; the bias shifts the result. Together they give the neuron the flexibility to fit patterns.'),
];

/* ================================================================== *
 * Lesson 4 — Activation Functions
 * ================================================================== */
const l4 = bank('w3-l4', 'intermediate');
const w3l4Q: Question[] = [
  l4.mc('activation-def', 'What does an activation function decide?',
    ['Whether and how strongly a neuron “fires”',
     'The colour of the screen',
     'How many layers exist',
     'The price of the computer'],
    0, 'After a neuron combines its inputs, the activation function decides how much signal to pass on — its “firing”.'),
  l4.tf('fire', 'The idea of a neuron “firing” comes from how brain cells send signals.', true,
    'Like a brain cell that only fires past a threshold, an activation function decides whether the neuron passes a signal.'),
  l4.mc('why-nonlinear', 'Activation functions add “non-linearity”, which lets networks…',
    ['Learn complex, curved patterns, not just straight lines',
     'Run without electricity',
     'Skip having any layers',
     'Only add numbers'],
    0, 'Without activation functions a network could only draw straight lines. They let it bend and curve to fit real data.'),
  l4.mc('no-activation', 'Without any activation functions, a deep network would…',
    ['Collapse into one simple straight-line calculation',
     'Become far more powerful',
     'Grow extra layers by itself',
     'Refuse to turn on'],
    0, 'Stacking layers without activations is pointless — the whole thing behaves like one plain linear step, no matter the depth.'),
  l4.tf('threshold', 'Some activation functions act like a threshold: fire only if the input is strong enough.', true,
    'Many activations stay quiet for weak inputs and switch on once the combined signal crosses a certain level.'),
  l4.match('idea', 'Match each idea to its meaning.',
    [{ left: 'Activation function', right: 'Decides if a neuron fires' },
     { left: 'Non-linearity', right: 'Ability to learn curved patterns' },
     { left: 'Threshold', right: 'The point where firing begins' }],
    'The activation gates the output, adds non-linearity, and often works like a threshold for firing.'),
  l4.mc('scenario-decide', 'A neuron’s combined input is very weak. A threshold-style activation will…',
    ['Keep the neuron mostly quiet',
     'Force it to fire at full strength',
     'Delete the neuron',
     'Turn off the whole network'],
    0, 'A weak signal that hasn’t crossed the threshold means the neuron passes little or nothing forward — it stays quiet.', 'scenario'),
  l4.tf('essential', 'Activation functions are an optional extra with no real effect.', false,
    'They are essential. Remove them and the network loses its power to learn anything but simple straight-line relationships.'),
  l4.mc('placement', 'Where does the activation function do its work?',
    ['Right after a neuron combines its inputs',
     'Before any input arrives',
     'Only on the screen',
     'After the computer shuts down'],
    0, 'The neuron first blends its inputs into one number, then the activation function shapes that number into the output.'),
  l4.mc('gatekeeper', 'A good analogy for an activation function is…',
    ['A gatekeeper deciding how much signal passes through',
     'A power switch for the building',
     'A storage box',
     'A random number generator'],
    0, 'Think of it as a gate: it looks at the combined signal and decides how much of it to let through to the next layer.'),
  l4.tf('curves', 'Non-linearity is what lets networks model complicated, real-world relationships.', true,
    'Real data rarely follows a straight line. Non-linearity from activations lets networks capture those twists and curves.'),
  l4.mc('summary-role', 'In one line, the activation function’s job is to…',
    ['Turn a neuron’s combined input into a shaped, useful output',
     'Store the training data',
     'Draw the network diagram',
     'Count the layers'],
    0, 'It takes the raw combined value and reshapes it — deciding how strongly the neuron speaks to the next layer.'),
];

/* ================================================================== *
 * Lesson 5 — How a Network Learns
 * ================================================================== */
const l5 = bank('w3-l5', 'intermediate');
const w3l5Q: Question[] = [
  l5.mc('forward-pass', 'What is the “forward pass”?',
    ['Data flowing through the network to make a guess',
     'The network shutting down',
     'Deleting the weights',
     'Charging the battery'],
    0, 'In the forward pass, input flows layer by layer to the output, producing the network’s guess.'),
  l5.mc('error', 'After a guess, the network measures the “error”, which is…',
    ['How far the guess was from the correct answer',
     'How fast the computer runs',
     'How many neurons there are',
     'The screen brightness'],
    0, 'The error compares the guess to the true answer — a big error means the network was very wrong.'),
  l5.mc('backprop', 'What is backpropagation?',
    ['Sending the error backward to adjust the weights',
     'Turning the computer off',
     'Adding more screens',
     'Deleting the network'],
    0, 'Backpropagation carries the error backward through the layers so each weight learns how to change to do better.'),
  l5.tf('guess-check-adjust', 'Learning is a loop of guess, check the error, then adjust.', true,
    'The network guesses (forward pass), checks how wrong it was (error), and adjusts its weights (backprop) — over and over.'),
  l5.order('loop', 'Put the learning steps in order.',
    ['Forward pass: make a guess', 'Compare the guess to the correct answer', 'Measure the error', 'Backpropagate the error', 'Adjust the weights', 'Repeat many times'],
    'Guess, compare, measure the error, send it backward, tweak the weights, and repeat until the network is good.'),
  l5.tf('one-round', 'A network learns perfectly after just one round of training.', false,
    'One round is nowhere near enough. Networks improve gradually over many rounds of guess-check-adjust.'),
  l5.match('terms', 'Match each learning term to its meaning.',
    [{ left: 'Forward pass', right: 'Flow inputs to a guess' },
     { left: 'Error', right: 'How wrong the guess was' },
     { left: 'Backpropagation', right: 'Send error back to fix weights' }],
    'Forward pass makes the guess, error measures the miss, and backpropagation fixes the weights.'),
  l5.mc('scenario-cat', 'A network guesses “dog” for a cat photo. What happens next in training?',
    ['The error is sent back and weights are adjusted',
     'The network is thrown away',
     'Nothing — the mistake is ignored',
     'The photo is deleted'],
    0, 'A wrong guess creates an error, which backpropagation uses to nudge the weights so next time it’s more likely right.', 'scenario'),
  l5.tf('direction', 'Backpropagation tells each weight which way to change to reduce error.', true,
    'That is its whole point: it works out, for every weight, whether to go up or down to shrink the mistake.'),
  l5.mc('repeat', 'Why does training repeat so many times?',
    ['Each pass only nudges the weights a little closer to good',
     'The computer forgets instantly',
     'To waste time on purpose',
     'Because one input isn’t enough'],
    0, 'Each round makes a small improvement. Thousands of rounds add up to a network that guesses well.'),
  l5.mc('analogy', 'This learning loop is most like…',
    ['A student doing practice, checking answers, and improving',
     'A calculator giving a fixed answer',
     'A book that never changes',
     'A light switch'],
    0, 'Practice, check your mistakes, adjust — that’s exactly how a network learns, one correction at a time.'),
  l5.tf('goal', 'The goal of training is to reduce the error on the network’s guesses.', true,
    'Every adjustment aims to shrink the error, so over time the network’s answers get closer and closer to correct.'),
];

/* ================================================================== *
 * Lesson 6 — Deep Learning: Why "Deep"?
 * ================================================================== */
const l6 = bank('w3-l6', 'advanced');
const w3l6Q: Question[] = [
  l6.mc('deep-def', 'What makes learning “deep” in deep learning?',
    ['The network has many hidden layers',
     'The computer is buried underground',
     'The screen is very dark',
     'It uses deep-sea data'],
    0, '“Deep” simply means many stacked hidden layers — depth is the number of layers, not anything mysterious.'),
  l6.tf('layers-depth', 'More layers generally let a network learn richer, more complex patterns.', true,
    'Each extra layer builds on the last, letting deep networks capture patterns far too complex for a shallow one.'),
  l6.mc('build-up', 'In a deep network for images, early layers might detect…',
    ['Simple edges, while later layers detect whole objects',
     'Only the final answer',
     'Nothing until the very end',
     'The colour of the computer'],
    0, 'Depth lets networks build up: edges → shapes → parts → objects, each layer combining what the last one found.'),
  l6.mc('why-unlocked', 'Why did depth help unlock modern AI?',
    ['It let networks learn complex real-world patterns from lots of data',
     'It made computers cheaper to build',
     'It removed the need for data',
     'It made screens bigger'],
    0, 'With enough data and computing power, deep networks learned patterns shallow methods never could — powering modern AI.'),
  l6.tf('always-better', 'Adding endless layers always makes a network better with no downsides.', false,
    'Depth helps, but too many layers can be hard to train and need far more data and computing power — it’s a trade-off.'),
  l6.match('depth', 'Match each idea to its meaning.',
    [{ left: 'Deep learning', right: 'Networks with many layers' },
     { left: 'Early layers', right: 'Detect simple features' },
     { left: 'Later layers', right: 'Detect complex features' }],
    'Deep means many layers; early ones spot simple features and later ones combine them into complex ones.'),
  l6.mc('scenario-face', 'A deep face-recognition network. What likely happens layer by layer?',
    ['Edges first, then eyes and noses, then whole faces',
     'The whole face is recognised in layer one',
     'Nothing until the last neuron',
     'It recognises sound, not images'],
    0, 'Depth builds understanding in stages: simple edges combine into features, which combine into full faces.', 'scenario'),
  l6.tf('data-compute', 'Deep learning needs lots of data and computing power to work well.', true,
    'Its rise came alongside big datasets and powerful hardware — both are needed to train deep networks effectively.'),
  l6.mc('shallow-vs-deep', 'Compared with a shallow network, a deep network can…',
    ['Learn more complex patterns, given enough data',
     'Always run faster',
     'Work with no data',
     'Never make mistakes'],
    0, 'Depth trades speed and data hunger for the ability to model far more complex relationships.'),
  l6.mc('modern-ai', 'Deep learning powers many modern AI systems because…',
    ['Its depth captures the rich patterns in images, speech and language',
     'It is the cheapest option',
     'It needs no training',
     'It only works offline'],
    0, 'The complex patterns in real-world data need depth — which is why deep learning sits behind so much modern AI.'),
  l6.tf('recap', 'Neurons, layers, weights, activations and learning all come together in deep networks.', true,
    'Deep learning is the whole picture: many neurons in many layers, tuned by weights and activations, trained to learn.'),
  l6.mc('summary-deep', 'The one-line takeaway on why “deep” matters is…',
    ['More layers let networks learn richer patterns, unlocking modern AI',
     'Deep just means slow',
     'Deep means dark-coloured',
     'Depth has no effect at all'],
    0, 'Stacking many layers lets networks build up complex understanding — the key reason deep learning transformed AI.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD3_LESSONS: Lesson[] = [
  {
    id: 'w3-l1', worldId: W, order: 1,
    title: 'What Is a Neuron?',
    subtitle: 'The tiny building block',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'Meet the artificial neuron — the smallest piece of a neural network. It takes in numbers and gives back just one.',
    explanation: 'An artificial neuron is a tiny math unit. It receives several input numbers, combines them into one value, and passes that single number along. On its own it’s simple; the magic comes from connecting many together.',
    realWorld: 'Picture a tiny voting machine: each input gets a say, the machine tallies them up, and out comes one result. That’s a neuron.',
    objectives: [
      'Define an artificial neuron in plain words',
      'Explain that a neuron takes inputs and gives one output',
      'See why one neuron is only a building block',
    ],
    activity: {
      kind: 'steps',
      title: 'Inside a Neuron',
      instructions: 'Drag the steps into the order a neuron actually works in.',
      config: {
        steps: [
          'Input numbers arrive',
          'The neuron combines them into one value',
          'It produces a single output number',
        ],
      },
    },
    keyTakeaways: [
      'A neuron takes several inputs and produces one output.',
      'It’s math, not a real brain cell.',
      'Power comes from connecting many neurons together.',
    ],
    commonMistakes: [
      'Thinking an artificial neuron is a living brain cell.',
      'Believing one neuron can solve complex problems alone.',
      'Assuming a neuron gives many outputs — it gives just one.',
    ],
    summary: 'An artificial neuron is a tiny math unit that turns input numbers into a single output.',
    prerequisiteLessonIds: ['w2-l8'],
    nextLessonId: 'w3-l2',
  },
  {
    id: 'w3-l2', worldId: W, order: 2,
    title: 'Layers: Input, Hidden & Output',
    subtitle: 'Stacking neurons into stages',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 5,
    description: 'One neuron is limited. Group neurons into layers and information flows through stages to build real complexity.',
    explanation: 'Neurons are arranged in layers. The input layer takes in raw data, hidden layers in the middle do the processing, and the output layer gives the final answer. Information flows from input, through hidden, to output.',
    realWorld: 'Think of a factory line: raw materials come in one end (input), stations in the middle shape them (hidden), and a finished product comes out the other end (output).',
    objectives: [
      'Name the three kinds of layers',
      'Describe how information flows through a network',
      'Explain why hidden layers add power',
    ],
    activity: {
      kind: 'steps',
      title: 'Follow the Data',
      instructions: 'Arrange the layers in the order data flows through them.',
      config: {
        steps: [
          'Input layer receives raw data',
          'Hidden layers process and find patterns',
          'Output layer gives the final answer',
        ],
      },
    },
    keyTakeaways: [
      'Layers are groups of neurons at the same stage.',
      'Data flows: input → hidden → output.',
      'Hidden layers do the real pattern-finding.',
    ],
    commonMistakes: [
      'Thinking the output layer takes in the raw data.',
      'Believing a network can only have one hidden layer.',
      'Assuming hidden layers are unimportant because they’re “hidden”.',
    ],
    summary: 'Neurons are stacked into input, hidden and output layers, with data flowing from one end to the other.',
    prerequisiteLessonIds: ['w3-l1'],
    nextLessonId: 'w3-l3',
  },
  {
    id: 'w3-l3', worldId: W, order: 3,
    title: 'Weights & Biases',
    subtitle: 'The knobs the network tunes',
    difficulty: 'beginner', estimatedMinutes: 7, xp: 60, coins: 8,
    description: 'Inside every connection are numbers called weights and biases. These are the knobs a network turns as it learns.',
    explanation: 'A weight says how important an input is — a big weight means that input matters a lot. A bias shifts the neuron’s result up or down. Learning is nothing more than tuning these numbers until the answers improve.',
    realWorld: 'Imagine a mixing desk: each input sits on its own volume knob (weight), and a master slider nudges the whole mix (bias). Learning is finding the right settings.',
    objectives: [
      'Define weights and biases in simple terms',
      'Explain how weight size affects an input',
      'Connect learning to tuning weights and biases',
    ],
    activity: {
      kind: 'slider',
      title: 'Turn Up the Weight',
      instructions: 'Slide to change an input’s weight and see how much it affects the neuron’s output.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Weight strength',
        stops: [
          { upTo: 5, title: 'Near zero', detail: 'The input is basically ignored — a whisper the neuron can’t hear.' },
          { upTo: 40, title: 'Small', detail: 'The input has a mild effect on the output.' },
          { upTo: 75, title: 'Large', detail: 'The input now strongly shapes the neuron’s decision.' },
          { upTo: 100, title: 'Very large', detail: 'This input dominates — it drives the output almost by itself.' },
        ],
      },
    },
    keyTakeaways: [
      'Weights set how important each input is.',
      'Bias shifts the result up or down.',
      'Learning = adjusting weights and biases automatically.',
    ],
    commonMistakes: [
      'Thinking programmers set weights by hand.',
      'Believing a near-zero weight is the most important one.',
      'Confusing bias here with real-world unfair “bias”.',
    ],
    summary: 'Weights decide how much each input matters and biases shift the result — and learning tunes them both.',
    prerequisiteLessonIds: ['w3-l2'],
    nextLessonId: 'w3-l4',
  },
  {
    id: 'w3-l4', worldId: W, order: 4,
    title: 'Activation Functions',
    subtitle: 'Deciding whether a neuron fires',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'After a neuron combines its inputs, one more step decides how strongly it “fires” — and it’s what lets networks learn complex patterns.',
    explanation: 'An activation function takes the neuron’s combined value and decides how much signal to pass on — whether it “fires”. It also adds non-linearity, which lets networks learn curved, complex patterns instead of just straight lines.',
    realWorld: 'Think of a gatekeeper at a door: they look at how strong the signal is and decide how much to let through. Weak signal, little passes; strong signal, lots passes.',
    objectives: [
      'Explain what an activation function decides',
      'Describe non-linearity in plain words',
      'Explain why activations are essential, not optional',
    ],
    activity: {
      kind: 'slider',
      title: 'Cross the Threshold',
      instructions: 'Slide the incoming signal strength and watch whether the neuron fires.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Signal strength',
        stops: [
          { upTo: 20, title: 'Too weak', detail: 'Below the threshold — the neuron stays quiet and passes almost nothing.' },
          { upTo: 50, title: 'Building up', detail: 'Getting close — a little signal starts to leak through.' },
          { upTo: 80, title: 'Firing', detail: 'The threshold is crossed — the neuron fires and passes the signal on.' },
          { upTo: 100, title: 'Full strength', detail: 'A strong signal fires the neuron fully to the next layer.' },
        ],
      },
    },
    keyTakeaways: [
      'Activation functions decide how strongly a neuron fires.',
      'They add non-linearity, so networks learn curved patterns.',
      'Without them, deep networks collapse to one straight line.',
    ],
    commonMistakes: [
      'Thinking activation functions are an optional extra.',
      'Believing networks without them can still learn complex patterns.',
      'Assuming “firing” means physical electricity, not math.',
    ],
    summary: 'An activation function shapes a neuron’s output and adds the non-linearity that lets networks learn complex patterns.',
    prerequisiteLessonIds: ['w3-l3'],
    nextLessonId: 'w3-l5',
  },
  {
    id: 'w3-l5', worldId: W, order: 5,
    title: 'How a Network Learns',
    subtitle: 'Guess, check the error, adjust',
    difficulty: 'intermediate', estimatedMinutes: 8, xp: 70, coins: 10,
    description: 'A network learns by guessing, seeing how wrong it was, and adjusting — a loop of forward pass, error and backpropagation.',
    explanation: 'First the forward pass: inputs flow through the network to make a guess. Then the error measures how far the guess was from the truth. Then backpropagation sends that error backward to adjust the weights. Repeat many times and the network gets better.',
    realWorld: 'It’s like a student doing practice questions: attempt an answer, check it against the key, see the mistake, and adjust — again and again until they’ve got it.',
    objectives: [
      'Describe the forward pass and error',
      'Explain backpropagation in plain words',
      'See why learning takes many repetitions',
    ],
    activity: {
      kind: 'steps',
      title: 'The Learning Loop',
      instructions: 'Put the steps of how a network learns in the correct order.',
      config: {
        steps: [
          'Forward pass: the network makes a guess',
          'Compare the guess to the correct answer',
          'Measure the error',
          'Backpropagate the error through the layers',
          'Adjust the weights',
          'Repeat many times',
        ],
      },
    },
    keyTakeaways: [
      'Forward pass makes a guess; error measures the miss.',
      'Backpropagation sends the error back to fix weights.',
      'Learning takes many rounds of guess-check-adjust.',
    ],
    commonMistakes: [
      'Thinking a network learns perfectly in one round.',
      'Believing mistakes are ignored rather than used to learn.',
      'Confusing the forward pass with backpropagation.',
    ],
    summary: 'A network learns by guessing, measuring its error, and using backpropagation to adjust its weights, over and over.',
    prerequisiteLessonIds: ['w3-l4'],
    nextLessonId: 'w3-l6',
  },
  {
    id: 'w3-l6', worldId: W, order: 6,
    title: 'Deep Learning: Why “Deep”?',
    subtitle: 'Many layers, richer patterns',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Add many layers and a network can learn far richer patterns. That depth is what unlocked modern AI.',
    explanation: '“Deep” just means many hidden layers stacked together. Early layers spot simple features like edges, and later layers combine them into complex ones like whole objects. With enough data and computing power, that depth lets networks learn patterns shallow methods never could.',
    realWorld: 'It’s like building understanding in stages: first you notice lines, then shapes, then faces. Each layer builds on what the one before it found.',
    objectives: [
      'Explain what “deep” means in deep learning',
      'Describe how layers build up from simple to complex',
      'Explain why depth unlocked modern AI',
    ],
    activity: {
      kind: 'bucket',
      title: 'Shallow or Deep?',
      instructions: 'Sort each statement into whether it describes shallow or deep networks.',
      config: {
        buckets: ['Shallow network', 'Deep network'],
        items: [
          { label: 'Few layers', bucket: 0 },
          { label: 'Learns simpler patterns', bucket: 0 },
          { label: 'Needs less data and compute', bucket: 0 },
          { label: 'Many hidden layers', bucket: 1 },
          { label: 'Learns rich, complex patterns', bucket: 1 },
          { label: 'Powers modern AI systems', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      '“Deep” means many stacked hidden layers.',
      'Layers build up: simple features to complex ones.',
      'Depth plus data and compute unlocked modern AI.',
    ],
    commonMistakes: [
      'Thinking “deep” means slow or dark, not many layers.',
      'Believing more layers is always better with no downsides.',
      'Assuming deep networks need no data to train.',
    ],
    summary: 'Deep learning stacks many layers so networks build up rich patterns — the key that unlocked modern AI.',
    prerequisiteLessonIds: ['w3-l5'],
    nextLessonId: 'w4-l1',
  },
];

export const WORLD3_QUESTIONS: Question[] = [
  ...w3l1Q, ...w3l2Q, ...w3l3Q,
  ...w3l4Q, ...w3l5Q, ...w3l6Q,
];
