import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 4 — Transformers. Full lessons + question bank.
 * Structure mirrors world1.ts (the reference template).
 */

const W = 'world-transformers';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — Before Transformers: The Memory Problem
 * ================================================================== */
const l1 = bank('w4-l1', 'beginner');
const w4l1Q: Question[] = [
  l1.mc('old-models', 'How did older language models read a sentence?',
    ['One word at a time, in order, from start to finish',
     'All words at once, instantly',
     'Backwards, from the last word',
     'They didn’t read words at all'],
    0, 'Older models (like RNNs) processed text word by word in sequence, passing along a running “memory” as they went.'),
  l1.tf('forgetting', 'Older word-by-word models could forget information from the start of a long sentence.', true,
    'As the sentence got longer, early details faded from the running memory — the classic “long-range” forgetting problem.'),
  l1.mc('why-limiting', 'Why was reading word-by-word limiting?',
    ['Important context from far back got lost by the time it was needed',
     'It used too many colours',
     'It could only read numbers',
     'It needed the internet'],
    0, 'If the key word was 30 words ago, a fading memory often lost it — hurting understanding of long text.'),
  l1.mc('slow', 'Reading strictly one word at a time also made models…',
    ['Slow, because each word had to wait for the one before it',
     'Faster than any other method',
     'Unable to use electricity',
     'Better at maths'],
    0, 'Sequential reading can’t be done in parallel — every step waits for the previous, which is slow on modern hardware.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Sequential', right: 'Reading one word after another, in order' },
     { left: 'Memory', right: 'What the model carries forward as it reads' },
     { left: 'Forgetting', right: 'Losing early details in a long sentence' }],
    'Sequential models carried a memory forward, but that memory faded — causing forgetting on long inputs.'),
  l1.tf('short-ok', 'For very short sentences, older models worked fairly well.', true,
    'With little to remember, the memory didn’t fade much — the trouble grew as sentences got longer.'),
  l1.mc('example-scenario', 'Reading “The trophy didn’t fit in the suitcase because it was too big,” an old model may struggle to link “it” to…',
    ['“trophy” — that link sits several words back and can fade',
     'the colour of the suitcase',
     'the current time',
     'the size of the screen'],
    0, 'Connecting “it” to the right earlier word is exactly the long-range link that fading memory made hard.', 'scenario'),
  l1.mc('bottleneck', 'The single running “memory” in old models acted like a…',
    ['Narrow funnel that everything had to squeeze through',
     'Wide open highway',
     'Bright light',
     'Loud speaker'],
    0, 'Cramming a whole sentence’s meaning into one small memory was a bottleneck — details got squeezed out.'),
  l1.tf('sequence-parallel', 'Word-by-word reading can easily be split across many processors at once.', false,
    'It can’t — each step depends on the last. This inability to parallelise was a big practical limitation.'),
  l1.mc('motivation', 'These problems set the stage for…',
    ['A new design that reads whole sentences at once and links any two words directly',
     'Removing computers entirely',
     'Making text shorter forever',
     'Only ever using short words'],
    0, 'The Transformer was invented to fix exactly these issues — long-range links and slow sequential reading.'),
  l1.mc('summary-idea', 'The core weakness of pre-Transformer models was…',
    ['Struggling to remember and connect distant words',
     'Being too accurate',
     'Using no data',
     'Reading too many words at once'],
    0, 'Fading memory over distance, plus slow sequential processing, were the weaknesses Transformers set out to solve.'),
  l1.tf('goal', 'Understanding this “memory problem” helps explain why Transformers were invented.', true,
    'Every clever part of a Transformer is a direct answer to the forgetting and slowness of older models.'),
];

/* ================================================================== *
 * Lesson 2 — Tokens: The Pieces a Model Reads
 * ================================================================== */
const l2 = bank('w4-l2', 'beginner');
const w4l2Q: Question[] = [
  l2.mc('what-token', 'What is a “token” in a language model?',
    ['A small piece of text — a word, part of a word, or a symbol',
     'A physical coin',
     'A full paragraph, always',
     'A single letter, always'],
    0, 'Text is chopped into tokens. A token is often a word or a word-piece — the unit the model actually reads.'),
  l2.tf('not-always-word', 'A token is always exactly one whole word.', false,
    'Not always. Long or rare words get split into pieces, and spaces or punctuation can be tokens too.'),
  l2.mc('why-split', 'Why is text split into tokens before the model reads it?',
    ['Models work on fixed-size pieces, not raw free-flowing text',
     'To make the text look prettier',
     'To delete the vowels',
     'To translate it to French'],
    0, 'Tokenising turns messy text into a tidy sequence of units the model can turn into numbers and process.'),
  l2.mc('subword', 'The word “unbelievable” might become tokens like…',
    ['“un”, “believ”, “able” — word-pieces',
     'a single emoji',
     'the number 42',
     'one token per letter, always'],
    0, 'Splitting into reusable pieces lets a model handle rare or new words from parts it already knows.'),
  l2.match('vocab', 'Match each term to its meaning.',
    [{ left: 'Token', right: 'A small piece of text the model reads' },
     { left: 'Tokeniser', right: 'The tool that splits text into tokens' },
     { left: 'Vocabulary', right: 'The full set of tokens a model knows' }],
    'A tokeniser splits text into tokens, all drawn from the model’s fixed vocabulary.'),
  l2.tf('numbers', 'Each token is turned into a number so the model can process it.', true,
    'Models do maths, not letters. Every token maps to a number (an ID) before the real work begins.'),
  l2.mc('count-scenario', 'A short phrase can be several tokens. “I love AI!” is closest to…',
    ['Around 4 tokens — words plus the “!” can each count',
     'Exactly 1 token',
     'Exactly 100 tokens',
     'Zero tokens'],
    0, 'Words and punctuation each tend to be their own token, so a few words easily add up to several tokens.', 'scenario'),
  l2.mc('rare-words', 'Splitting into word-pieces helps most with…',
    ['Rare, long or made-up words the model hasn’t seen whole',
     'Only the word “the”',
     'Numbers only',
     'Nothing at all'],
    0, 'A model can build an unfamiliar word from familiar pieces, instead of failing on it entirely.'),
  l2.tf('spaces', 'Spaces and punctuation can be part of tokens too.', true,
    'Tokenisers often attach or separate spaces and punctuation — they’re part of how text is chopped up.'),
  l2.mc('limits', 'Why do models have a “token limit”?',
    ['They can only read a fixed number of tokens at once',
     'Tokens cost real money to print',
     'Tokens run out at night',
     'The screen is too small'],
    0, 'A model’s context window is measured in tokens — go over the limit and the extra text won’t fit.'),
  l2.mc('order', 'The correct flow when a model reads text is…',
    ['Text → split into tokens → turn into numbers → process',
     'Numbers → tokens → text → delete',
     'Process → tokens → text → numbers',
     'Text → process → tokens'],
    0, 'First split the text into tokens, then convert those tokens to numbers, and only then does the model process them.'),
  l2.tf('foundation', 'Tokens are the basic building blocks a Transformer works with.', true,
    'Everything a Transformer does starts from tokens — get the tokens, and the rest of the pipeline can begin.'),
];

/* ================================================================== *
 * Lesson 3 — Attention: Focusing on What Matters
 * ================================================================== */
const l3 = bank('w4-l3', 'intermediate');
const w4l3Q: Question[] = [
  l3.mc('core-idea', 'What is “attention” in a Transformer, in plain words?',
    ['A way for the model to focus on the words that matter most for each word',
     'A way to make the screen brighter',
     'A timer that counts down',
     'A tool that deletes words'],
    0, 'Attention lets each word “look at” and weigh the other words, focusing on the ones that give it meaning.'),
  l3.tf('all-equal', 'With attention, every word matters equally for understanding a given word.', false,
    'The whole point is that they don’t. Attention gives more weight to the relevant words and less to the rest.'),
  l3.mc('pronoun', 'In “The dog chased the ball because it was fast,” attention helps link “it” to…',
    ['the most relevant earlier word (here, likely “dog”)',
     'the last word only',
     'a random word',
     'nothing at all'],
    0, 'Attention lets “it” focus on the word that gives it meaning, connecting distant, related words directly.', 'scenario'),
  l3.mc('vs-old', 'How is attention better than the old fading memory?',
    ['Any word can look directly at any other, no matter how far apart',
     'It reads fewer words',
     'It never uses data',
     'It ignores context entirely'],
    0, 'No more relay of fading memory — attention makes a direct link between any two words, near or far.'),
  l3.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Attention', right: 'Focusing on the most relevant words' },
     { left: 'Weight', right: 'How much focus one word gives another' },
     { left: 'Context', right: 'Meaning built from surrounding words' }],
    'Attention assigns weights that decide how much each word contributes to another’s context.'),
  l3.tf('distance', 'Attention can connect two words even if they’re far apart in a sentence.', true,
    'Distance no longer matters — attention links any two words directly, which older models struggled to do.'),
  l3.mc('weights', 'The “attention weights” tell the model…',
    ['How much each word should focus on each other word',
     'What colour to use',
     'How loud to be',
     'When to shut down'],
    0, 'Higher weight means “pay more attention here”. These weights are how the model decides what’s relevant.'),
  l3.mc('bank-scenario', 'To read “river bank” vs “money bank,” attention lets “bank” focus on…',
    ['nearby words like “river” or “money” to pick the right meaning',
     'the first word of the book',
     'a random letter',
     'the file size'],
    0, 'Attention uses context — the surrounding words — to resolve which meaning of an ambiguous word applies.', 'scenario'),
  l3.tf('spotlight', 'Attention is like a spotlight that highlights the words that matter for each word.', true,
    'That spotlight analogy is spot on — attention brightens the relevant words and dims the rest.'),
  l3.mc('why-powerful', 'Attention is powerful mainly because it…',
    ['Builds rich context by directly relating words to each other',
     'Makes text shorter',
     'Removes the need for tokens',
     'Uses no maths'],
    0, 'By letting words relate directly, attention builds a much richer understanding of how a sentence fits together.'),
  l3.mc('summary', 'The one-line idea of attention is…',
    ['Each word decides which other words to focus on',
     'Every word is ignored',
     'Only the first word matters',
     'Words are read backwards'],
    0, 'Attention = each word choosing where to focus, so meaning comes from the right neighbours.'),
  l3.tf('foundation', 'Attention is the core idea that makes Transformers work.', true,
    'It’s the heart of the Transformer — the mechanism everything else is built around.'),
];

/* ================================================================== *
 * Lesson 4 — Self-Attention Explained Simply
 * ================================================================== */
const l4 = bank('w4-l4', 'intermediate');
const w4l4Q: Question[] = [
  l4.mc('what', 'What does “self-attention” mean?',
    ['Every word in a sentence looks at every other word to build context',
     'The model looks only at itself and no words',
     'Words look only at the next word',
     'The model ignores the sentence'],
    0, 'In self-attention, each word attends to all the words in the same sentence — including itself — to gather meaning.'),
  l4.tf('every-word', 'In self-attention, each word can look at every other word in the sentence.', true,
    'Yes — it’s an all-to-all comparison, so every word gathers context from the whole sentence at once.'),
  l4.mc('self', 'Why is it called “self”-attention?',
    ['The words attend to other words within the same sequence',
     'The model attends to a different document',
     'It only ever uses one word',
     'It looks at the user’s face'],
    0, '“Self” means the sentence attends to itself — words relate to other words in the very same input.'),
  l4.order('steps', 'Put the simple self-attention steps in order.',
    ['Each word compares itself to every other word',
     'Work out how relevant each other word is (weights)',
     'Blend the words together using those weights',
     'Each word gets a new, context-rich meaning'],
    'Compare → score relevance → blend by weight → each word ends up richer with context from the whole sentence.'),
  l4.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Self-attention', right: 'Words attend to words in the same sentence' },
     { left: 'All-to-all', right: 'Every word compared with every other' },
     { left: 'Context-rich', right: 'A word’s meaning shaped by its neighbours' }],
    'Self-attention is all-to-all comparison that leaves every word context-rich.'),
  l4.tf('parallel', 'Self-attention can compare all the words at the same time, in parallel.', true,
    'Because it’s not a step-by-step relay, all comparisons happen at once — which is fast on modern hardware.'),
  l4.mc('meaning-scenario', 'After self-attention, the word “bank” in “sat by the river bank” carries…',
    ['a meaning shaped by “river” — the water-edge sense',
     'no meaning at all',
     'the meaning of a money bank',
     'a random number'],
    0, 'Self-attention blends in context, so “bank” absorbs the “river” hint and settles on the right meaning.', 'scenario'),
  l4.mc('vs-plain', 'How does self-attention differ from reading in order?',
    ['It relates all words at once, not in a one-by-one chain',
     'It reads only the last word',
     'It uses no words',
     'It is always slower'],
    0, 'Instead of a sequential chain, every word sees every other word simultaneously — richer and more parallel.'),
  l4.tf('itself', 'A word can even attend to itself during self-attention.', true,
    'Yes — a word’s own information is part of the mix, alongside the context from its neighbours.'),
  l4.mc('result', 'The result of self-attention for each word is…',
    ['A new representation that includes context from the whole sentence',
     'The word deleted',
     'The word turned into an image',
     'The exact same word, unchanged'],
    0, 'Each word comes out enriched — its new form encodes how it relates to everything around it.'),
  l4.mc('why-matters', 'Self-attention matters because it…',
    ['Lets the model understand how words relate across the whole input',
     'Makes the text shorter',
     'Removes punctuation',
     'Uses less data than any method'],
    0, 'Understanding relationships between all words is what gives Transformers their strong grasp of language.'),
  l4.tf('foundation', 'Self-attention is the specific mechanism inside a Transformer that applies attention within a sentence.', true,
    'It’s attention turned inward on the input itself — the workhorse operation of every Transformer layer.'),
];

/* ================================================================== *
 * Lesson 5 — Multi-Head Attention & Layers
 * ================================================================== */
const l5 = bank('w4-l5', 'advanced');
const w4l5Q: Question[] = [
  l5.mc('multi-head', 'What is “multi-head” attention?',
    ['Running attention several times in parallel, each with a different focus',
     'One giant attention with no focus',
     'Attention that reads only one word',
     'A screen with many colours'],
    0, 'Each “head” attends in its own way — one might track grammar, another meaning — and their views are combined.'),
  l5.tf('one-view', 'A single attention head can capture every kind of relationship at once.', false,
    'One head has one perspective. Using many heads lets the model track several kinds of relationships together.'),
  l5.mc('why-heads', 'Why use many attention heads instead of one?',
    ['Different heads can capture different relationships (grammar, meaning, position)',
     'To use more electricity for fun',
     'To make text longer',
     'Heads are just decoration'],
    0, 'Multiple heads give multiple “views” of the sentence, so the model catches more kinds of connections.'),
  l5.mc('layers', 'What does stacking many Transformer “layers” do?',
    ['Each layer builds on the last, forming deeper, richer understanding',
     'It makes the model forget everything',
     'It removes all the tokens',
     'It only changes the colour'],
    0, 'Early layers catch simple patterns; deeper layers combine them into higher-level meaning — depth adds power.'),
  l5.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Head', right: 'One attention “view” with its own focus' },
     { left: 'Multi-head', right: 'Several heads running in parallel' },
     { left: 'Layer', right: 'A stack level that builds on the one below' }],
    'Multi-head means several heads per layer; stacking many layers builds understanding step by step.'),
  l5.tf('deeper', 'Generally, more layers and heads let a model capture more complex patterns.', true,
    'More heads catch more relationships per layer; more layers build deeper meaning — up to a point.'),
  l5.mc('views-scenario', 'In one sentence, different heads might separately track…',
    ['who did the action, and which word a pronoun refers to',
     'the phone’s battery level',
     'the room temperature',
     'the file’s colour'],
    0, 'Each head can specialise — one on subject–verb links, another on pronouns — giving a fuller picture together.', 'scenario'),
  l5.mc('combine', 'After the heads each attend, their results are…',
    ['Combined into one richer representation',
     'Thrown away',
     'Kept forever separate and unused',
     'Printed on paper'],
    0, 'The heads’ different views are merged, so the next layer gets one representation that blends all their focuses.'),
  l5.tf('cost', 'More heads and layers usually cost more computing power.', true,
    'Depth and width aren’t free — bigger models need more compute and data, a real trade-off in practice.'),
  l5.mc('stack-order', 'Information flows through a stack of layers by…',
    ['Passing from one layer up to the next, getting richer each time',
     'Skipping every layer',
     'Going only downward',
     'Staying in one layer forever'],
    0, 'Each layer refines the output of the one below, so understanding deepens as data climbs the stack.'),
  l5.mc('why-matters', 'Multi-head attention and layers together give a Transformer…',
    ['The ability to understand rich, complex relationships in text',
     'A smaller vocabulary',
     'Fewer tokens to read',
     'The need for no data'],
    0, 'Many views (heads) across many levels (layers) is what lets Transformers model language so richly.'),
  l5.tf('foundation', 'Heads add breadth of focus; layers add depth of understanding.', true,
    'A neat way to remember it: heads spread out, layers build up — together they make the model powerful.'),
];

/* ================================================================== *
 * Lesson 6 — Putting It Together: The Transformer
 * ================================================================== */
const l6 = bank('w4-l6', 'advanced');
const w4l6Q: Question[] = [
  l6.mc('whole-sentence', 'A key advantage of the Transformer is that it…',
    ['Reads a whole sentence at once instead of one word at a time',
     'Reads only the last word',
     'Reads nothing until told to',
     'Reads text backwards only'],
    0, 'By using attention over all tokens together, a Transformer takes in the whole input at once — fast and context-rich.'),
  l6.order('pipeline', 'Put the Transformer pipeline in order.',
    ['Split text into tokens',
     'Turn tokens into numbers',
     'Apply self-attention across all tokens',
     'Pass through stacked layers',
     'Produce an output (like the next word)'],
    'Tokenise → numbers → self-attention → stacked layers → output. That’s the full Transformer flow, end to end.'),
  l6.tf('parallel', 'Reading all tokens at once lets Transformers use hardware in parallel and train faster.', true,
    'No sequential bottleneck means the work splits across many processors — a big reason Transformers scaled up so well.'),
  l6.mc('scale', 'Why could Transformers be “scaled up” so much?',
    ['Their parallel design trains efficiently on huge data and big hardware',
     'They use less data than anything else',
     'They need no computers',
     'They only work on tiny text'],
    0, 'Parallelism plus attention meant bigger models on more data kept getting better — enabling today’s large models.'),
  l6.match('recap', 'Match each Transformer part to its job.',
    [{ left: 'Tokens', right: 'The pieces of text the model reads' },
     { left: 'Self-attention', right: 'Relates every word to every other' },
     { left: 'Layers', right: 'Build deeper understanding, step by step' }],
    'Tokens are the input, self-attention relates them, and stacked layers deepen the understanding.'),
  l6.tf('memory-solved', 'The Transformer fixed the old long-range “forgetting” problem.', true,
    'Attention links any two words directly, so distant context is no longer lost the way it was in older models.'),
  l6.mc('powers-scenario', 'When a modern chatbot keeps track of a long conversation, it’s largely thanks to…',
    ['attention over many tokens, the Transformer’s core mechanism',
     'a bigger screen',
     'a faster battery',
     'reading one word at a time'],
    0, 'Attention lets the model relate far-apart parts of a long input — exactly what long conversations need.', 'scenario'),
  l6.mc('same-idea', 'Large modern language models are mostly built from…',
    ['scaled-up Transformers',
     'old fading-memory models',
     'plain calculators',
     'hand-written rules only'],
    0, 'Today’s big models are Transformers made larger — same core design, much more scale.'),
  l6.tf('not-magic', 'Even a huge Transformer is still tokens, attention and layers — not magic.', true,
    'Scale changes the size, not the ingredients. Under the hood it’s the same pipeline you just learned.'),
  l6.mc('why-revolution', 'The Transformer was revolutionary because it…',
    ['Solved forgetting AND enabled fast, parallel, large-scale training',
     'Made text shorter',
     'Removed the need for data',
     'Only worked on short phrases'],
    0, 'Fixing long-range memory and unlocking parallel scale together sparked the modern era of AI language models.'),
  l6.mc('summary', 'In one line, a Transformer is…',
    ['A model that reads tokens all at once and uses attention to relate them',
     'A model that reads one word and forgets the rest',
     'A calculator with a screen',
     'A set of hand-written rules'],
    0, 'Tokens in, attention relating them all, layers deepening meaning, output out — that’s the Transformer.'),
  l6.tf('foundation', 'Understanding tokens, attention and layers means you understand the heart of modern AI.', true,
    'These three ideas are the foundation every large language model is built on — you now know how they fit together.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD4_LESSONS: Lesson[] = [
  {
    id: 'w4-l1', worldId: W, order: 1,
    title: 'Before Transformers: The Memory Problem',
    subtitle: 'Why older models forgot',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'Before Transformers, models read text one word at a time and carried a small “memory” along — which faded on long sentences.',
    explanation: 'Older language models processed a sentence word by word, passing a running memory forward. On long text, early details faded before they were needed. Reading one word at a time was also slow, because each step had to wait for the one before. These weaknesses are exactly what the Transformer was built to fix.',
    realWorld: 'Imagine whispering a long message down a line of people. By the end, the first words are muddled or lost — that’s the old model’s fading memory.',
    objectives: [
      'Explain how older models read text',
      'Describe the long-range “forgetting” problem',
      'See why sequential reading was slow',
    ],
    activity: {
      kind: 'sequence',
      title: 'Watch the Memory Fade',
      instructions: 'An old model reads one word at a time. Which early detail is it most likely to have forgotten by the end?',
      config: {
        shown: ['The', 'scientist', 'from', 'Peru', 'who', 'won', 'the', 'prize', 'said', 'she…'],
        options: ['Where the scientist was from', 'The very last word', 'That there was a scientist at all', 'Nothing is ever forgotten'],
        correctIndex: 0,
        reveal: 'The link back to “Peru” and “scientist” sits many words away — exactly the distant detail a fading memory tends to lose.',
      },
    },
    keyTakeaways: [
      'Older models read one word at a time, carrying a running memory.',
      'That memory faded, so distant words got forgotten.',
      'Sequential reading was also slow — each step waited for the last.',
    ],
    commonMistakes: [
      'Thinking old models read whole sentences at once — they didn’t.',
      'Assuming forgetting was a bug; it was a built-in limit of the design.',
    ],
    summary: 'Older models read word-by-word and forgot distant context — the problem Transformers solve.',
    prerequisiteLessonIds: ['w3-l6'],
    nextLessonId: 'w4-l2',
  },
  {
    id: 'w4-l2', worldId: W, order: 2,
    title: 'Tokens: The Pieces a Model Reads',
    subtitle: 'How text is chopped up',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 5,
    description: 'Before a model can read text, it splits it into small pieces called tokens — usually words or word-parts — and turns them into numbers.',
    explanation: 'A model doesn’t read raw text; it reads tokens. A tokeniser chops text into small pieces — whole words, word-parts, or punctuation — all drawn from a fixed vocabulary. Each token is then turned into a number the model can process. Splitting into pieces also lets the model handle rare or new words from parts it already knows.',
    realWorld: 'Think of building words from LEGO bricks. You don’t need a unique brick for every word — you snap together a few reusable pieces. Tokens work the same way.',
    objectives: [
      'Define what a token is',
      'Explain why text is split into tokens',
      'See how word-pieces handle rare words',
    ],
    activity: {
      kind: 'bucket',
      title: 'One Token or Many?',
      instructions: 'Sort each item by how a tokeniser is likely to handle it.',
      config: {
        buckets: ['Usually one token', 'Often split into pieces'],
        items: [
          { label: 'the', bucket: 0 },
          { label: 'cat', bucket: 0 },
          { label: 'run', bucket: 0 },
          { label: 'unbelievability', bucket: 1 },
          { label: 'antidisestablishment', bucket: 1 },
          { label: 'a made-up word like “florbnak”', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'A token is a small piece of text — a word, word-part or symbol.',
      'Tokens are turned into numbers before the model processes them.',
      'Word-pieces let models handle rare and new words.',
    ],
    commonMistakes: [
      'Believing every token is exactly one whole word.',
      'Forgetting that punctuation and spaces can be tokens too.',
    ],
    summary: 'Text is split into tokens — the numbered pieces a model actually reads.',
    prerequisiteLessonIds: ['w4-l1'],
    nextLessonId: 'w4-l3',
  },
  {
    id: 'w4-l3', worldId: W, order: 3,
    title: 'Attention: Focusing on What Matters',
    subtitle: 'The core idea, in plain words',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Attention lets each word focus on the other words that matter most to it — building meaning from the right neighbours, near or far.',
    explanation: 'Attention is the heart of a Transformer. For each word, it decides how much to focus on every other word, giving more weight to the relevant ones. This lets a model connect distant, related words directly — no more fading memory. Attention is like a spotlight that brightens the words that matter and dims the rest.',
    realWorld: 'Reading “she poured it into the cup,” your eyes flick back to find what “it” means. Attention is that flick — each word looking to the words that give it meaning.',
    objectives: [
      'Explain attention in plain language',
      'See how attention connects distant words',
      'Understand attention weights',
    ],
    activity: {
      kind: 'bucket',
      title: 'Where Should “it” Look?',
      instructions: 'In “The cup fell off the shelf because it was slippery,” sort each word by how much “it” should attend to it.',
      config: {
        buckets: ['High attention', 'Low attention'],
        items: [
          { label: 'shelf', bucket: 0 },
          { label: 'slippery', bucket: 0 },
          { label: 'because', bucket: 1 },
          { label: 'off', bucket: 1 },
          { label: 'the', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Attention lets each word focus on the words that matter most.',
      'It links any two words directly, even far apart.',
      'Weights decide how much focus one word gives another.',
    ],
    commonMistakes: [
      'Thinking attention treats all words equally — it deliberately doesn’t.',
      'Assuming only nearby words can be connected.',
    ],
    summary: 'Attention lets each word focus on its most relevant neighbours to build meaning.',
    prerequisiteLessonIds: ['w4-l2'],
    nextLessonId: 'w4-l4',
  },
  {
    id: 'w4-l4', worldId: W, order: 4,
    title: 'Self-Attention Explained Simply',
    subtitle: 'Every word looks at every word',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Self-attention is attention turned inward: every word in a sentence looks at every other word to build rich, shared context.',
    explanation: 'Self-attention means the sentence attends to itself. Each word compares itself to every other word, works out how relevant each one is, and blends them together by those weights. The result is that every word ends up with a new, context-rich meaning shaped by the whole sentence. Because all comparisons happen at once, it’s fast and parallel.',
    realWorld: 'Picture everyone at a round table glancing at everyone else before speaking — each person’s point is shaped by the whole group. Self-attention does that for words.',
    objectives: [
      'Define self-attention',
      'Walk through the all-to-all comparison',
      'See how each word gains context',
    ],
    activity: {
      kind: 'steps',
      title: 'Run Self-Attention',
      instructions: 'Drag the steps into the order self-attention actually happens.',
      config: {
        steps: [
          'Each word compares itself to every other word',
          'Work out how relevant each other word is (weights)',
          'Blend the words together using those weights',
          'Each word gets a new, context-rich meaning',
        ],
      },
    },
    keyTakeaways: [
      'Self-attention = every word attends to every word in the same sentence.',
      'Each word comes out enriched with context from the whole input.',
      'All comparisons happen at once, so it’s parallel and fast.',
    ],
    commonMistakes: [
      'Thinking a word only looks at the next word — it looks at all of them.',
      'Forgetting a word also attends to itself.',
    ],
    summary: 'Self-attention lets every word gather context from every other word at once.',
    prerequisiteLessonIds: ['w4-l3'],
    nextLessonId: 'w4-l5',
  },
  {
    id: 'w4-l5', worldId: W, order: 5,
    title: 'Multi-Head Attention & Layers',
    subtitle: 'Many views, stacked deep',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Transformers run attention many times in parallel (heads) and stack many layers — giving both breadth of focus and depth of understanding.',
    explanation: 'One attention head has one point of view. Multi-head attention runs several heads in parallel, each focusing differently — one on grammar, another on meaning — then combines their views. Stacking these into many layers lets each level build on the last: early layers catch simple patterns, deeper layers form higher-level meaning. Heads add breadth; layers add depth.',
    realWorld: 'Think of a panel of experts reading the same sentence — a grammarian, a translator, a fact-checker. Each notices something different, and together they understand more. That’s multi-head attention.',
    objectives: [
      'Explain what multi-head attention adds',
      'See why multiple heads beat one',
      'Understand how stacked layers deepen understanding',
    ],
    activity: {
      kind: 'slider',
      title: 'Heads, Layers & Power',
      instructions: 'Slide to add more heads and layers. Watch how the model’s understanding — and its cost — grows.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Heads & layers',
        stops: [
          { upTo: 10, title: 'Tiny', detail: 'One head, one layer — it catches only the simplest patterns.' },
          { upTo: 40, title: 'Small', detail: 'A few heads and layers — basic grammar and meaning come through.' },
          { upTo: 75, title: 'Large', detail: 'Many heads and layers — rich, complex relationships are captured.' },
          { upTo: 100, title: 'Huge (costly)', detail: 'Very deep and wide — powerful, but needs lots of data and compute.' },
        ],
      },
    },
    keyTakeaways: [
      'Multi-head = several attention “views” running in parallel.',
      'Different heads capture different kinds of relationships.',
      'Stacked layers build deeper understanding, step by step.',
    ],
    commonMistakes: [
      'Assuming one head can capture every relationship at once.',
      'Thinking more heads and layers are free — they cost compute and data.',
    ],
    summary: 'Many heads add breadth of focus; many layers add depth of understanding.',
    prerequisiteLessonIds: ['w4-l4'],
    nextLessonId: 'w4-l6',
  },
  {
    id: 'w4-l6', worldId: W, order: 6,
    title: 'Putting It Together: The Transformer',
    subtitle: 'The full pipeline, scaled up',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Now assemble the whole thing: tokens in, self-attention relating them all at once, stacked layers deepening meaning, and an output out.',
    explanation: 'A Transformer splits text into tokens, turns them into numbers, applies self-attention across all tokens at once, passes them through stacked layers, and produces an output like the next word. Reading the whole input at once fixed the old forgetting problem and let training run in parallel. That parallel design is why Transformers could be scaled up into today’s huge language models.',
    realWorld: 'It’s like reading a whole page at a glance instead of one word through a keyhole — you see how everything connects, and you can do it fast.',
    objectives: [
      'Trace the full Transformer pipeline',
      'Explain why reading whole sentences at once helps',
      'See why Transformers scaled up so well',
    ],
    activity: {
      kind: 'steps',
      title: 'Assemble the Transformer',
      instructions: 'Drag the stages into the order text flows through a Transformer.',
      config: {
        steps: [
          'Split text into tokens',
          'Turn tokens into numbers',
          'Apply self-attention across all tokens',
          'Pass through stacked layers',
          'Produce an output (like the next word)',
        ],
      },
    },
    keyTakeaways: [
      'Transformers read all tokens at once using attention.',
      'That fixed forgetting and enabled fast, parallel training.',
      'Scaling this same design up gave us today’s large language models.',
    ],
    commonMistakes: [
      'Thinking big models use a different design — they’re scaled-up Transformers.',
      'Believing scale is “magic” — it’s the same tokens, attention and layers, just bigger.',
    ],
    summary: 'A Transformer reads tokens all at once, relates them with attention, and scales up to power modern AI.',
    prerequisiteLessonIds: ['w4-l5'],
    nextLessonId: 'w5-l1',
  },
];

export const WORLD4_QUESTIONS: Question[] = [
  ...w4l1Q, ...w4l2Q, ...w4l3Q,
  ...w4l4Q, ...w4l5Q, ...w4l6Q,
];
