import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 5 — Large Language Models. Full lessons + question bank.
 * Structure mirrors world1.ts (the reference template).
 */

const W = 'world-llms';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — What Is a Large Language Model?
 * ================================================================== */
const l1 = bank('w5-l1', 'beginner');
const w5l1Q: Question[] = [
  l1.mc('definition', 'What is a Large Language Model (LLM)?',
    ['An AI trained on huge amounts of text to understand and produce language',
     'A dictionary stored on your phone',
     'A very fast spell-checker',
     'A robot that reads books aloud'],
    0, 'An LLM learns patterns from an enormous pile of text, then uses them to read and write language.'),
  l1.tf('scope', 'An LLM is basically just a big lookup table of memorised answers.', false,
    'It doesn’t store answers to copy back. It learns patterns from text and generates fresh responses each time.'),
  l1.mc('large', 'What does the “large” in Large Language Model mostly refer to?',
    ['A huge amount of training text and a very big model',
     'A physically large computer screen',
     'Long sentences only',
     'A large price tag'],
    0, '“Large” means it learned from a massive amount of text and has a very large number of internal settings.'),
  l1.mc('trained-on', 'LLMs learn their skills from…',
    ['Reading vast amounts of human-written text',
     'A single instruction manual',
     'Watching television',
     'Being hand-coded rule by rule'],
    0, 'They soak up patterns from books, articles and web pages — far more text than any human could read.'),
  l1.tf('language', 'LLMs are designed mainly to work with language — reading and writing text.', true,
    'The clue is in the name. Their core job is understanding and generating human language.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'LLM', right: 'AI trained on lots of text to handle language' },
     { left: 'Training data', right: 'The text the model learned from' },
     { left: '“Large”', right: 'Huge data and a very big model' }],
    'An LLM is the model, training data is what it read, and “large” describes its scale.'),
  l1.mc('what-it-does', 'Which task is an LLM naturally good at?',
    ['Writing an email or answering a question in words',
     'Charging your phone battery',
     'Physically lifting boxes',
     'Measuring the temperature of a room'],
    0, 'Language tasks — writing, summarising, answering — are exactly what an LLM is built for.'),
  l1.tf('understand', 'An LLM truly understands language the same way a human does.', false,
    'It’s extremely good at predicting patterns in language, but it doesn’t understand meaning the way people do.'),
  l1.mc('chatbot', 'A chatbot that answers your questions in fluent sentences is powered by…',
    ['A large language model',
     'A calculator',
     'A weather sensor',
     'A printed encyclopedia'],
    0, 'Fluent, flexible text responses are the signature of an LLM at work.'),
  l1.mc('scenario-help', 'You ask an app to “rewrite this message to sound friendlier” and it does. This is…',
    ['An LLM reshaping your text based on language patterns it learned',
     'A human editor replying instantly',
     'Random word shuffling',
     'A spell-checker only'],
    0, 'Rewriting text while keeping the meaning is a classic LLM language task.', 'scenario'),
  l1.tf('scale', 'Training on far more text generally helps an LLM handle language better.', true,
    'More varied text means more patterns learned, which usually makes the model more capable — up to a point.'),
  l1.mc('misconception', 'Which statement about LLMs is TRUE?',
    ['They generate language by predicting likely patterns, not by looking up stored answers',
     'They always tell the truth',
     'They store every webpage word-for-word',
     'They think and feel like people'],
    0, 'An LLM is a powerful pattern-predictor for language — not a truth machine, a database, or a mind.'),
];

/* ================================================================== *
 * Lesson 2 — Predicting the Next Token
 * ================================================================== */
const l2 = bank('w5-l2', 'beginner');
const w5l2Q: Question[] = [
  l2.mc('core-idea', 'At its heart, how does an LLM generate text?',
    ['It predicts the next small piece (token) one at a time',
     'It writes the whole answer at once from memory',
     'It copies a saved paragraph',
     'It asks a human what to type'],
    0, 'An LLM builds text step by step, repeatedly predicting the most likely next token.'),
  l2.mc('token', 'A “token” is best described as…',
    ['A small chunk of text — often a word or part of a word',
     'A coin you pay to use AI',
     'A complete essay',
     'A single letter only, always'],
    0, 'Tokens are the little pieces an LLM reads and writes — usually a word or a fragment of one.'),
  l2.order('loop', 'Put the text-generation loop in the right order.',
    ['Read the text so far', 'Predict the most likely next token', 'Add that token to the text', 'Repeat until the answer is complete'],
    'Read → predict → add → repeat. One token at a time, the sentence grows.'),
  l2.tf('one-at-a-time', 'An LLM produces its answer one token at a time.', true,
    'Each new token is predicted from everything written so far, then the process repeats.'),
  l2.mc('predict-what', 'When predicting the next token, the model chooses based on…',
    ['What’s most likely to come next given the text so far',
     'The current time of day',
     'The colour of your screen',
     'A coin flip with no patterns'],
    0, 'It uses patterns learned from training to estimate which token most naturally follows.'),
  l2.mc('autocomplete', 'Predicting the next token is a lot like…',
    ['Phone autocomplete guessing your next word — but far more powerful',
     'A calculator adding numbers',
     'A light switch',
     'A printed map'],
    0, 'Autocomplete is the same basic idea: guess what comes next. An LLM does it with much richer patterns.'),
  l2.tf('whole-plan', 'An LLM plans the entire final sentence before writing any of it.', false,
    'It doesn’t write the whole thing upfront — it decides each token in turn as it goes.'),
  l2.match('terms', 'Match the term to its meaning.',
    [{ left: 'Token', right: 'A small chunk of text' },
     { left: 'Prediction', right: 'The model’s guess at the next token' },
     { left: 'Generation', right: 'Building text token by token' }],
    'Tokens are the pieces, prediction is the guess, and generation is stringing guesses together.'),
  l2.mc('why-tokens', 'Why break text into tokens instead of whole sentences?',
    ['Small, reusable pieces make prediction manageable and flexible',
     'Sentences are illegal to store',
     'Tokens use no memory at all',
     'It makes the text longer on purpose'],
    0, 'Working in small pieces lets the model handle any wording by combining familiar chunks.'),
  l2.tf('context-matters', 'The words already written affect which token comes next.', true,
    'Each prediction depends on the text so far — that’s how the output stays on topic and coherent.'),
  l2.mc('scenario-sentence', 'The model has written “The sky is” and must pick the next token. It most likely chooses…',
    ['“blue” — a highly likely continuation it learned from text',
     'A random unrelated word',
     'A number like 7',
     'Nothing — it stops guessing'],
    0, 'From patterns in its training, “blue” is a very likely next token after “The sky is”.', 'scenario'),
  l2.mc('coherence', 'Generating one token at a time still produces coherent text because…',
    ['Every new token is chosen to fit everything written before it',
     'The model erases its earlier words each step',
     'It ignores the previous words',
     'Coherence is impossible this way'],
    0, 'Each token builds on the growing text, so the sentence stays consistent and on-topic.'),
];

/* ================================================================== *
 * Lesson 3 — The Context Window
 * ================================================================== */
const l3 = bank('w5-l3', 'intermediate');
const w5l3Q: Question[] = [
  l3.mc('definition', 'What is the “context window” of an LLM?',
    ['The amount of text it can pay attention to at once',
     'A pop-up help menu',
     'The screen size of the app',
     'The time the model runs each day'],
    0, 'The context window is how much text — your prompt plus its reply — the model can hold in view at one time.'),
  l3.mc('analogy', 'The context window works most like…',
    ['Short-term memory — only so much fits at once',
     'A permanent hard drive that never forgets',
     'A camera lens',
     'A battery'],
    0, 'It behaves like short-term memory: useful while active, but limited in how much it can hold.'),
  l3.tf('limit', 'The context window has a limit on how much text fits in it.', true,
    'Every model has a maximum size. Beyond it, older text must be dropped to make room.'),
  l3.mc('what-fits', 'What counts toward filling the context window?',
    ['Your prompt AND the model’s response together',
     'Only the model’s response',
     'Only pictures',
     'Nothing — it’s unlimited'],
    0, 'Both the input you give and the output it writes share the same limited space.'),
  l3.mc('overflow', 'What happens when a conversation grows past the context window?',
    ['The oldest text falls out of view and can be forgotten',
     'The model gains extra memory automatically',
     'The app deletes your account',
     'Nothing ever falls out'],
    0, 'Once it’s full, earlier parts drop off — which is why long chats can “forget” what you said at the start.'),
  l3.tf('permanent', 'Anything in the context window is remembered forever, across all future chats.', false,
    'The context window is temporary and per-conversation. It’s not permanent long-term memory.'),
  l3.match('terms', 'Match the term to its meaning.',
    [{ left: 'Context window', right: 'How much text the model sees at once' },
     { left: 'Prompt', right: 'The text you give the model' },
     { left: 'Overflow', right: 'Old text dropping out when it’s full' }],
    'The window holds your prompt and the reply; when it’s full, the oldest text overflows.'),
  l3.mc('why-limit', 'Why does a context window have a limit at all?',
    ['Paying attention to more text costs more memory and computing power',
     'To annoy users on purpose',
     'Because text can’t be stored',
     'There’s no real reason'],
    0, 'A bigger window is more expensive to run, so there’s always a practical ceiling.'),
  l3.tf('bigger-better', 'A larger context window lets the model consider more of your text at once.', true,
    'More room means it can keep track of longer documents or conversations without dropping the start.'),
  l3.mc('scenario-forget', 'In a very long chat, the AI forgets a detail you gave at the very beginning. Likely cause?',
    ['The early text slid out of the context window as the chat grew',
     'The model is broken',
     'The internet went down',
     'It’s ignoring you on purpose'],
    0, 'Long chats can push early text past the window’s limit, so the model no longer “sees” it.', 'scenario'),
  l3.mc('tip', 'A good habit when a chat gets long and the model seems to forget is to…',
    ['Restate the key details it needs right now',
     'Type in all capital letters',
     'Wait a day before asking',
     'Assume the model can never help'],
    0, 'Re-sharing important context brings it back into the window so the model can use it again.'),
  l3.tf('shared-space', 'A long prompt leaves less room in the window for the model’s reply.', true,
    'Prompt and reply share the same space, so a huge input reduces how much output can fit.'),
];

/* ================================================================== *
 * Lesson 4 — Temperature & Creativity
 * ================================================================== */
const l4 = bank('w5-l4', 'intermediate');
const w5l4Q: Question[] = [
  l4.mc('definition', 'What does “temperature” control in an LLM?',
    ['How random or creative the output is',
     'How hot the computer gets',
     'The reading speed of the model',
     'The size of the context window'],
    0, 'Temperature is a dial for randomness — low means safe and predictable, high means varied and creative.'),
  l4.tf('low', 'A low temperature makes the output more focused and predictable.', true,
    'At low temperature the model sticks to the most likely tokens, giving steady, repeatable answers.'),
  l4.mc('high', 'A high temperature tends to make output…',
    ['More creative, varied and surprising',
     'Shorter every time',
     'Always perfectly correct',
     'Completely blank'],
    0, 'Raising temperature lets the model pick less-likely tokens, adding variety and surprise.'),
  l4.mc('repeatable', 'If you want the SAME reliable answer every time, you’d use…',
    ['A low temperature',
     'A high temperature',
     'The largest context window',
     'More emojis'],
    0, 'Low temperature keeps the model on the safest, most likely path — great for consistent results.'),
  l4.tf('high-always-better', 'A high temperature is always the best choice.', false,
    'High temperature can wander off-topic or turn odd. The right setting depends on the task.'),
  l4.match('settings', 'Match the temperature to its typical effect.',
    [{ left: 'Low temperature', right: 'Focused, predictable, repeatable' },
     { left: 'High temperature', right: 'Creative, varied, surprising' },
     { left: 'Medium temperature', right: 'A balance of the two' }],
    'Turn the dial down for safety, up for creativity, or leave it in the middle for balance.'),
  l4.mc('task-fit', 'For brainstorming lots of unusual story ideas, a good setting is…',
    ['A higher temperature for more variety',
     'A temperature of exactly zero',
     'The smallest context window',
     'No model at all'],
    0, 'Creative tasks benefit from higher temperature, which encourages fresh, unexpected ideas.'),
  l4.mc('task-fit2', 'For extracting a precise fact from a document, a good setting is…',
    ['A lower temperature for a focused, reliable answer',
     'The highest possible temperature',
     'Maximum randomness',
     'A random setting each time'],
    0, 'Fact-focused tasks want low temperature so the model stays precise and doesn’t improvise.'),
  l4.tf('randomness', 'Temperature works by adjusting how much randomness enters token choice.', true,
    'It changes how boldly the model strays from the single most likely next token.'),
  l4.mc('scenario-poem', 'You want a playful, original poem but keep getting flat, generic lines. You should…',
    ['Raise the temperature to add creativity',
     'Lower the temperature to zero',
     'Shrink the context window',
     'Turn the model off and on'],
    0, 'Generic output often means temperature is too low; raising it invites more imaginative wording.', 'scenario'),
  l4.tf('trade-off', 'Higher temperature trades reliability for creativity.', true,
    'More creativity means more surprises — and sometimes more mistakes. It’s a genuine trade-off.'),
  l4.mc('summary', 'The best way to think of temperature is as…',
    ['A creativity dial you tune to the task',
     'A fixed setting you can never change',
     'A measure of the room’s heat',
     'The model’s battery level'],
    0, 'Match the dial to the job: low for precise work, high for creative work.'),
];

/* ================================================================== *
 * Lesson 5 — Hallucinations: When AI Makes Things Up
 * ================================================================== */
const l5 = bank('w5-l5', 'intermediate');
const w5l5Q: Question[] = [
  l5.mc('definition', 'What is an AI “hallucination”?',
    ['When the model states something false as if it were true',
     'When the screen flickers',
     'When the model refuses to answer',
     'When the app crashes'],
    0, 'A hallucination is a confident-sounding answer that is simply wrong or made up.'),
  l5.tf('confident', 'A hallucinated answer can sound completely confident and still be wrong.', true,
    'That’s what makes them tricky — the model doesn’t signal doubt even when it’s inventing.'),
  l5.mc('why', 'Why do LLMs hallucinate?',
    ['They predict likely-sounding text, not verified facts',
     'They are lying on purpose',
     'They ran out of battery',
     'They are angry at the user'],
    0, 'The model aims for plausible language, so it can produce something that reads well but isn’t true.'),
  l5.mc('example', 'Which is an example of a hallucination?',
    ['The AI invents a fake book title and confidently attributes it to a real author',
     'The AI says “I’m not sure”',
     'The AI correctly summarises a paragraph',
     'The AI asks you a clarifying question'],
    0, 'Making up a source that doesn’t exist — while sounding sure — is a classic hallucination.'),
  l5.tf('never', 'Modern LLMs never make things up.', false,
    'Even the best models can hallucinate. It’s a known limitation, not a solved problem.'),
  l5.match('guard', 'Match the guarding habit to why it helps.',
    [{ left: 'Verify facts elsewhere', right: 'Catches confident but false claims' },
     { left: 'Ask for sources', right: 'Makes made-up references easier to spot' },
     { left: 'Be extra careful on high-stakes topics', right: 'Limits the damage of a wrong answer' }],
    'Checking facts, requesting sources and staying cautious are your main defences against hallucinations.'),
  l5.mc('high-stakes', 'For a medical or legal question, the safest approach is to…',
    ['Treat the AI’s answer as a starting point and verify with a trusted source',
     'Accept it as final truth',
     'Assume it’s always wrong and ignore it',
     'Never ask any question'],
    0, 'On high-stakes topics, always confirm the AI’s answer against a reliable, authoritative source.'),
  l5.tf('made-up-sources', 'LLMs can invent citations or sources that don’t actually exist.', true,
    'Fabricated references are a common hallucination — always check that a cited source is real.'),
  l5.mc('reduce', 'Which habit best reduces the risk of being misled by a hallucination?',
    ['Cross-check important claims against a reliable source',
     'Ask the same question in a louder voice',
     'Trust the most confident-sounding reply',
     'Use a bigger screen'],
    0, 'Verification is the reliable guard. Confidence alone tells you nothing about correctness.'),
  l5.mc('scenario-fact', 'An AI gives you a very specific statistic with no source. You should…',
    ['Verify it before relying on it',
     'Assume it must be true because it’s specific',
     'Share it immediately as fact',
     'Ignore all statistics forever'],
    0, 'Precise-sounding numbers can still be invented. Confirm them before trusting or sharing.', 'scenario'),
  l5.tf('understand', 'Hallucinations happen because the model predicts plausible text rather than checking a database of facts.', true,
    'It’s optimising for what sounds right, which is not the same as what is true.'),
  l5.mc('takeaway', 'The key takeaway about hallucinations is…',
    ['Always verify important AI answers — confidence isn’t proof',
     'AI answers are always correct',
     'Never use AI for anything',
     'Only long answers can be wrong'],
    0, 'Use AI freely, but verify what matters. A confident answer can still be false.'),
];

/* ================================================================== *
 * Lesson 6 — Multimodal AI: Beyond Text
 * ================================================================== */
const l6 = bank('w5-l6', 'intermediate');
const w5l6Q: Question[] = [
  l6.mc('definition', 'What is a “multimodal” AI model?',
    ['One model that can handle several kinds of input, like text, images and audio',
     'A model that only reads text',
     'A model with many different apps',
     'A model that runs on many computers'],
    0, 'Multimodal means many modes — one model working across text, images, audio and more.'),
  l6.tf('beyond-text', 'Multimodal models can work with more than just text.', true,
    'They can also take in and reason about images, audio and even video — not text alone.'),
  l6.mc('example', 'Which is an example of a multimodal task?',
    ['Describing what’s happening in a photo in words',
     'Adding two numbers',
     'Sorting a text list alphabetically',
     'Turning off the screen'],
    0, 'Going from an image to a text description crosses two modes — a hallmark of multimodal AI.'),
  l6.match('modes', 'Match each mode to an example input.',
    [{ left: 'Text', right: 'A typed question' },
     { left: 'Image', right: 'A photo of a street' },
     { left: 'Audio', right: 'A spoken voice note' }],
    'Text, images and audio are all “modes” a multimodal model can take in.'),
  l6.tf('one-model', 'Multimodal AI uses one model to handle several senses, rather than a separate model per type.', true,
    'The strength is that a single model connects the modes — understanding text and images together.'),
  l6.mc('senses', 'A helpful way to picture multimodal AI is…',
    ['One brain with several senses — it can read, see and hear',
     'A calculator with a bigger screen',
     'A model that only ever writes poems',
     'A printer'],
    0, 'Like a person using multiple senses at once, a multimodal model combines different kinds of input.'),
  l6.mc('use-case', 'Which is a realistic use of multimodal AI?',
    ['Answering a question about a chart shown in an image',
     'Charging a phone faster',
     'Physically cleaning a room',
     'Measuring rainfall directly'],
    0, 'Reading a chart image and answering questions about it blends vision and language — multimodal in action.'),
  l6.tf('text-only', 'A model that can only read and write text is fully multimodal.', false,
    'Text-only is single-mode. Multimodal specifically means it handles more than one kind of input.'),
  l6.mc('combine', 'The real power of multimodal AI comes from…',
    ['Combining information across modes, like matching a caption to an image',
     'Ignoring all but one input type',
     'Using the smallest possible model',
     'Never using text'],
    0, 'Connecting what it sees with what it reads lets the model do things a text-only model can’t.'),
  l6.mc('scenario-photo', 'You send the AI a photo of your fridge and ask “what can I cook?” This works because the model is…',
    ['Multimodal — it can look at the image and answer in text',
     'Text-only',
     'A simple calculator',
     'Just guessing without seeing the photo'],
    0, 'Understanding the photo and replying in words is exactly what a multimodal model does.', 'scenario'),
  l6.tf('future', 'Multimodal models are a step toward AI that interacts with the world more like people do.', true,
    'Handling sight, sound and language together brings AI closer to how humans naturally perceive things.'),
  l6.mc('summary', 'The best one-line summary of multimodal AI is…',
    ['One model, many senses — text, images, audio and beyond',
     'A model that only handles numbers',
     'A model with no inputs',
     'A model that works only offline'],
    0, 'Multimodal AI unifies several kinds of input in a single model — many senses, one brain.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD5_LESSONS: Lesson[] = [
  {
    id: 'w5-l1', worldId: W, order: 1,
    title: 'What Is a Large Language Model?',
    subtitle: 'The AI behind the chatbots',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'Meet the LLM: an AI trained on a mountain of text that can read, write and answer in plain language.',
    explanation: 'A large language model learns by reading a huge amount of human-written text — far more than any person could. From all that reading it picks up the patterns of language: which words tend to follow which. That’s why it can answer questions and write in fluent sentences. It doesn’t look up stored answers; it generates fresh text using what it learned.',
    realWorld: 'Think of someone who has read almost every book in a giant library. They can’t recall each book word-for-word, but they’ve absorbed how language works well enough to write about almost anything.',
    objectives: [
      'Define a large language model in one clear sentence',
      'Explain what the word “large” refers to',
      'Recognise everyday tools powered by an LLM',
    ],
    activity: {
      kind: 'bucket',
      title: 'LLM Job or Not?',
      instructions: 'Sort each task by whether a large language model is a good fit.',
      config: {
        buckets: ['Great fit for an LLM', 'Not an LLM’s job'],
        items: [
          { label: 'Write a friendly email', bucket: 0 },
          { label: 'Summarise an article', bucket: 0 },
          { label: 'Answer a question in words', bucket: 0 },
          { label: 'Rewrite a message’s tone', bucket: 0 },
          { label: 'Charge a phone battery', bucket: 1 },
          { label: 'Measure room temperature', bucket: 1 },
          { label: 'Physically lift a box', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'An LLM is an AI trained on huge amounts of text to handle language.',
      '“Large” means massive training data and a very big model.',
      'It generates fresh text from patterns — it isn’t a lookup table.',
    ],
    commonMistakes: [
      'Thinking an LLM stores and looks up answers word-for-word.',
      'Assuming it truly understands meaning like a human does.',
      'Believing everything it says is automatically correct.',
    ],
    summary: 'An LLM is text-trained AI that reads and writes fluent language.',
    prerequisiteLessonIds: ['w4-l6'],
    nextLessonId: 'w5-l2',
  },
  {
    id: 'w5-l2', worldId: W, order: 2,
    title: 'Predicting the Next Token',
    subtitle: 'How an LLM actually writes',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 5,
    description: 'Under the hood, an LLM writes by guessing one tiny piece of text at a time — over and over.',
    explanation: 'An LLM builds its answer token by token, where a token is a small chunk of text — often a word or part of one. It reads everything written so far, predicts the most likely next token, adds it, and repeats. It’s the same idea as phone autocomplete, just far more powerful. Because each guess builds on the last, the sentence stays coherent and on-topic.',
    realWorld: 'It’s like autocomplete finishing your text messages — but instead of one word, it keeps going, chaining guess after guess into whole paragraphs.',
    objectives: [
      'Describe the read–predict–add–repeat loop',
      'Explain what a token is',
      'Connect next-token prediction to autocomplete',
    ],
    activity: {
      kind: 'sequence',
      title: 'Guess the Next Token',
      instructions: 'Look at the text so far and pick the most likely next token — just like the model does.',
      config: {
        shown: ['The', 'sky', 'is'],
        options: ['blue', 'seven', 'quickly', 'banana'],
        correctIndex: 0,
        reveal: 'From patterns in text, “blue” is a very likely continuation of “The sky is”. The model picks whatever is most likely to come next.',
      },
    },
    keyTakeaways: [
      'An LLM generates text one token at a time.',
      'A token is a small chunk of text, often a word or part of one.',
      'Each prediction builds on everything written so far.',
    ],
    commonMistakes: [
      'Thinking the model writes the whole answer at once.',
      'Believing it plans the full sentence before starting.',
      'Assuming a token is always exactly one word.',
    ],
    summary: 'LLMs write by predicting the next token, again and again.',
    prerequisiteLessonIds: ['w5-l1'],
    nextLessonId: 'w5-l3',
  },
  {
    id: 'w5-l3', worldId: W, order: 3,
    title: 'The Context Window',
    subtitle: 'The model’s short-term memory',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 60, coins: 8,
    description: 'An LLM can only “see” so much text at once. That limited view is its context window.',
    explanation: 'The context window is how much text — your prompt plus the model’s reply — the LLM can pay attention to at one time. It works like short-term memory: helpful while it’s in view, but limited. Both your input and the output share this space. When a conversation grows past the limit, the oldest text drops out, which is why long chats can seem to forget what you said at the start.',
    realWorld: 'It’s like a desk that only fits so many papers. New pages keep arriving, and once the desk is full, the oldest pages get pushed off the edge and out of sight.',
    objectives: [
      'Define the context window',
      'Explain why it has a limit',
      'Predict what happens when it fills up',
    ],
    activity: {
      kind: 'slider',
      title: 'How Much Fits?',
      instructions: 'Slide to change how big the context window is, and see how much of a conversation the model can keep in view.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Context window size',
        stops: [
          { upTo: 15, title: 'Tiny', detail: 'Only the last few lines fit — it quickly forgets earlier text.' },
          { upTo: 45, title: 'Small', detail: 'It follows a short chat but loses the start of a long one.' },
          { upTo: 75, title: 'Large', detail: 'It keeps most of a long conversation in view.' },
          { upTo: 100, title: 'Very large', detail: 'It can hold whole documents and long chats at once.' },
        ],
      },
    },
    keyTakeaways: [
      'The context window is how much text the model sees at once.',
      'Your prompt and its reply share that limited space.',
      'When it fills up, the oldest text drops out and can be forgotten.',
    ],
    commonMistakes: [
      'Thinking the model remembers everything forever.',
      'Forgetting that a long prompt leaves less room for the reply.',
      'Assuming the window is unlimited.',
    ],
    summary: 'The context window is the model’s limited short-term memory.',
    prerequisiteLessonIds: ['w5-l2'],
    nextLessonId: 'w5-l4',
  },
  {
    id: 'w5-l4', worldId: W, order: 4,
    title: 'Temperature & Creativity',
    subtitle: 'The randomness dial',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Temperature is a dial that decides how safe or how creative an LLM’s answers are.',
    explanation: 'Temperature controls how much randomness enters the model’s token choices. At a low temperature it sticks to the most likely tokens, giving focused, predictable, repeatable answers — great for facts. At a high temperature it’s willing to pick less-likely tokens, producing creative, varied and surprising text — great for brainstorming. Higher creativity trades away some reliability, so you tune the dial to the task.',
    realWorld: 'Low temperature is a careful chef who always follows the recipe exactly. High temperature is an adventurous chef who improvises — sometimes brilliant, sometimes strange.',
    objectives: [
      'Explain what temperature controls',
      'Match low and high temperature to their effects',
      'Choose a temperature that fits the task',
    ],
    activity: {
      kind: 'slider',
      title: 'Temperature Dial',
      instructions: 'Slide the temperature from low to high and see how the model’s style changes.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Temperature',
        stops: [
          { upTo: 20, title: 'Low — focused', detail: 'Safe, predictable, repeatable. Best for facts and precise answers.' },
          { upTo: 50, title: 'Medium-low — steady', detail: 'Mostly reliable with a little variety.' },
          { upTo: 80, title: 'Medium-high — lively', detail: 'More varied and expressive, still on-topic.' },
          { upTo: 100, title: 'High — creative', detail: 'Surprising and imaginative — and sometimes off-track.' },
        ],
      },
    },
    keyTakeaways: [
      'Temperature controls how random or creative the output is.',
      'Low = focused and repeatable; high = creative and surprising.',
      'Tune the dial to the task — precise work low, creative work high.',
    ],
    commonMistakes: [
      'Thinking higher temperature is always better.',
      'Confusing temperature with the model’s speed or memory.',
      'Expecting the exact same answer at a high temperature.',
    ],
    summary: 'Temperature is the creativity dial: low for focus, high for flair.',
    prerequisiteLessonIds: ['w5-l3'],
    nextLessonId: 'w5-l5',
  },
  {
    id: 'w5-l5', worldId: W, order: 5,
    title: 'Hallucinations: When AI Makes Things Up',
    subtitle: 'Confident, fluent — and sometimes wrong',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'LLMs can state false things as if they were true. Learn why it happens and how to guard against it.',
    explanation: 'A hallucination is when an LLM confidently says something that isn’t true — sometimes even inventing sources that don’t exist. It happens because the model predicts plausible-sounding language, not verified facts, so it can produce text that reads well but is wrong. The tricky part is that it shows no doubt. Your best defence is to verify important claims against a trusted source, especially on high-stakes topics.',
    realWorld: 'It’s like a smooth-talking friend who never says “I don’t know” — they always give a confident answer, so you learn to double-check the important ones.',
    objectives: [
      'Define what a hallucination is',
      'Explain why LLMs make things up',
      'Apply habits that guard against being misled',
    ],
    activity: {
      kind: 'steps',
      title: 'Guard Against Hallucinations',
      instructions: 'Drag the steps into a sensible order for handling an important AI answer.',
      config: {
        steps: [
          'Read the AI’s answer carefully',
          'Notice it sounds confident — but confidence isn’t proof',
          'Check the key claims against a trusted source',
          'Only rely on the answer once it’s verified',
        ],
      },
    },
    keyTakeaways: [
      'A hallucination is a confident answer that is actually false.',
      'It happens because the model predicts plausible text, not verified facts.',
      'Always verify important claims — confidence isn’t proof.',
    ],
    commonMistakes: [
      'Trusting an answer just because it sounds confident.',
      'Assuming cited sources are always real.',
      'Believing modern models never make things up.',
    ],
    summary: 'LLMs can confidently make things up — verify what matters.',
    prerequisiteLessonIds: ['w5-l4'],
    nextLessonId: 'w5-l6',
  },
  {
    id: 'w5-l6', worldId: W, order: 6,
    title: 'Multimodal AI: Beyond Text',
    subtitle: 'One model, many senses',
    difficulty: 'intermediate', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Some AI models go beyond text — they can also handle images, audio and video in a single model.',
    explanation: 'A multimodal model works with more than one kind of input: text, images, audio, even video. Instead of a separate model per type, one model connects them — so it can look at a photo and describe it, or read a chart image and answer questions about it. The real power comes from combining modes, like matching a caption to a picture. Picture it as one brain with several senses.',
    realWorld: 'It’s like a person who can read a menu, see the food and hear the waiter — all at once — and pull it together into one understanding. That blend of senses is what multimodal AI does.',
    objectives: [
      'Define multimodal AI',
      'Name the modes it can handle',
      'Recognise tasks that need more than text',
    ],
    activity: {
      kind: 'bucket',
      title: 'Multimodal or Text-Only?',
      instructions: 'Sort each task by whether it needs a multimodal model or just text.',
      config: {
        buckets: ['Needs multimodal AI', 'Text-only is enough'],
        items: [
          { label: 'Describe what’s in a photo', bucket: 0 },
          { label: 'Answer questions about a chart image', bucket: 0 },
          { label: 'Transcribe a spoken voice note', bucket: 0 },
          { label: 'Suggest recipes from a fridge photo', bucket: 0 },
          { label: 'Summarise a typed paragraph', bucket: 1 },
          { label: 'Rewrite a sentence more politely', bucket: 1 },
          { label: 'Answer a typed trivia question', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Multimodal AI handles several input types in one model.',
      'It can work with text, images, audio and video.',
      'Its power comes from combining information across modes.',
    ],
    commonMistakes: [
      'Thinking a text-only model is multimodal.',
      'Assuming each mode needs a totally separate model.',
      'Overlooking that combining modes is the real advantage.',
    ],
    summary: 'Multimodal AI is one model with many senses — beyond text alone.',
    prerequisiteLessonIds: ['w5-l5'],
    nextLessonId: 'w6-l1',
  },
];

export const WORLD5_QUESTIONS: Question[] = [
  ...w5l1Q, ...w5l2Q, ...w5l3Q,
  ...w5l4Q, ...w5l5Q, ...w5l6Q,
];
