import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 10 — Model Context Protocol (MCP). Full lessons + question bank.
 * Analogy running through the world: MCP is like a USB-C port for AI —
 * one standard plug so any AI app can connect to any tool or data source.
 */

const W = 'world-mcp';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — The Integration Problem
 * ================================================================== */
const l1 = bank('w10-l1', 'intermediate');
const w10l1Q: Question[] = [
  l1.mc('problem', 'Before MCP, connecting an AI app to a tool usually meant…',
    ['Writing a custom, one-off integration for that exact pairing',
     'The tool connecting itself automatically',
     'No connection was ever possible',
     'Buying a new laptop'],
    0, 'Each AI-app-to-tool link was hand-built. Nothing was reusable, so every new pairing started from scratch.'),
  l1.tf('scope', 'Custom integrations built for one AI app could usually be reused by every other AI app.', false,
    'A custom link was glued to one specific app and one specific tool. Another app couldn’t just pick it up.'),
  l1.mc('nxm', 'The “N×M problem” describes…',
    ['N AI apps each needing a separate custom link to M tools — an explosion of connectors',
     'A maths puzzle unrelated to software',
     'Multiplying model sizes',
     'A way to speed up chips'],
    0, 'With N apps and M tools, custom wiring means up to N×M connectors to build and maintain — it doesn’t scale.'),
  l1.mc('cost', 'What made the old approach so painful?',
    ['Every connector had to be built, tested and maintained separately',
     'Connectors were illegal',
     'Tools refused to share data',
     'AI apps could only run once'],
    0, 'Duplicated effort everywhere: each team reinvented the same plumbing, then had to keep all of it working.'),
  l1.tf('duplication', 'The old custom-integration world led to lots of duplicated, repeated work.', true,
    'Ten apps wanting the same database each wrote their own connector — the same job done ten different times.'),
  l1.mc('analogy', 'Life before a universal standard is most like…',
    ['Every device needing its own unique charger and cable',
     'Everyone speaking the same language',
     'One key opening every door',
     'A single power socket for the whole world'],
    0, 'Remember the drawer of mismatched chargers? That mess is exactly what custom AI integrations felt like.'),
  l1.match('pain', 'Match each symptom of the old world to what it meant.',
    [{ left: 'N×M connectors', right: 'Too many links to build' },
     { left: 'Custom code per pairing', right: 'No reuse across apps' },
     { left: 'Separate maintenance', right: 'Ongoing upkeep for each link' }],
    'More apps and tools multiplied the wiring, none of it was reusable, and all of it needed babysitting.'),
  l1.mc('scenario-team', 'A team adds a 4th AI app that needs the same 5 tools the other apps use. Without a standard, they must…',
    ['Build 5 more custom connectors from scratch for this app',
     'Do nothing — the connectors auto-transfer',
     'Delete the other apps',
     'Wait for the tools to connect themselves'],
    0, 'Because connectors aren’t shareable, each new app re-wires every tool it needs — the N×M mess in action.', 'scenario'),
  l1.tf('scale', 'As you add more AI apps and more tools, the number of custom connectors can grow very fast.', true,
    'It grows roughly with N times M. Ten apps and ten tools could mean up to a hundred separate connectors.'),
  l1.mc('why-standard', 'The core reason a shared standard would help is that it…',
    ['Lets any app reuse one connector instead of everyone rebuilding it',
     'Makes tools run faster',
     'Removes the need for data',
     'Turns every AI into general AI'],
    0, 'A standard turns N×M custom links into something far smaller and reusable — build once, connect many.'),
  l1.mc('goal', 'The integration problem is best summarised as…',
    ['Too many custom, non-reusable connections between AI apps and tools',
     'AI apps being too slow',
     'Tools having no data',
     'Screens being too small'],
    0, 'It’s a plumbing problem: bespoke wiring everywhere, none of it shared — exactly what MCP sets out to fix.'),
  l1.tf('motivation', 'MCP exists mainly to replace this messy custom wiring with one shared way to connect.', true,
    'Understanding the pain of the old world is the whole motivation for MCP — it’s the problem MCP was built to solve.'),
];

/* ================================================================== *
 * Lesson 2 — What Is the Model Context Protocol?
 * ================================================================== */
const l2 = bank('w10-l2', 'intermediate');
const w10l2Q: Question[] = [
  l2.mc('definition', 'What is the Model Context Protocol (MCP)?',
    ['An open standard that lets AI apps and tools connect in one common way',
     'A brand of laptop',
     'A type of AI model',
     'A programming language'],
    0, 'MCP is a shared protocol — a common language — so any AI app can talk to any tool that follows it.'),
  l2.tf('open', 'MCP is an open standard, not owned by a single locked-down product.', true,
    'Being open means anyone can build MCP servers and clients that work together — that’s what makes it universal.'),
  l2.mc('usb-c', 'The USB-C analogy for MCP means…',
    ['One standard plug so any AI app can connect to any tool or data source',
     'MCP only works over USB cables',
     'AI needs special hardware ports',
     'You must buy new chargers for AI'],
    0, 'Like USB-C replaced a drawer of chargers with one plug, MCP replaces custom wiring with one standard connection.'),
  l2.mc('what-fixes', 'What problem does MCP directly solve?',
    ['The N×M mess of custom, non-reusable integrations',
     'Slow internet',
     'Small phone screens',
     'AI running out of electricity'],
    0, 'MCP turns “build a custom link for every pairing” into “follow one standard and connect to everything”.'),
  l2.tf('protocol', 'A protocol is basically an agreed set of rules for how two sides talk to each other.', true,
    'Just like HTTP lets browsers and websites agree how to talk, MCP lets AI apps and tools agree how to talk.'),
  l2.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Protocol', right: 'Agreed rules for communication' },
     { left: 'Open standard', right: 'Public, anyone can implement it' },
     { left: 'MCP', right: 'A standard link between AI apps and tools' }],
    'MCP is an open protocol — public rules everyone can follow so their AI apps and tools interoperate.'),
  l2.mc('benefit', 'The biggest benefit of one standard is…',
    ['Build a connector once and any compliant AI app can use it',
     'AI answers become always correct',
     'Tools no longer need data',
     'Models get physically smaller'],
    0, 'Write to the standard once and it plugs into every MCP-capable app — no more rebuilding the same connector.'),
  l2.tf('one-language', 'With MCP, an AI app and a tool don’t need a custom private language for each pairing.', true,
    'They both speak MCP. That shared language is what removes the need for bespoke, one-off connectors.'),
  l2.mc('not', 'Which of these is MCP NOT?',
    ['A smarter AI model that thinks better',
     'A way for AI apps to reach tools',
     'An open standard',
     'A common communication protocol'],
    0, 'MCP doesn’t make the model smarter — it’s the connection layer that gives the model access to tools and data.'),
  l2.mc('scenario-new-tool', 'A company builds a new note-taking tool and wants every AI app to use it. The MCP way is to…',
    ['Expose it once via MCP, so any MCP client can connect',
     'Write a private connector for each AI app separately',
     'Ask every app maker to rewrite their app',
     'Keep it disconnected from all AI'],
    0, 'Following the standard once makes the tool instantly reachable by the whole MCP ecosystem — that’s the point.', 'scenario'),
  l2.tf('interoperable', 'Because MCP is a shared standard, tools and apps from different makers can work together.', true,
    'Interoperability is the whole idea: different vendors’ apps and tools cooperate as long as they speak MCP.'),
  l2.mc('goal', 'In one line, MCP is…',
    ['A common standard so AI apps and tools speak the same language',
     'A faster chip for AI',
     'A cloud storage service',
     'A type of chatbot'],
    0, 'One shared language between AI apps and tools — that single idea is the heart of the Model Context Protocol.'),
];

/* ================================================================== *
 * Lesson 3 — Servers, Clients & Tools
 * ================================================================== */
const l3 = bank('w10-l3', 'intermediate');
const w10l3Q: Question[] = [
  l3.mc('server', 'In MCP, what does a “server” do?',
    ['Exposes tools and data that an AI app can use',
     'Displays the chat window',
     'Trains the AI model',
     'Charges the battery'],
    0, 'An MCP server is the side that offers capabilities — tools to call and data to read — for AI apps to use.'),
  l3.mc('client', 'In MCP, the “client” is…',
    ['The AI app that connects to servers and uses their tools',
     'The database itself',
     'The physical cable',
     'The person typing'],
    0, 'The client lives inside the AI app. It reaches out to MCP servers and calls the tools they expose.'),
  l3.tf('roles', 'An MCP server exposes capabilities; an MCP client (the AI app) uses them.', true,
    'Server = offers tools and data. Client = the AI app that connects and puts those tools to work.'),
  l3.mc('tool', 'A “tool” in MCP is best described as…',
    ['An action the AI can invoke, like search files or query a database',
     'A physical hammer',
     'The AI model’s brain',
     'A screen setting'],
    0, 'Tools are the actions a server offers — the AI can call them to actually do things, not just talk about them.'),
  l3.match('roles-match', 'Match each MCP piece to its job.',
    [{ left: 'Server', right: 'Exposes tools and data' },
     { left: 'Client', right: 'The AI app that uses them' },
     { left: 'Tool', right: 'An action the AI can invoke' }],
    'Servers offer, clients consume, and tools are the concrete actions that pass between them.'),
  l3.tf('many', 'One AI app (client) can connect to several MCP servers at the same time.', true,
    'A single client can plug into a files server, a database server and a calendar server all at once.'),
  l3.mc('data', 'Besides actions, MCP servers can also expose…',
    ['Data and resources the AI can read for context',
     'Only the weather',
     'Nothing but images',
     'Only the current time'],
    0, 'Servers can share resources — documents, records, context — not just callable actions.'),
  l3.mc('who-calls', 'Who decides to actually call a tool?',
    ['The client (AI app), driven by the model’s needs',
     'The server, whenever it likes',
     'The tool calls itself randomly',
     'The database'],
    0, 'The client initiates. The server just makes tools available; the AI app decides when to invoke them.'),
  l3.tf('server-smart', 'An MCP server has to contain the AI model itself.', false,
    'No. The model lives on the client side. The server simply exposes tools and data — it isn’t the AI.'),
  l3.mc('scenario-weather', 'You want your AI app to fetch live weather. The clean MCP setup is…',
    ['A weather MCP server exposing a “get_weather” tool the client calls',
     'Putting the weather inside the model’s training',
     'Asking the user to type the forecast',
     'Making the server run the AI'],
    0, 'Expose weather as a tool on a server; the AI-app client calls it when it needs live data. Clean separation.', 'scenario'),
  l3.match('examples', 'Match each real thing to its MCP role.',
    [{ left: 'A files MCP server', right: 'Server' },
     { left: 'The AI chat app', right: 'Client' },
     { left: '“search_files” action', right: 'Tool' }],
    'The files server offers capabilities, the chat app is the client, and search_files is one of its tools.'),
  l3.tf('goal', 'Knowing server vs client vs tool is the vocabulary you need for everything else in MCP.', true,
    'Everything in MCP is servers exposing tools and clients using them — get these three and the rest follows.'),
];

/* ================================================================== *
 * Lesson 4 — How MCP Connects Everything
 * ================================================================== */
const l4 = bank('w10-l4', 'advanced');
const w10l4Q: Question[] = [
  l4.mc('first-step', 'The very first thing that happens when a client uses an MCP server is…',
    ['The client connects to the server',
     'The client calls a tool blindly',
     'The server rewrites the AI model',
     'The user reboots the phone'],
    0, 'You connect first. Only after a connection exists can the client discover and call anything.'),
  l4.order('flow', 'Put the connect-and-call flow in the right order.',
    ['Client connects to the MCP server',
     'Client asks the server what tools it offers',
     'Server sends back its list of available tools',
     'Client calls a chosen tool with inputs',
     'Server runs the tool and returns the result'],
    'Connect → discover the tools → pick and call one with inputs → get the result back. That’s the whole handshake.'),
  l4.tf('discovery', 'A client can ask a server which tools it offers, rather than guessing.', true,
    'Discovery is built in: the client requests the tool list, so it always knows exactly what’s available.'),
  l4.mc('why-discover', 'Why does discovery matter?',
    ['The client learns exactly which tools and inputs are available before calling',
     'It makes the screen brighter',
     'It trains the model',
     'It deletes old data'],
    0, 'Discovery means no hard-coded assumptions — the client adapts to whatever tools each server actually offers.'),
  l4.mc('call', 'When the client calls a tool, it sends…',
    ['The tool name plus the inputs that tool needs',
     'Only a random number',
     'The entire AI model',
     'Nothing at all'],
    0, 'A call names the tool and provides its inputs (arguments); the server uses those to do the work.'),
  l4.tf('result', 'After running a tool, the server returns a result the AI can use.', true,
    'The result flows back to the client, giving the model fresh information or confirming an action was done.'),
  l4.match('steps-match', 'Match each step to who does it.',
    [{ left: 'Connect to the server', right: 'Client' },
     { left: 'List available tools', right: 'Server' },
     { left: 'Run the tool and reply', right: 'Server' }],
    'The client drives connecting and calling; the server responds by listing tools and running them.'),
  l4.mc('reuse', 'Because every server follows the same flow, the client can…',
    ['Talk to any MCP server the same way, without custom code per server',
     'Only ever use one server',
     'Skip connecting entirely',
     'Avoid sending inputs'],
    0, 'One shared flow means one code path works for all servers — exactly the reuse the standard promises.'),
  l4.tf('order-matters', 'You can call a tool before connecting to the server.', false,
    'No connection, no calls. The flow always starts with connecting; calling comes only after discovery.'),
  l4.mc('scenario-debug', 'A client connects but finds no tools to call. The most likely reason is…',
    ['The server exposes no tools, or discovery returned an empty list',
     'The user’s screen is too dim',
     'The AI model is too smart',
     'The battery is full'],
    0, 'If discovery returns nothing, there’s nothing to call. Check that the server actually exposes tools.', 'scenario'),
  l4.order('mini', 'Order just the “call” half of the flow.',
    ['Client picks a tool from the list',
     'Client sends the tool name and inputs',
     'Server runs the tool',
     'Server returns the result to the client'],
    'Pick → send name and inputs → server runs it → result comes back. That’s a single tool call end to end.'),
  l4.tf('goal', 'The connect → discover → call → result flow is the heartbeat of every MCP interaction.', true,
    'Every MCP feature, no matter the tool, rides on this same simple handshake — learn it once, understand them all.'),
];

/* ================================================================== *
 * Lesson 5 — MCP in Practice
 * ================================================================== */
const l5 = bank('w10-l5', 'advanced');
const w10l5Q: Question[] = [
  l5.mc('files', 'An MCP server for files would let an AI app…',
    ['Read, search or write files through standard tools',
     'Change the phone’s wallpaper',
     'Train a new model',
     'Charge the battery'],
    0, 'A files server exposes tools like read, list and search — so the AI can work with your documents directly.'),
  l5.tf('database', 'An MCP server can let an AI app query a database with the right tools.', true,
    'A database MCP server exposes query tools, so the AI can pull real records instead of guessing.'),
  l5.mc('web', 'A web-search MCP server gives an AI app the ability to…',
    ['Look up fresh information from the internet',
     'Print documents',
     'Replace its training data',
     'Turn off Wi-Fi'],
    0, 'A web server exposes search or fetch tools, letting the AI reach current information beyond its training.'),
  l5.mc('calendar', 'Plugging a calendar MCP server into an AI app lets it…',
    ['Read events and create or update appointments',
     'Change the time zone of the sun',
     'Make the model larger',
     'Delete the internet'],
    0, 'A calendar server exposes tools to view and manage events, so the AI can actually schedule things for you.'),
  l5.match('servers', 'Match each MCP server to what it lets the AI do.',
    [{ left: 'Files server', right: 'Read and search documents' },
     { left: 'Database server', right: 'Query records' },
     { left: 'Calendar server', right: 'Manage appointments' }],
    'Each server plugs a real capability into the AI app — files, data, or scheduling — all via the same standard.'),
  l5.tf('mix', 'One AI app can use a files server AND a calendar server AND a web server together.', true,
    'Because they all speak MCP, an app can plug in many servers at once and combine their tools freely.'),
  l5.mc('context', 'Why is connecting these servers so powerful?',
    ['The AI moves from just talking to actually doing and using live data',
     'It makes the AI conscious',
     'It removes the need for a model',
     'It hides the AI from users'],
    0, 'Tools turn a chatbot into an assistant that reads your files, checks live info and takes real actions.'),
  l5.mc('scenario-assistant', 'You ask your AI to “find my budget file and add a meeting to review it Friday.” It uses…',
    ['A files server to find the file and a calendar server to add the meeting',
     'Only its training data, no tools',
     'A single random guess',
     'The web server to charge the phone'],
    0, 'Two servers, two tools: search the files, then create the calendar event. Combining tools is MCP in practice.', 'scenario'),
  l5.tf('same-flow', 'A files server and a calendar server are used through the same connect-and-call flow.', true,
    'Different capabilities, identical flow. Once you learn one MCP server, you effectively know how to use them all.'),
  l5.mc('value', 'The practical value of MCP for an everyday user is…',
    ['Their AI app can safely reach the real tools and data they care about',
     'Faster screen brightness',
     'Bigger emojis',
     'Louder speakers'],
    0, 'MCP quietly lets your AI work with your files, calendar and data — real usefulness, powered by a shared standard.'),
  l5.mc('extend', 'To give an AI app a brand-new capability, you can…',
    ['Add another MCP server that exposes that capability as tools',
     'Retrain the whole model from scratch',
     'Buy a new phone',
     'Delete the existing servers'],
    0, 'Capabilities are modular: plug in a new server and the AI gains new powers — no retraining, no rewrites.'),
];

/* ================================================================== *
 * Lesson 6 — The Future: A Universal AI Interface
 * ================================================================== */
const l6 = bank('w10-l6', 'advanced');
const w10l6Q: Question[] = [
  l6.mc('why-matters', 'Why does having ONE standard matter so much?',
    ['Build a tool once and every compliant AI app can use it',
     'It makes AI models bigger',
     'It removes the need for data',
     'It makes screens brighter'],
    0, 'A single standard unlocks a network effect: each new server or app instantly works with all the others.'),
  l6.tf('ecosystem', 'A shared standard lets an ecosystem of interchangeable tools and apps grow.', true,
    'When everyone speaks MCP, tools and apps mix and match freely — that’s how a healthy ecosystem forms.'),
  l6.mc('network', 'The “network effect” of MCP means…',
    ['Every new MCP tool makes every MCP app more capable, and vice versa',
     'The internet gets slower',
     'AI models forget things',
     'Tools stop working together'],
    0, 'Each addition benefits the whole: more servers make apps richer, more apps make servers worth building.'),
  l6.mc('usb-c-again', 'Calling MCP “USB-C for AI” captures the idea that…',
    ['One standard plug connects any app to any tool or data source',
     'AI needs special cables',
     'MCP only works on new devices',
     'You must replace all your tools'],
    0, 'Like USB-C ended the charger chaos, MCP aims to end integration chaos with one universal connection.'),
  l6.match('future', 'Match each benefit of a universal interface to its result.',
    [{ left: 'One standard', right: 'Build once, connect everywhere' },
     { left: 'Growing ecosystem', right: 'More tools and apps that interoperate' },
     { left: 'Network effect', right: 'Each addition helps the whole' }],
    'A single standard, a growing ecosystem and network effects reinforce each other into a universal AI interface.'),
  l6.tf('replace-model', 'A universal interface like MCP replaces the AI model itself.', false,
    'MCP connects the model to the world; it doesn’t replace the model. It’s the plug, not the brain.'),
  l6.mc('contrast', 'Compared with the old N×M mess, a universal standard gives us…',
    ['Far fewer connectors, all reusable across apps and tools',
     'Even more custom connectors',
     'No connections at all',
     'Slower AI apps'],
    0, 'Instead of N×M bespoke links, everyone builds to one standard — dramatically less work, endlessly reusable.'),
  l6.tf('open-growth', 'Being an open standard helps MCP’s ecosystem grow faster.', true,
    'Open means anyone can contribute servers and clients, so the ecosystem expands without gatekeepers.'),
  l6.mc('scenario-future', 'A startup wants its AI product to work with hundreds of existing tools quickly. MCP helps by…',
    ['Letting it connect to any tool that already speaks MCP, no custom work each time',
     'Forcing it to rebuild every tool',
     'Blocking it from other tools',
     'Making its model conscious'],
    0, 'Speak the standard and the whole existing ecosystem opens up instantly — that’s the strategic power of MCP.', 'scenario'),
  l6.mc('takeaway', 'The big-picture takeaway of MCP is…',
    ['A universal, open way for AI to connect to tools and data',
     'A faster type of chip',
     'A new kind of screen',
     'A way to make AI conscious'],
    0, 'MCP’s promise is a shared, open interface — one plug — between AI and everything it needs to be useful.'),
  l6.tf('goal', 'MCP points toward a future where any AI app can plug into any tool through one shared standard.', true,
    'That vision — one universal interface for AI — is why MCP matters and why its ecosystem keeps growing.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD10_LESSONS: Lesson[] = [
  {
    id: 'w10-l1', worldId: W, order: 1,
    title: 'The Integration Problem',
    subtitle: 'Why connecting AI to tools used to be a mess',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 60, coins: 6,
    description: 'Before MCP, every AI-app-to-tool connection was hand-built. Meet the “N×M” mess that made this unsustainable.',
    explanation: 'Imagine N different AI apps each needing to reach M different tools. With custom wiring, you might build up to N×M separate connectors — and none of them are reusable. Every new app or tool multiplies the work.',
    realWorld: 'Think of the old drawer full of mismatched chargers — a different cable for every device. Custom AI integrations felt exactly like that: bespoke, tangled and never reusable.',
    objectives: [
      'Describe how AI-tool connections were built before MCP',
      'Explain the N×M integration problem',
      'See why custom connectors don’t scale',
    ],
    activity: {
      kind: 'slider',
      title: 'The N×M Explosion',
      instructions: 'Slide to add more AI apps and tools. Watch how many custom connectors you’d need to build and maintain.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Apps × tools to connect',
        stops: [
          { upTo: 5, title: 'A couple of links', detail: 'One app, one tool — a single custom connector. Manageable.' },
          { upTo: 30, title: 'Getting messy', detail: 'A few apps and tools already mean many separate connectors.' },
          { upTo: 70, title: 'Hard to maintain', detail: 'Connectors everywhere — each one built and babysat by hand.' },
          { upTo: 100, title: 'The N×M mess', detail: 'An explosion of bespoke links. This is exactly what MCP fixes.' },
        ],
      },
    },
    keyTakeaways: [
      'Before MCP, each AI-tool link was a custom, one-off build.',
      'N apps and M tools meant up to N×M connectors — none reusable.',
      'This duplication and upkeep simply didn’t scale.',
    ],
    commonMistakes: [
      'Thinking a connector built for one app could be reused by another — it couldn’t.',
      'Assuming the problem was slow tools, when it was really the wiring between them.',
    ],
    summary: 'The old world was a tangle of custom, non-reusable connectors — the problem MCP was born to solve.',
    prerequisiteLessonIds: ['w9-l6'],
    nextLessonId: 'w10-l2',
  },
  {
    id: 'w10-l2', worldId: W, order: 2,
    title: 'What Is the Model Context Protocol?',
    subtitle: 'One standard, one common language',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 60, coins: 6,
    description: 'MCP is an open standard that lets any AI app and any tool connect in one common way — no more custom wiring.',
    explanation: 'A protocol is just an agreed set of rules for how two sides talk. MCP is an open protocol for AI: follow it once, and your app or tool can connect to everything else that speaks it.',
    realWorld: 'MCP is like a USB-C port for AI — one standard plug so any AI app can connect to any tool or data source, instead of a unique cable for every pairing.',
    objectives: [
      'Define MCP as an open standard',
      'Explain how a shared protocol removes custom wiring',
      'Connect MCP to the USB-C analogy',
    ],
    activity: {
      kind: 'bucket',
      title: 'What MCP Is (and Isn’t)',
      instructions: 'Sort each statement into what MCP is versus what it is not.',
      config: {
        buckets: ['What MCP is', 'What MCP is NOT'],
        items: [
          { label: 'An open standard', bucket: 0 },
          { label: 'A common language between apps and tools', bucket: 0 },
          { label: 'A way to reuse one connector everywhere', bucket: 0 },
          { label: 'A smarter AI model', bucket: 1 },
          { label: 'A programming language', bucket: 1 },
          { label: 'A brand of laptop', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'MCP is an open standard — a shared protocol for AI apps and tools.',
      'It replaces custom wiring with one common language.',
      'Like USB-C, it’s one plug for connecting anything to anything.',
    ],
    commonMistakes: [
      'Thinking MCP makes the AI model itself smarter — it’s the connection layer, not the brain.',
      'Assuming MCP is a product one company controls, rather than an open standard.',
    ],
    summary: 'MCP is the open, common language that lets AI apps and tools connect without bespoke connectors.',
    prerequisiteLessonIds: ['w10-l1'],
    nextLessonId: 'w10-l3',
  },
  {
    id: 'w10-l3', worldId: W, order: 3,
    title: 'Servers, Clients & Tools',
    subtitle: 'The three words that explain all of MCP',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 8,
    description: 'MCP has just three core roles: servers expose tools and data, and clients — the AI apps — use them.',
    explanation: 'A server offers capabilities: tools (actions the AI can call) and data (context it can read). A client lives inside the AI app and connects to servers to use those tools. That’s the whole cast.',
    realWorld: 'Think of a server as a wall socket offering power (tools), and the client as the device that plugs in to use it. The AI app decides what to plug into and when.',
    objectives: [
      'Define MCP server, client and tool',
      'Explain who exposes capabilities and who uses them',
      'Recognise these roles in real examples',
    ],
    activity: {
      kind: 'bucket',
      title: 'Server, Client or Tool?',
      instructions: 'Sort each item into the MCP role it plays.',
      config: {
        buckets: ['Server', 'Client', 'Tool'],
        items: [
          { label: 'A files MCP server', bucket: 0 },
          { label: 'A database MCP server', bucket: 0 },
          { label: 'The AI chat app', bucket: 1 },
          { label: 'An AI coding assistant', bucket: 1 },
          { label: '“search_files” action', bucket: 2 },
          { label: '“query_database” action', bucket: 2 },
        ],
      },
    },
    keyTakeaways: [
      'Server = exposes tools and data.',
      'Client = the AI app that connects and uses them.',
      'Tool = a concrete action the AI can invoke.',
    ],
    commonMistakes: [
      'Thinking the AI model lives on the server — it’s on the client side.',
      'Assuming one client can only use one server — it can use many at once.',
    ],
    summary: 'Servers offer tools and data, clients (AI apps) use them — that vocabulary unlocks the rest of MCP.',
    prerequisiteLessonIds: ['w10-l2'],
    nextLessonId: 'w10-l4',
  },
  {
    id: 'w10-l4', worldId: W, order: 4,
    title: 'How MCP Connects Everything',
    subtitle: 'The connect-and-call handshake',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 75, coins: 10,
    description: 'Every MCP interaction follows one simple flow: connect, discover the tools, call one with inputs, get a result back.',
    explanation: 'The client connects to a server, then asks what tools it offers. The server replies with a list. The client picks a tool, calls it with the needed inputs, and the server runs it and returns the result. Same handshake, every time.',
    realWorld: 'It’s like plugging into a USB-C hub: connect, see which ports (tools) are available, use the one you need, and get back what it provides.',
    objectives: [
      'Order the connect → discover → call → result flow',
      'Explain why tool discovery matters',
      'See how one flow works for every server',
    ],
    activity: {
      kind: 'steps',
      title: 'The MCP Handshake',
      instructions: 'Drag the steps into the order a client uses to connect to an MCP server and call a tool.',
      config: {
        steps: [
          'Client connects to the MCP server',
          'Client asks the server what tools it offers',
          'Server sends back its list of available tools',
          'Client calls a chosen tool with inputs',
          'Server runs the tool and returns the result',
        ],
      },
    },
    keyTakeaways: [
      'The flow is always: connect → discover → call → result.',
      'Discovery lets the client learn what tools exist, no guessing.',
      'One shared flow means one code path works for every server.',
    ],
    commonMistakes: [
      'Trying to call a tool before connecting — the flow always starts with connecting.',
      'Assuming the client must hard-code every tool, instead of discovering them.',
    ],
    summary: 'Connect, discover, call, return — this one handshake powers every MCP interaction.',
    prerequisiteLessonIds: ['w10-l3'],
    nextLessonId: 'w10-l5',
  },
  {
    id: 'w10-l5', worldId: W, order: 5,
    title: 'MCP in Practice',
    subtitle: 'Files, databases, the web and calendars — plugged in',
    difficulty: 'advanced', estimatedMinutes: 7, xp: 75, coins: 10,
    description: 'See MCP at work: real servers that let an AI app read files, query databases, search the web and manage your calendar.',
    explanation: 'Each capability is just another MCP server. A files server exposes read and search tools; a database server exposes query tools; a web server exposes search; a calendar server manages events. One app can plug in all of them at once.',
    realWorld: 'Ask your AI to “find my budget file and add a meeting to review it Friday.” It uses a files server to find the file and a calendar server to book the meeting — two tools, one request.',
    objectives: [
      'Name common MCP servers and what they enable',
      'See how one app combines several servers',
      'Understand how new capabilities are added',
    ],
    activity: {
      kind: 'bucket',
      title: 'Which Server Does the Job?',
      instructions: 'Match each task to the kind of MCP server that handles it.',
      config: {
        buckets: ['Files server', 'Database server', 'Web server', 'Calendar server'],
        items: [
          { label: 'Search a document', bucket: 0 },
          { label: 'Read a report file', bucket: 0 },
          { label: 'Query customer records', bucket: 1 },
          { label: 'Look up fresh news online', bucket: 2 },
          { label: 'Add a meeting Friday', bucket: 3 },
          { label: 'List this week’s events', bucket: 3 },
        ],
      },
    },
    keyTakeaways: [
      'Files, database, web and calendar servers each plug a real capability in.',
      'One AI app can combine many servers through the same flow.',
      'New powers come from adding new servers — no retraining needed.',
    ],
    commonMistakes: [
      'Thinking the AI must be retrained to gain a new capability, instead of adding a server.',
      'Assuming each server needs its own special flow — they all share the same one.',
    ],
    summary: 'Real MCP servers plug files, data, the web and calendars into an AI app — all via one standard flow.',
    prerequisiteLessonIds: ['w10-l4'],
    nextLessonId: 'w10-l6',
  },
  {
    id: 'w10-l6', worldId: W, order: 6,
    title: 'The Future: A Universal AI Interface',
    subtitle: 'Why one standard changes everything',
    difficulty: 'advanced', estimatedMinutes: 7, xp: 80, coins: 12,
    description: 'One open standard turns the old N×M mess into a growing ecosystem where every AI app can plug into every tool.',
    explanation: 'With a shared standard, each new tool makes every app more capable, and each new app makes tools worth building — a network effect. Being open lets the ecosystem grow without gatekeepers.',
    realWorld: 'MCP is USB-C for AI. Just as one plug ended the charger chaos, one standard aims to end integration chaos — build once, connect to everything.',
    objectives: [
      'Explain why one standard matters',
      'Describe the network effect of a growing ecosystem',
      'Contrast the universal interface with the old N×M mess',
    ],
    activity: {
      kind: 'sequence',
      title: 'From Mess to Ecosystem',
      instructions: 'Given the story so far, guess what comes next as the standard spreads.',
      config: {
        shown: ['Custom N×M wiring', 'One open standard (MCP)', 'Tools and apps interoperate'],
        options: [
          'A growing ecosystem where each new tool helps every app',
          'Even more custom, non-reusable connectors',
          'No connections at all',
          'The AI model becomes conscious',
        ],
        correctIndex: 0,
        reveal: 'Once tools and apps interoperate, every addition benefits the whole — that network effect grows the ecosystem.',
      },
    },
    keyTakeaways: [
      'One open standard means build once, connect everywhere.',
      'Network effects: each new tool or app helps the whole ecosystem.',
      'MCP is the plug between AI and the world — not a replacement for the model.',
    ],
    commonMistakes: [
      'Thinking a universal interface replaces the AI model — it connects it, not replaces it.',
      'Underestimating the network effect — the value grows with every new server and app.',
    ],
    summary: 'A single open standard turns integration chaos into a growing, universal interface for AI.',
    prerequisiteLessonIds: ['w10-l5'],
    nextLessonId: 'w11-l1',
  },
];

export const WORLD10_QUESTIONS: Question[] = [
  ...w10l1Q, ...w10l2Q, ...w10l3Q,
  ...w10l4Q, ...w10l5Q, ...w10l6Q,
];
