import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 8 — Retrieval Augmented Generation (RAG). Full lessons + question bank.
 * Follows the world1.ts reference template exactly.
 */

const W = 'world-rag';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — Why Models Need Extra Knowledge
 * ================================================================== */
const l1 = bank('w8-l1', 'intermediate');
const w8l1Q: Question[] = [
  l1.mc('knowledge-gap', 'Why can’t a language model answer a question about your company’s private documents?',
    ['It was never trained on your private data, so it simply doesn’t know it',
     'It refuses on purpose to protect you',
     'Private documents are too small to matter',
     'Models can read any file on your computer automatically'],
    0, 'A model only knows what was in its training data. Your private files were never part of that, so the information isn’t there.'),
  l1.tf('cutoff', 'A model’s knowledge stops at the point its training data ended.', true,
    'This is the “knowledge cutoff”. Anything that happened after training — or was never public — is outside what the model knows.'),
  l1.mc('latest-info', 'You ask a model about a news event from this morning. What’s the likely problem?',
    ['The event is newer than the model’s training data, so it can’t know it',
     'The model is broken',
     'News is never in any training data',
     'The question was too short'],
    0, 'Fresh, recent information often falls after the training cutoff, so the model has no memory of it.', 'scenario'),
  l1.mc('hallucinate', 'When a model doesn’t know an answer but responds anyway, it may…',
    ['Make up a confident but false answer (a hallucination)',
     'Always say “I don’t know”',
     'Shut itself off',
     'Email the correct answer to an expert'],
    0, 'Without the right facts, models can invent plausible-sounding but wrong answers. Giving them real data helps prevent this.'),
  l1.tf('retrain-cost', 'Retraining a whole model every time your documents change is fast and cheap.', false,
    'Retraining is slow and expensive. That’s a big reason we look for ways to add knowledge without retraining.'),
  l1.match('gaps', 'Match each knowledge gap to its cause.',
    [{ left: 'Private company files', right: 'Never in the public training data' },
     { left: 'This week’s news', right: 'Newer than the training cutoff' },
     { left: 'Your personal notes', right: 'Not shared with the model' }],
    'All three gaps share one root cause: the information simply wasn’t part of what the model learned from.'),
  l1.mc('general-vs-specific', 'A general model is great at language but weak at…',
    ['Specific, private or very recent facts it never saw',
     'Forming grammatical sentences',
     'Summarising ideas',
     'Answering common general-knowledge questions'],
    0, 'Models excel at language patterns learned broadly, but struggle with narrow facts outside their training data.'),
  l1.tf('memorise-all', 'It’s realistic to train one model to memorise every document in the world.', false,
    'No model can hold everything, and the world keeps changing. Looking information up on demand is far more practical.'),
  l1.mc('better-approach', 'What’s a smarter fix than retraining for private or fresh knowledge?',
    ['Give the model the relevant information at question time',
     'Ask users to memorise the answers',
     'Delete the question',
     'Wait a year for the next model'],
    0, 'Instead of baking knowledge in, we can fetch the right facts and hand them to the model right when it needs them.'),
  l1.mc('why-matters', 'Closing the knowledge gap matters most when you need…',
    ['Accurate answers grounded in your own, up-to-date data',
     'Longer sentences',
     'A prettier interface',
     'The model to run slower'],
    0, 'The whole point is trustworthy, current, specific answers — which a general model alone can’t reliably give.'),
  l1.tf('cutoff-known', 'Knowing a model has a knowledge cutoff helps you judge when to feed it extra data.', true,
    'Recognising the gap is the first step. Once you see it, you can decide when the model needs outside help.'),
  l1.mc('scenario-support', 'A support bot must answer using this month’s updated policy PDF. Best plan?',
    ['Supply the relevant policy text to the model when it answers',
     'Hope the model guesses the new policy',
     'Retrain the model from scratch nightly',
     'Tell customers to read the PDF themselves'],
    0, 'Handing the model the current policy text at answer time is fast, accurate and always up to date.', 'scenario'),
];

/* ================================================================== *
 * Lesson 2 — What Is Retrieval Augmented Generation?
 * ================================================================== */
const l2 = bank('w8-l2', 'intermediate');
const w8l2Q: Question[] = [
  l2.mc('definition', 'What does Retrieval Augmented Generation (RAG) do?',
    ['Fetches relevant information first, then lets the model answer using it',
     'Trains a brand-new model for every question',
     'Deletes the model’s knowledge',
     'Answers only from memory, ignoring documents'],
    0, 'RAG = retrieve the right info, then generate an answer grounded in it. Fetch first, answer second.'),
  l2.tf('no-retrain', 'RAG adds fresh knowledge without retraining the model.', true,
    'That’s the big win: you update the documents, not the model. New info is available immediately.'),
  l2.mc('two-parts', 'The two core steps in RAG are…',
    ['Retrieval (find relevant info) and generation (write the answer)',
     'Training and deleting',
     'Encrypting and compressing',
     'Guessing and hoping'],
    0, 'The name says it: Retrieval + Augmented Generation. Find, then generate an answer augmented by what you found.'),
  l2.mc('open-book', 'RAG is most like…',
    ['An open-book exam — look up the facts, then answer',
     'A closed-book exam from memory only',
     'Copying a friend’s answer',
     'Leaving the exam blank'],
    0, 'Instead of relying on memory, the model gets to “open the book” of your documents and answer from what it reads.'),
  l2.tf('augment', 'The “augmented” part means the model’s prompt is enriched with retrieved information.', true,
    'We augment (add to) the prompt with relevant text, so the model answers using that context rather than memory alone.'),
  l2.match('vocab', 'Match each RAG term to its meaning.',
    [{ left: 'Retrieval', right: 'Finding relevant information' },
     { left: 'Augmented', right: 'Adding that info to the prompt' },
     { left: 'Generation', right: 'The model writing the answer' }],
    'Retrieve the facts, augment the prompt with them, then generate the grounded answer — that’s RAG in three words.'),
  l2.mc('why-use', 'A key reason teams choose RAG is that it…',
    ['Lets the model answer from private or fresh data it wasn’t trained on',
     'Makes the model forget everything',
     'Removes the need for any documents',
     'Slows the model down on purpose'],
    0, 'RAG bridges the knowledge gap: the model can now answer from your specific, current data.'),
  l2.tf('replace-model', 'RAG replaces the language model entirely.', false,
    'RAG works with the model, not instead of it. The model still writes the answer — it just gets helpful context first.'),
  l2.mc('grounded', 'Because RAG feeds the model real text, its answers are more…',
    ['Grounded in actual sources, so fewer made-up facts',
     'Random and unpredictable',
     'Likely to be blank',
     'Expensive to read'],
    0, 'Answers backed by retrieved text are more trustworthy — the model has real material to lean on instead of guessing.'),
  l2.mc('scenario-docs', 'A team has 10,000 internal wiki pages. They want a bot that answers from them. RAG helps by…',
    ['Retrieving the few relevant pages, then answering from those',
     'Reading all 10,000 pages into every prompt',
     'Memorising the wiki inside the model',
     'Ignoring the wiki completely'],
    0, 'RAG fetches only the handful of pages that matter for the question, keeping answers focused and grounded.', 'scenario'),
  l2.tf('update-easy', 'To update a RAG system’s knowledge, you usually just update the documents.', true,
    'Change or add documents and the system retrieves the new info next time — no model retraining required.'),
  l2.mc('summary', 'In one line, RAG is best summarised as…',
    ['Look it up, then answer using what you found',
     'Answer purely from memory',
     'Train a new model per question',
     'Never use documents'],
    0, 'Fetch relevant info, then generate a grounded answer. That simple loop is the heart of RAG.'),
];

/* ================================================================== *
 * Lesson 3 — The RAG Pipeline
 * ================================================================== */
const l3 = bank('w8-l3', 'intermediate');
const w8l3Q: Question[] = [
  l3.order('answer-flow', 'Put the answer-time RAG flow in order.',
    ['User asks a question', 'Turn the question into an embedding', 'Retrieve the most relevant chunks', 'Add those chunks to the prompt', 'Model generates a grounded answer'],
    'At answer time: take the question, embed it, retrieve matching chunks, add them to the prompt, then generate the answer.'),
  l3.mc('two-phases', 'The RAG pipeline has two phases. What are they?',
    ['Preparing documents ahead of time, and answering at question time',
     'Training and deleting',
     'Only answering, never preparing',
     'Encrypting and decrypting'],
    0, 'First you prep documents (chunk, embed, store). Later, per question, you retrieve and generate. Prep once, answer many times.'),
  l3.order('prep-flow', 'Put the document-prep phase in order.',
    ['Split documents into chunks', 'Turn each chunk into an embedding', 'Store the embeddings in a vector database'],
    'Preparation is chunk → embed → store. Once documents are indexed this way, they’re ready to be retrieved later.'),
  l3.tf('embed-both', 'Both the stored chunks and the incoming question are turned into embeddings.', true,
    'Retrieval works by comparing the question’s embedding to the chunk embeddings — so both sides must be embedded.'),
  l3.match('stages', 'Match each pipeline stage to what it does.',
    [{ left: 'Chunk', right: 'Split documents into pieces' },
     { left: 'Embed', right: 'Turn text into number vectors' },
     { left: 'Retrieve', right: 'Find the closest chunks to the question' }],
    'Chunking breaks text up, embedding turns it into vectors, and retrieval finds the chunks nearest the question.'),
  l3.mc('retrieve-how', 'How does retrieval decide which chunks are “relevant”?',
    ['By finding chunk embeddings closest in meaning to the question’s embedding',
     'By picking chunks at random',
     'By choosing the longest chunks',
     'By alphabetical order'],
    0, 'Embeddings capture meaning, so chunks whose vectors are nearest the question are the most relevant matches.'),
  l3.tf('store-once', 'You must re-chunk and re-embed every document for each new question.', false,
    'Preparation happens once. After documents are chunked, embedded and stored, every question just retrieves from that index.'),
  l3.mc('vector-db', 'What is the vector database’s job in RAG?',
    ['Store chunk embeddings and quickly find the closest ones',
     'Write the final answer',
     'Train the language model',
     'Display the user interface'],
    0, 'The vector store holds embeddings and does fast similarity search — returning the chunks nearest the question.'),
  l3.mc('generate-step', 'In the final step, the model generates an answer using…',
    ['The user’s question plus the retrieved chunks in its prompt',
     'Only its training memory, ignoring the chunks',
     'A random document',
     'Nothing at all'],
    0, 'The retrieved chunks are added to the prompt so the model answers grounded in that specific, relevant context.'),
  l3.tf('order-matters', 'You must retrieve relevant chunks before the model can generate a grounded answer.', true,
    'Generation depends on retrieval. The model needs the fetched context in its prompt before it can answer from it.'),
  l3.mc('scenario-slow', 'A RAG bot feels slow because it re-embeds all documents on every question. The fix?',
    ['Embed and store documents once, up front, then only embed each question',
     'Embed the documents twice for safety',
     'Never embed anything',
     'Retrain the model each time'],
    0, 'Document embedding belongs to the one-time prep phase. At answer time you only embed the single incoming question.', 'scenario'),
  l3.mc('big-picture', 'The full RAG pipeline in order is…',
    ['Chunk → embed → store → retrieve → generate',
     'Generate → retrieve → store → embed → chunk',
     'Store → generate → chunk → retrieve → embed',
     'Embed → generate → chunk → store → retrieve'],
    0, 'Prepare (chunk, embed, store), then answer (retrieve, generate). Learning this order is the key to RAG.'),
];

/* ================================================================== *
 * Lesson 4 — Chunking Your Documents
 * ================================================================== */
const l4 = bank('w8-l4', 'intermediate');
const w8l4Q: Question[] = [
  l4.mc('what-chunk', 'What does “chunking” mean in RAG?',
    ['Splitting documents into smaller, searchable pieces',
     'Deleting half of every document',
     'Combining all documents into one giant file',
     'Translating documents to another language'],
    0, 'Chunking breaks long documents into bite-sized pieces so retrieval can find and return just the relevant parts.'),
  l4.tf('why-chunk', 'We chunk so retrieval can return small, focused pieces instead of whole documents.', true,
    'Feeding a whole book into the prompt is wasteful and confusing. Small chunks let you fetch just what’s relevant.'),
  l4.mc('too-big', 'What’s a problem with chunks that are too large?',
    ['They mix many topics, so retrieval is less precise and prompts get bloated',
     'They are always more accurate',
     'They can’t be embedded',
     'They make the model faster'],
    0, 'Big chunks bundle unrelated ideas together, blurring relevance and wasting space in the prompt.'),
  l4.mc('too-small', 'What’s a problem with chunks that are too small?',
    ['They may lose context and cut ideas in half',
     'They are always the best choice',
     'They contain too much information',
     'They can never be stored'],
    0, 'Tiny chunks can split a single idea across pieces, so a retrieved chunk lacks the context needed to be useful.'),
  l4.tf('goldilocks', 'A good chunk size is “just right” — big enough for context, small enough to stay focused.', true,
    'Chunk size is a balance. You want each chunk to hold one coherent idea with enough surrounding context.'),
  l4.match('sizes', 'Match each chunk size to its main risk.',
    [{ left: 'Too large', right: 'Mixes topics, bloats the prompt' },
     { left: 'Too small', right: 'Loses context, splits ideas' },
     { left: 'Just right', right: 'One focused idea with context' }],
    'Both extremes hurt retrieval quality. The sweet spot keeps each chunk coherent and self-contained.'),
  l4.mc('overlap', 'Why do some systems overlap chunks slightly at their edges?',
    ['So an idea spanning a boundary isn’t cut off from its context',
     'To waste storage on purpose',
     'To make chunks identical',
     'To avoid embedding them'],
    0, 'A little overlap means a sentence near the edge still appears with its surrounding context in a neighbouring chunk.'),
  l4.tf('one-size', 'There is one perfect chunk size that works for every document and use case.', false,
    'The best size depends on the content and task. Chunking is something you tune, not a single universal number.'),
  l4.mc('boundaries', 'A sensible place to split a document into chunks is…',
    ['At natural boundaries like paragraphs or sections',
     'In the middle of random words',
     'Exactly every 3 characters',
     'Only at the very end'],
    0, 'Splitting on paragraphs or sections keeps each chunk’s meaning intact, which makes retrieval far more reliable.'),
  l4.mc('scenario-manual', 'A 300-page manual is stored as one huge chunk and retrieval is useless. The fix?',
    ['Split it into many smaller, topic-focused chunks',
     'Store it as an even bigger single chunk',
     'Stop using the manual',
     'Embed only its title'],
    0, 'One giant chunk can’t pinpoint a specific answer. Breaking it into focused pieces lets retrieval find the right section.', 'scenario'),
  l4.tf('quality-in', 'Good chunking directly improves how relevant your retrieved results are.', true,
    'Retrieval can only return the chunks you created. Thoughtful chunks in means relevant, useful results out.'),
  l4.mc('takeaway', 'The main goal of chunking is to…',
    ['Make documents searchable in focused, context-rich pieces',
     'Make documents as long as possible',
     'Hide documents from the model',
     'Remove all punctuation'],
    0, 'Well-sized chunks are the foundation of good retrieval — they decide what the model can actually find and use.'),
];

/* ================================================================== *
 * Lesson 5 — Grounding & Citing Sources
 * ================================================================== */
const l5 = bank('w8-l5', 'intermediate');
const w8l5Q: Question[] = [
  l5.mc('grounding', 'What does “grounding” an answer mean?',
    ['Basing the answer on retrieved source text, not just the model’s memory',
     'Turning the answer off',
     'Making the answer longer',
     'Hiding where the answer came from'],
    0, 'A grounded answer stands on real retrieved text, so it reflects actual sources rather than the model’s guesses.'),
  l5.tf('fewer-halluc', 'Grounding answers in retrieved text reduces hallucinations.', true,
    'When the model answers from real supplied text, it has less need to invent facts — so made-up answers drop.'),
  l5.mc('citation', 'Why add citations that point to the retrieved sources?',
    ['So users can verify the answer and trust where it came from',
     'To make the answer harder to read',
     'To hide the sources',
     'Because citations slow the model down'],
    0, 'Citations let people check the source. That transparency builds trust and makes errors easy to catch.'),
  l5.mc('verify', 'A big benefit of citing sources in a RAG answer is that users can…',
    ['Click through and confirm the claim in the original document',
     'Never see any source',
     'Only read the model’s opinion',
     'Avoid reading anything'],
    0, 'A citation is a receipt. It shows exactly which document backs the claim, so users can verify it themselves.'),
  l5.tf('still-check', 'Even with grounding and citations, important answers should still be reviewed.', true,
    'Grounding cuts errors but doesn’t eliminate them. For high-stakes uses, a human should still verify the result.'),
  l5.match('benefits', 'Match each practice to its benefit.',
    [{ left: 'Grounding', right: 'Fewer made-up facts' },
     { left: 'Citations', right: 'Users can verify the source' },
     { left: 'Human review', right: 'Catches remaining mistakes' }],
    'Grounding lowers hallucinations, citations enable verification, and review is the final safety net.'),
  l5.mc('no-source', 'If the retrieved chunks don’t contain the answer, a well-designed RAG system should…',
    ['Say it doesn’t have enough information rather than invent an answer',
     'Make up a confident answer anyway',
     'Return a random document',
     'Crash'],
    0, 'Honesty beats guessing. If the sources lack the answer, admitting so is safer than fabricating one.'),
  l5.tf('grounding-truth', 'Grounding guarantees the answer is always 100% correct.', false,
    'Grounding greatly helps, but sources can be outdated or wrong, and the model can still misread them. It reduces, not removes, errors.'),
  l5.mc('trust', 'For a medical or legal RAG assistant, citations matter because…',
    ['Experts must verify claims against trusted sources before acting',
     'They look decorative',
     'They make answers longer for no reason',
     'They replace the need for experts'],
    0, 'In high-stakes fields, traceable sources let a human expert confirm each claim — essential for safe use.', 'scenario'),
  l5.mc('scenario-bad', 'A bot cites a source, but the cited page doesn’t actually support the claim. This shows…',
    ['Citations must be checked — grounding can still be sloppy or wrong',
     'Citations are useless and should be removed',
     'The user made a mistake',
     'The model is perfect'],
    0, 'A citation is only as good as its accuracy. Mismatched citations are a red flag that the answer needs review.', 'scenario'),
  l5.tf('transparency', 'Showing sources makes a RAG system more transparent and trustworthy.', true,
    'Visible sources turn a black-box answer into something users can inspect, question and trust appropriately.'),
];

/* ================================================================== *
 * Lesson 6 — RAG vs Fine-Tuning
 * ================================================================== */
const l6 = bank('w8-l6', 'advanced');
const w8l6Q: Question[] = [
  l6.mc('rag-when', 'RAG is the better choice when you need…',
    ['Answers from knowledge that changes often or is private',
     'To change the model’s writing style permanently',
     'To make the model forget everything',
     'To avoid using any documents'],
    0, 'RAG shines for facts that change or must stay current — you update documents, not the model.'),
  l6.mc('ft-when', 'Fine-tuning is the better choice when you need…',
    ['To teach the model a new style, format or skill baked into its behaviour',
     'To add today’s breaking news',
     'To swap documents constantly',
     'To avoid training entirely'],
    0, 'Fine-tuning adjusts the model itself — good for changing how it behaves, not for feeding fast-changing facts.'),
  l6.tf('rag-fresh', 'RAG makes it easy to keep knowledge fresh by updating documents.', true,
    'Because RAG looks things up at answer time, new or edited documents take effect immediately — no retraining.'),
  l6.tf('ft-fresh', 'Fine-tuning is a fast, cheap way to add breaking-news facts every hour.', false,
    'Fine-tuning is slow and costly to repeat. For rapidly changing facts, RAG’s look-it-up approach fits far better.'),
  l6.match('choose', 'Match each need to the better approach.',
    [{ left: 'Latest private data', right: 'RAG (look it up)' },
     { left: 'A consistent tone or format', right: 'Fine-tuning (retrain behaviour)' },
     { left: 'Frequently changing facts', right: 'RAG (update documents)' }],
    'RAG handles changing knowledge; fine-tuning shapes lasting behaviour. Match the tool to what actually needs to change.'),
  l6.mc('tradeoff-rag', 'A trade-off of RAG is that…',
    ['Answer quality depends heavily on retrieval finding the right chunks',
     'It permanently changes the model’s weights',
     'It can never use private data',
     'It ignores documents entirely'],
    0, 'If retrieval misses the relevant chunk, the answer suffers. Good chunking and search are essential for RAG.'),
  l6.mc('tradeoff-ft', 'A trade-off of fine-tuning is that…',
    ['It’s costly to redo, and new facts require retraining',
     'It updates instantly with no effort',
     'It never changes model behaviour',
     'It requires no data'],
    0, 'Fine-tuning bakes knowledge in, so keeping it current means retraining again — expensive and slow.'),
  l6.tf('combine', 'RAG and fine-tuning can be used together.', true,
    'They’re not rivals. You might fine-tune for style and use RAG for facts — combining behaviour and fresh knowledge.'),
  l6.mc('scenario-policy', 'A company’s policies change weekly and must be answered accurately. Best approach?',
    ['RAG — retrieve the current policy documents at answer time',
     'Fine-tune the model every week',
     'Do nothing and hope',
     'Ask staff to memorise all policies'],
    0, 'Weekly-changing facts are a classic RAG case: update the documents and answers stay current, no retraining needed.', 'scenario'),
  l6.mc('scenario-style', 'A brand wants every reply in its exact tone and format, regardless of topic. Best approach?',
    ['Fine-tune the model to internalise that style',
     'Retrieve style examples for every single question',
     'Change the documents weekly',
     'Ignore the brand guidelines'],
    0, 'A consistent, always-on behaviour is best baked into the model through fine-tuning rather than retrieved each time.', 'scenario'),
  l6.mc('summary', 'The clearest rule of thumb is…',
    ['Look it up (RAG) for knowledge; retrain (fine-tune) for behaviour',
     'Always fine-tune, never use RAG',
     'Always use RAG, never fine-tune',
     'Avoid both and guess'],
    0, 'RAG for what the model needs to know, fine-tuning for how it should behave. Pick — or combine — based on what must change.'),
  l6.tf('understand', 'Knowing when to use RAG versus fine-tuning helps you design better, cheaper AI systems.', true,
    'Matching the right tool to the problem saves cost and improves quality — the mark of thoughtful AI design.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD8_LESSONS: Lesson[] = [
  {
    id: 'w8-l1', worldId: W, order: 1,
    title: 'Why Models Need Extra Knowledge',
    subtitle: 'The knowledge gap, explained',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 60, coins: 6,
    description: 'A language model only knows what it was trained on. Your private files and today’s news simply aren’t in there — that’s the knowledge gap.',
    realWorld: 'Ask a brilliant friend about your company’s internal policy and they’ll shrug — they never read it. A model is the same: smart, but blind to what it never saw.',
    objectives: [
      'Explain the model knowledge cutoff',
      'Identify private and recent info a model can’t know',
      'See why feeding data beats constant retraining',
    ],
    activity: {
      kind: 'bucket',
      title: 'Knows It or Needs It?',
      instructions: 'Sort each question. Which can a general model likely answer, and which needs your extra data?',
      config: {
        buckets: ['Model likely knows', 'Needs extra data'],
        items: [
          { label: 'What is the capital of France?', bucket: 0 },
          { label: 'Define “photosynthesis”', bucket: 0 },
          { label: 'Basic grammar rules', bucket: 0 },
          { label: 'Our company’s refund policy', bucket: 1 },
          { label: 'This morning’s news', bucket: 1 },
          { label: 'Notes from your private journal', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'A model only knows what was in its training data.',
      'Private and very recent info fall into the knowledge gap.',
      'Feeding relevant data on demand beats costly retraining.',
    ],
    commonMistakes: [
      'Assuming a model automatically knows your private documents.',
      'Trusting confident answers about events after the training cutoff.',
      'Thinking retraining is the only way to add new knowledge.',
    ],
    summary: 'Models are limited to their training data — closing that gap is what the rest of this world is about.',
    prerequisiteLessonIds: ['w7-l6'],
    nextLessonId: 'w8-l2',
  },
  {
    id: 'w8-l2', worldId: W, order: 2,
    title: 'What Is Retrieval Augmented Generation?',
    subtitle: 'Fetch first, then answer',
    difficulty: 'intermediate', estimatedMinutes: 6, xp: 65, coins: 8,
    description: 'RAG closes the knowledge gap: it fetches the relevant information, then lets the model answer using it — no retraining needed.',
    realWorld: 'It’s an open-book exam. Instead of answering from memory, the model gets to look up the right pages in your documents first, then answer.',
    objectives: [
      'Define RAG in one clear sentence',
      'Name its two steps: retrieval and generation',
      'Explain why RAG adds knowledge without retraining',
    ],
    activity: {
      kind: 'sequence',
      title: 'The RAG Idea',
      instructions: 'Given the two core steps of RAG so far, what comes next?',
      config: {
        shown: ['Retrieve relevant information', 'Add it to the prompt'],
        options: ['Generate a grounded answer', 'Delete the documents', 'Retrain the model', 'Ignore the information'],
        correctIndex: 0,
        reveal: 'RAG = retrieve, augment the prompt, then generate. The model answers using the info you just fetched.',
      },
    },
    keyTakeaways: [
      'RAG = fetch relevant info, then answer using it.',
      'It works with the model, not instead of it.',
      'Update the documents to update the knowledge — no retraining.',
    ],
    commonMistakes: [
      'Thinking RAG replaces the language model.',
      'Assuming RAG needs the model to be retrained.',
      'Confusing “augmented” with changing the model itself.',
    ],
    summary: 'RAG is “look it up, then answer” — a simple, powerful way to ground a model in your data.',
    prerequisiteLessonIds: ['w8-l1'],
    nextLessonId: 'w8-l3',
  },
  {
    id: 'w8-l3', worldId: W, order: 3,
    title: 'The RAG Pipeline',
    subtitle: 'Chunk, embed, store, retrieve, generate',
    difficulty: 'intermediate', estimatedMinutes: 8, xp: 70, coins: 10,
    description: 'RAG runs in two phases: prepare documents once (chunk, embed, store), then answer each question (retrieve, generate). Learn the full flow.',
    realWorld: 'A librarian first indexes every book (prep), then for each visitor finds the right pages and hands them over to read from (answer). RAG works the same way.',
    objectives: [
      'Separate the prep phase from the answer phase',
      'Order the full pipeline end to end',
      'Explain how retrieval matches questions to chunks',
    ],
    activity: {
      kind: 'steps',
      title: 'Build the RAG Pipeline',
      instructions: 'Drag the answer-time steps into the order RAG actually runs.',
      config: {
        steps: [
          'User asks a question',
          'Turn the question into an embedding',
          'Retrieve the most relevant chunks',
          'Add those chunks to the prompt',
          'Model generates a grounded answer',
        ],
      },
    },
    keyTakeaways: [
      'Prep once: chunk → embed → store in a vector database.',
      'Answer each time: embed question → retrieve chunks → generate.',
      'Retrieval finds chunks whose meaning is closest to the question.',
    ],
    commonMistakes: [
      'Re-embedding all documents on every question instead of once up front.',
      'Forgetting the question itself must also be embedded.',
      'Trying to generate an answer before retrieving relevant chunks.',
    ],
    summary: 'Prepare documents once, then retrieve and generate per question — that’s the RAG pipeline in a nutshell.',
    prerequisiteLessonIds: ['w8-l2'],
    nextLessonId: 'w8-l4',
  },
  {
    id: 'w8-l4', worldId: W, order: 4,
    title: 'Chunking Your Documents',
    subtitle: 'Splitting docs into searchable pieces',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Before retrieval can find anything, documents must be split into chunks. Chunk size quietly decides how good your results will be.',
    realWorld: 'Imagine indexing a book by whole chapters versus by paragraphs. Paragraph-sized pieces let you point to the exact answer instead of a vague chapter.',
    objectives: [
      'Explain what chunking is and why it matters',
      'Weigh the risks of chunks that are too big or too small',
      'Pick sensible boundaries for splitting documents',
    ],
    activity: {
      kind: 'slider',
      title: 'Chunk Size Simulator',
      instructions: 'Slide to change the chunk size and see how it affects retrieval quality.',
      config: {
        min: 0, max: 100, step: 5, valueLabel: 'Chunk size',
        stops: [
          { upTo: 15, title: 'Very small', detail: 'Ideas get split apart — chunks lose context and mislead retrieval.' },
          { upTo: 55, title: 'Just right', detail: 'Each chunk holds one focused idea with enough context. Retrieval is sharp.' },
          { upTo: 80, title: 'Getting large', detail: 'Chunks start mixing topics; relevance and precision begin to slip.' },
          { upTo: 100, title: 'Too large', detail: 'One chunk bundles many topics and bloats the prompt — retrieval turns vague.' },
        ],
      },
    },
    keyTakeaways: [
      'Chunking splits documents into small, searchable pieces.',
      'Too large mixes topics; too small loses context.',
      'Split on natural boundaries like paragraphs or sections.',
    ],
    commonMistakes: [
      'Storing a whole document as one giant chunk.',
      'Chopping text so small that ideas get cut in half.',
      'Assuming one chunk size is perfect for every document.',
    ],
    summary: 'Well-sized, coherent chunks are the foundation of good retrieval — get them right and everything downstream improves.',
    prerequisiteLessonIds: ['w8-l3'],
    nextLessonId: 'w8-l5',
  },
  {
    id: 'w8-l5', worldId: W, order: 5,
    title: 'Grounding & Citing Sources',
    subtitle: 'Answers backed by real text',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 75, coins: 10,
    description: 'RAG answers should stand on the retrieved text and point back to it. Grounding means fewer made-up facts; citations let users verify.',
    realWorld: 'A good journalist doesn’t just assert things — they quote sources you can check. A grounded RAG answer does the same, showing its receipts.',
    objectives: [
      'Explain what grounding an answer means',
      'Describe how citations build trust and enable verification',
      'Recognise that review is still needed for important answers',
    ],
    activity: {
      kind: 'bucket',
      title: 'Grounded or Guessed?',
      instructions: 'Sort each answer style. Which reflects a well-grounded RAG system, and which is a red flag?',
      config: {
        buckets: ['Well-grounded', 'Red flag'],
        items: [
          { label: 'Answer quotes the retrieved source', bucket: 0 },
          { label: 'Answer links to a document you can check', bucket: 0 },
          { label: 'Says “not enough info” when sources lack it', bucket: 0 },
          { label: 'Confident claim with no source at all', bucket: 1 },
          { label: 'Cites a page that doesn’t support the claim', bucket: 1 },
          { label: 'Invents a fact to fill a gap', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Grounding bases answers on retrieved text, reducing hallucinations.',
      'Citations let users verify claims against the source.',
      'Grounding cuts errors but doesn’t remove them — review still matters.',
    ],
    commonMistakes: [
      'Trusting a grounded answer as guaranteed correct.',
      'Adding citations but never checking they actually support the claim.',
      'Letting the system invent an answer when sources lack one.',
    ],
    summary: 'Grounded, cited answers are the trust layer of RAG — they let people verify, not just believe.',
    prerequisiteLessonIds: ['w8-l4'],
    nextLessonId: 'w8-l6',
  },
  {
    id: 'w8-l6', worldId: W, order: 6,
    title: 'RAG vs Fine-Tuning',
    subtitle: 'Look it up, or retrain?',
    difficulty: 'advanced', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Two ways to give a model what it lacks: look things up (RAG) or retrain the model (fine-tuning). Knowing which fits when is a key design skill.',
    realWorld: 'RAG is handing someone a reference book to look things up. Fine-tuning is sending them to school to change how they think. Different problems, different tools.',
    objectives: [
      'Match RAG and fine-tuning to the problems they solve',
      'Weigh the trade-offs of each approach',
      'Decide when to use one, the other, or both',
    ],
    activity: {
      kind: 'bucket',
      title: 'RAG or Fine-Tune?',
      instructions: 'Sort each need. Is it better solved by looking it up (RAG) or retraining behaviour (fine-tuning)?',
      config: {
        buckets: ['Use RAG', 'Fine-tune'],
        items: [
          { label: 'Answer from this week’s private docs', bucket: 0 },
          { label: 'Facts that change frequently', bucket: 0 },
          { label: 'Cite up-to-date sources', bucket: 0 },
          { label: 'Always reply in a fixed brand tone', bucket: 1 },
          { label: 'Master a special output format', bucket: 1 },
          { label: 'Learn a consistent new skill', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'RAG for changing or private knowledge — update documents, not the model.',
      'Fine-tuning for lasting behaviour — style, format, skill.',
      'They can be combined: fine-tune for behaviour, RAG for facts.',
    ],
    commonMistakes: [
      'Fine-tuning repeatedly to keep fast-changing facts current.',
      'Using RAG to force a consistent tone instead of fine-tuning.',
      'Treating the two as rivals rather than complementary tools.',
    ],
    summary: 'Look it up (RAG) for knowledge, retrain (fine-tune) for behaviour — and combine them when you need both.',
    prerequisiteLessonIds: ['w8-l5'],
    nextLessonId: 'w9-l1',
  },
];

export const WORLD8_QUESTIONS: Question[] = [
  ...w8l1Q, ...w8l2Q, ...w8l3Q,
  ...w8l4Q, ...w8l5Q, ...w8l6Q,
];
