import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 6 — Prompt Engineering. Full lessons + question bank.
 * Structure mirrors world1.ts, the reference template.
 */

const W = 'world-prompt-engineering';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — What Is a Prompt?
 * ================================================================== */
const l1 = bank('w6-l1', 'beginner');
const w6l1Q: Question[] = [
  l1.mc('definition', 'What is a “prompt” in AI?',
    ['The instruction or question you give the model to get an answer',
     'The name of the AI model',
     'A button that turns the AI on',
     'The price you pay to use the AI'],
    0, 'A prompt is simply your input — the words you send. The model reads it and produces a response based on it.'),
  l1.tf('shapes', 'The wording of your prompt affects the answer you get back.', true,
    'The prompt is the model’s only clue about what you want. Change the words and you change the output.'),
  l1.mc('control', 'Why is prompt engineering a useful skill?',
    ['A clearer prompt reliably gets you a better, more useful answer',
     'It makes the AI run on less electricity',
     'It changes the model’s training data',
     'It unlocks secret hidden models'],
    0, 'You can’t retrain the model, but you can control what you ask. Better prompts are the easiest way to better results.'),
  l1.mc('vague-scenario', 'You type “tell me about dogs” and get a rambling answer you didn’t want. The likely problem is…',
    ['The prompt was too vague — it didn’t say what you actually needed',
     'The model is broken',
     'Dogs are too complex a topic for AI',
     'You need a faster internet connection'],
    0, 'A vague prompt gives the model no target. It guesses at what you want — often wrongly.', 'scenario'),
  l1.tf('mind-reader', 'The AI can read your mind and know what you meant even if you don’t say it.', false,
    'The model only has your words. It can’t sense intent you didn’t write down — you have to spell it out.'),
  l1.mc('same-question', 'Two people ask the AI the same topic but get different answers. Most likely because…',
    ['They phrased their prompts differently',
     'The AI likes one person more',
     'One of them used a newer phone',
     'The AI ran out of answers'],
    0, 'Different wording leads to different outputs. The prompt is the steering wheel for the response.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Prompt', right: 'The instruction you give the model' },
     { left: 'Response', right: 'The answer the model produces' },
     { left: 'Prompt engineering', right: 'Writing prompts to get better answers' }],
    'You write a prompt, the model returns a response, and prompt engineering is the craft of writing good prompts.'),
  l1.mc('everyday', 'Which of these is a prompt?',
    ['“Write a three-line birthday message for my sister.”',
     'The AI’s reply about birthdays',
     'The app’s loading screen',
     'The Wi-Fi password'],
    0, 'A prompt is what you send in. The reply is the output — not the prompt.'),
  l1.tf('length', 'A prompt can be a single word or several sentences.', true,
    'Prompts have no fixed length. What matters is whether they give the model enough to work with.'),
  l1.mc('better-prompt', 'Which prompt is likely to get the more useful answer?',
    ['“Summarise this email in 2 bullet points for my boss.”',
     '“email”',
     '“stuff about the email”',
     '“do the thing”'],
    0, 'The first names the task, the format, and the audience. The others leave the model guessing.', 'identify-prompt'),
  l1.mc('point', 'The main lesson of prompting is that…',
    ['You get better answers by giving clearer instructions',
     'The AI ignores whatever you type',
     'Longer prompts are always worse',
     'Only experts can talk to AI'],
    0, 'Better in, better out. Learning to ask well is the core skill this world builds.'),
  l1.tf('skill', 'Anyone can improve their AI results by learning to write better prompts.', true,
    'Prompting is a learnable skill — no coding required. Small wording changes can make a big difference.'),
];

/* ================================================================== *
 * Lesson 2 — Clear Instructions Beat Clever Tricks
 * ================================================================== */
const l2 = bank('w6-l2', 'beginner');
const w6l2Q: Question[] = [
  l2.mc('specific', 'What makes a prompt “clear”?',
    ['It states the task, the format, and any constraints',
     'It uses the longest words possible',
     'It hides what you really want',
     'It is written in all capital letters'],
    0, 'Clarity comes from spelling out what to do, how to present it, and any limits — not from fancy language.'),
  l2.tf('specificity', 'Being specific about what you want usually improves the answer.', true,
    'The more precisely you describe the target, the closer the model can aim. Vagueness invites wrong guesses.'),
  l2.mc('format', 'Adding “answer in 3 bullet points” to a prompt is an example of specifying the…',
    ['Format', 'Model', 'Price', 'Language the AI runs in'],
    0, 'Telling the model how to shape its answer — bullets, a table, one sentence — is specifying the format.'),
  l2.mc('better-prompt', 'Which is the clearer prompt?',
    ['“Write a polite 2-sentence reply declining the meeting, suggesting Friday instead.”',
     '“reply to this”',
     '“say no nicely maybe”',
     '“meeting stuff”'],
    0, 'The first names the tone, length, task, and a key detail. The rest force the model to guess.', 'identify-prompt'),
  l2.tf('tricks', 'Clever wording tricks matter more than simply being clear about what you want.', false,
    'Clear, direct instructions almost always beat gimmicks. Say plainly what you need.'),
  l2.mc('constraint', 'A “constraint” in a prompt is…',
    ['A limit or rule the answer must follow, like a word count or tone',
     'The AI’s battery level',
     'A type of AI model',
     'A synonym for the answer'],
    0, 'Constraints keep the output in bounds: “under 50 words”, “no jargon”, “formal tone”. They shape the result.'),
  l2.match('parts', 'Match each prompt part to an example.',
    [{ left: 'Task', right: '“Summarise this article”' },
     { left: 'Format', right: '“as a 5-item list”' },
     { left: 'Constraint', right: '“in under 100 words”' }],
    'A strong prompt often combines all three: what to do, how to present it, and what limits to respect.'),
  l2.mc('audience', 'Adding “explain it to a 10-year-old” helps by specifying the…',
    ['Audience and level of the answer',
     'File size of the answer',
     'Colour of the text',
     'Speed of the model'],
    0, 'Naming the audience tells the model how simple or technical to make its language.'),
  l2.tf('assume', 'If you don’t say what format you want, the model will always pick the one you had in mind.', false,
    'It can’t know your unspoken preference. If format matters, say so — otherwise you take what you’re given.'),
  l2.mc('scenario-fix', 'Your prompt “make this better” gives a vague result. The best fix is to…',
    ['Say what “better” means: shorter? friendlier? fewer errors?',
     'Send the exact same prompt again',
     'Assume the AI can’t help',
     'Type it in capital letters'],
    0, '“Better” is subjective. Defining it — “shorter and more formal” — gives the model a clear target.', 'scenario'),
  l2.mc('best-summary', 'The core rule of this lesson is:',
    ['Say clearly what you want, how you want it, and any limits',
     'Use as few words as possible always',
     'Trick the model into guessing',
     'Never mention the format'],
    0, 'Task + format + constraints, stated plainly, is the reliable recipe for a good answer.'),
  l2.tf('effort', 'Spending a few extra seconds to write a clear prompt often saves re-asking later.', true,
    'A precise first prompt usually beats several rounds of fixing a vague one. Clarity up front pays off.'),
];

/* ================================================================== *
 * Lesson 3 — Show, Don’t Just Tell: Few-Shot Examples
 * ================================================================== */
const l3 = bank('w6-l3', 'beginner');
const w6l3Q: Question[] = [
  l3.mc('few-shot', 'What is a “few-shot” prompt?',
    ['One where you include a few examples of the answer you want',
     'One you can only send a few times',
     'A prompt fired from a gun',
     'A prompt that costs a few coins'],
    0, 'Few-shot means giving the model a handful of example inputs and outputs so it copies the pattern.'),
  l3.tf('examples-help', 'Showing the model an example of the output steers it toward that style.', true,
    'Examples are powerful. The model picks up the format, tone, and pattern you demonstrate.'),
  l3.mc('zero-shot', 'A prompt with NO examples, just an instruction, is called…',
    ['Zero-shot', 'Full-shot', 'Blind-shot', 'Example-shot'],
    0, 'Zero-shot = instruction only. Few-shot = instruction plus a few examples to guide the output.'),
  l3.mc('when-examples', 'Examples are especially useful when…',
    ['The exact style or format is hard to describe in words',
     'You want the answer to be random',
     'You have no idea what you want',
     'The task is a simple yes/no'],
    0, 'When it’s easier to show than to explain — a specific tone or layout — examples do the describing for you.'),
  l3.tf('consistency', 'Few-shot examples help the model produce consistent, matching output.', true,
    'By demonstrating the pattern a few times, you get answers that follow the same shape each time.'),
  l3.match('terms', 'Match the term to its meaning.',
    [{ left: 'Zero-shot', right: 'Instruction only, no examples' },
     { left: 'Few-shot', right: 'Instruction plus a few examples' },
     { left: 'Example', right: 'A sample input paired with the wanted output' }],
    'The difference is simply how many demonstrations you include: none, or a few.'),
  l3.mc('better-prompt', 'You want product names turned into short taglines. Which prompt is better?',
    ['“Turn each product into a tagline. Example: ‘Coffee mug → Start your day warm.’ Now do: ‘Desk lamp →’”',
     '“taglines for products”',
     '“make it catchy”',
     '“products”'],
    0, 'The first shows the exact pattern with an example, so the model matches it. The others leave the style to chance.', 'identify-prompt'),
  l3.mc('pattern', 'When you give examples, the model mainly learns the…',
    ['Pattern, style, and format to copy',
     'Your name and location',
     'The current time',
     'How much money you have'],
    0, 'Examples teach the model what a good answer looks like, so it reproduces that shape for new inputs.'),
  l3.tf('too-many', 'Even one or two good examples can noticeably improve the output.', true,
    'You don’t need dozens. A couple of clear, correct examples often do the job well.'),
  l3.mc('scenario-format', 'You keep getting answers in the wrong format. A quick fix is to…',
    ['Include one example showing exactly the format you want',
     'Send the prompt more angrily',
     'Give up on formatting',
     'Ask a completely different question'],
    0, 'One well-chosen example acts as a template. The model tends to mirror the format you demonstrate.', 'scenario'),
  l3.mc('show-tell', 'The lesson “show, don’t just tell” means…',
    ['Demonstrating with examples often beats describing in words alone',
     'You should never explain anything',
     'Pictures are the only good prompts',
     'Telling the model facts is forbidden'],
    0, 'Sometimes an example communicates the target far better than a long description — so show it.'),
];

/* ================================================================== *
 * Lesson 4 — Setting Role & Context
 * ================================================================== */
const l4 = bank('w6-l4', 'intermediate');
const w6l4Q: Question[] = [
  l4.mc('role', 'What does giving the AI a role like “act as a travel guide” do?',
    ['It shapes the tone, focus, and style of the answer',
     'It changes which country you live in',
     'It makes the AI a real travel guide',
     'It costs extra coins'],
    0, 'A role sets the model’s “hat”. Ask it to act as a teacher, editor, or guide, and its answers shift to match.'),
  l4.tf('context-helps', 'Giving background context usually leads to a more relevant answer.', true,
    'Context narrows the model’s aim. The more it knows about your situation, the better it can tailor the reply.'),
  l4.mc('context-example', 'Which of these adds useful context to a prompt?',
    ['“I’m a beginner cook with only a microwave — suggest a recipe.”',
     '“recipe”',
     '“food please”',
     '“cook something”'],
    0, 'It tells the model your skill level and your one constraint, so the answer actually fits your kitchen.', 'identify-prompt'),
  l4.mc('why-role', 'Assigning a role helps mainly because it…',
    ['Guides the model to the right tone, depth, and vocabulary',
     'Gives the model real-world job experience',
     'Makes the model type faster',
     'Removes the need to say anything else'],
    0, '“Act as a lawyer” vs “act as a friend” produce very different phrasing. The role frames how it answers.'),
  l4.tf('context-optional', 'Adding relevant context is a waste of time and never helps.', false,
    'Relevant context is one of the biggest levers you have. It makes answers fit your real situation.'),
  l4.match('roles', 'Match the role to the kind of answer it encourages.',
    [{ left: '“Act as a teacher”', right: 'Clear, step-by-step explanations' },
     { left: '“Act as an editor”', right: 'Fixes and improvements to text' },
     { left: '“Act as a marketer”', right: 'Persuasive, catchy phrasing' }],
    'The role you assign nudges the model’s style toward what that role would naturally produce.'),
  l4.mc('scenario-tailor', 'You ask for feedback on a resume but get generic tips. Adding “act as a hiring manager for tech roles” would…',
    ['Focus the feedback on what tech recruiters actually look for',
     'Make no difference at all',
     'Break the AI',
     'Delete your resume'],
    0, 'A specific role sharpens the perspective, so the advice becomes targeted rather than generic.', 'scenario'),
  l4.tf('audience-context', 'Telling the model who the answer is for is a form of context.', true,
    'Audience is context. “For a 5-year-old” vs “for an engineer” changes the whole answer.'),
  l4.mc('combine', 'A strong prompt often combines role, context, and…',
    ['A clear task with the format you want',
     'A random emoji',
     'Your bank details',
     'The current weather'],
    0, 'Role + context + a clear task and format is a reliable pattern for well-aimed answers.'),
  l4.mc('background', 'Why include background details the model can’t know?',
    ['The model only knows what you tell it about your situation',
     'To make the prompt longer for fun',
     'Because the model prefers gossip',
     'It has no effect on the answer'],
    0, 'The model can’t see your life. Facts about your goal, level, or limits let it tailor the response.'),
  l4.tf('generic', 'Without any context, the model tends to give a generic, one-size-fits-all answer.', true,
    'With nothing to go on, it aims for the average case. Context is what makes the answer yours.'),
  l4.mc('lesson', 'The main idea of this lesson is:',
    ['Set a role and give context to get more relevant, tailored answers',
     'Never tell the model anything about yourself',
     'Roles confuse the model',
     'Context slows the AI down'],
    0, 'A well-chosen role plus relevant background steers the model toward answers that fit your real need.'),
];

/* ================================================================== *
 * Lesson 5 — Think Step by Step: Chain of Thought
 * ================================================================== */
const l5 = bank('w6-l5', 'intermediate');
const w6l5Q: Question[] = [
  l5.mc('cot', 'What does “think step by step” ask the model to do?',
    ['Show its reasoning in stages before giving the final answer',
     'Answer more slowly on purpose',
     'Skip the hard parts',
     'Only give one-word answers'],
    0, 'Asking for step-by-step reasoning makes the model work through the problem, which often improves the answer.'),
  l5.tf('reasoning-helps', 'Asking for reasoning can improve answers on hard, multi-step problems.', true,
    'Working through steps helps the model avoid jumping to a wrong conclusion, especially on tricky questions.'),
  l5.mc('when-cot', 'Chain-of-thought prompting helps MOST with…',
    ['Multi-step problems like math or logic puzzles',
     'A simple greeting',
     'Repeating one word',
     'Turning the AI on'],
    0, 'For problems with several steps, showing the working reduces careless mistakes. Simple tasks don’t need it.'),
  l5.mc('better-prompt', 'Which prompt is more likely to get a correct answer to a tricky word problem?',
    ['“Solve this step by step, showing your working, then give the final answer.”',
     '“answer fast”',
     '“just the number”',
     '“solve it”'],
    0, 'Requesting the steps encourages careful reasoning. Demanding only a quick answer invites a rushed mistake.', 'identify-prompt'),
  l5.tf('always', 'You should ask for step-by-step reasoning on every single prompt.', false,
    'For simple tasks it just adds clutter. Reserve chain-of-thought for problems that actually need reasoning.'),
  l5.match('terms', 'Match the term to its meaning.',
    [{ left: 'Chain of thought', right: 'Reasoning shown step by step' },
     { left: 'Final answer', right: 'The conclusion after the steps' },
     { left: 'Multi-step problem', right: 'One needing several stages to solve' }],
    'Chain of thought lays out the stages that lead to the final answer — useful when a problem has several steps.'),
  l5.order('process', 'Order a good chain-of-thought prompt flow.',
    ['State the problem clearly', 'Ask the model to think step by step', 'Let it work through each step', 'Have it state the final answer', 'Check the reasoning makes sense'],
    'Give the problem, request the steps, let it reason, get the answer, then sanity-check the working.'),
  l5.mc('why-works', 'Why does showing reasoning tend to help?',
    ['Breaking a problem into steps reduces careless jumps to wrong answers',
     'It changes the model’s training',
     'It gives the model more memory',
     'It makes the answer shorter'],
    0, 'Tackling one step at a time mirrors how people avoid mistakes on hard problems. The model benefits similarly.'),
  l5.tf('verify', 'Seeing the model’s steps also makes it easier for you to spot where it went wrong.', true,
    'Visible reasoning is checkable. If the answer looks off, you can trace which step broke down.'),
  l5.mc('scenario-math', 'The AI gives a wrong total for a multi-part calculation. A good next move is to…',
    ['Ask it to redo the problem step by step and show each stage',
     'Assume math is impossible for AI',
     'Ask the exact same way again',
     'Give up entirely'],
    0, 'Forcing the working out often fixes the error and lets you see where it slipped.', 'scenario'),
  l5.mc('lesson', 'The takeaway of this lesson is:',
    ['For hard problems, ask the model to reason step by step',
     'Always demand instant one-word answers',
     'Reasoning never helps',
     'Only simple prompts work'],
    0, 'On multi-step problems, requesting visible reasoning boosts accuracy and lets you check the work.'),
];

/* ================================================================== *
 * Lesson 6 — Common Prompting Mistakes
 * ================================================================== */
const l6 = bank('w6-l6', 'intermediate');
const w6l6Q: Question[] = [
  l6.mc('vagueness', 'Which is the most common prompting mistake?',
    ['Being too vague about what you actually want',
     'Using complete sentences',
     'Saying “please”',
     'Naming the format you want'],
    0, 'Vagueness is the number-one issue. Without a clear target, the model guesses — and often guesses wrong.'),
  l6.tf('overload', 'Cramming five unrelated tasks into one prompt can confuse the model.', true,
    'Overloading a prompt spreads the model thin. Splitting big requests into steps usually works better.'),
  l6.mc('no-format', 'You wanted a table but got a paragraph. The likely mistake was…',
    ['Not specifying the format you wanted',
     'The model hates tables',
     'Using too few capital letters',
     'Asking during the day'],
    0, 'If you don’t state the format, you get whatever the model defaults to. Name it to get it.'),
  l6.mc('private-context', 'Why can’t the AI answer correctly about “the report from yesterday’s meeting”?',
    ['It has no access to your private files or memory of your day',
     'It is too lazy to look',
     'It forgot on purpose',
     'Reports are banned'],
    0, 'The model doesn’t know your private context unless you include it. Paste the details it needs.'),
  l6.tf('assume-knows', 'The model automatically knows your company’s internal documents and past chats.', false,
    'It doesn’t. Unless you provide the information in the prompt, it can’t use context it was never given.'),
  l6.match('mistakes', 'Match each mistake to its fix.',
    [{ left: 'Too vague', right: 'Say exactly what you want' },
     { left: 'No format given', right: 'State the format you need' },
     { left: 'Assumes private context', right: 'Paste in the needed details' }],
    'Most bad answers trace back to a fixable prompt: add specifics, name the format, supply the context.'),
  l6.mc('better-prompt', 'Which prompt avoids the common mistakes?',
    ['“Rewrite this paragraph (pasted below) to be more formal, in under 80 words.”',
     '“fix my writing”',
     '“make it good”',
     '“the paragraph from before”'],
    0, 'It includes the text, names the task, the tone, and a length limit — no vagueness, no assumed context.', 'identify-prompt'),
  l6.tf('one-thing', 'Breaking a big request into smaller, focused prompts often gives better results.', true,
    'Focused prompts are easier for the model to handle well. One clear task at a time beats an overloaded jumble.'),
  l6.mc('scenario-overload', 'You ask the AI to “research, summarise, translate, and format” all at once and get a messy result. Better to…',
    ['Split it into separate, focused prompts, one step at a time',
     'Shout the prompt louder',
     'Assume the AI is broken',
     'Add more unrelated tasks'],
    0, 'Overloaded prompts produce muddled answers. Tackling one step per prompt keeps each result clean.', 'scenario'),
  l6.mc('diagnose', 'When an AI answer disappoints, the smartest first move is usually to…',
    ['Look at whether your prompt was clear, specific, and complete',
     'Blame the model and stop',
     'Assume AI can never help',
     'Send the same prompt repeatedly'],
    0, 'Most weak answers come from weak prompts. Improving the prompt is the fastest path to a better result.'),
  l6.tf('learnable', 'Avoiding these common mistakes is a skill anyone can build with practice.', true,
    'Spot vagueness, overloading, missing format, and assumed context — fix those, and your results jump.'),
  l6.mc('wrap', 'The single best summary of good prompting is:',
    ['Be clear, specific, and complete — give the model what it needs',
     'Keep the model guessing',
     'Never explain what you want',
     'Cram everything into one line'],
    0, 'Clear, specific, complete prompts are the whole game. Give the model the task, format, and context it needs.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD6_LESSONS: Lesson[] = [
  {
    id: 'w6-l1', worldId: W, order: 1,
    title: 'What Is a Prompt?',
    subtitle: 'Your instruction shapes the answer',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'A prompt is simply what you say to the AI. Those words are the only clue the model has — so they decide the answer you get back.',
    explanation: 'When you talk to an AI, everything it does starts from your prompt. It can’t read your mind; it can only read your words. That’s why learning to ask well is the single most useful skill for getting good answers.',
    realWorld: 'It’s like ordering food. “Something to eat” gets you anything; “a cheese sandwich, no onions” gets you exactly what you wanted. Your prompt is the order.',
    objectives: [
      'Define what a prompt is',
      'Explain why wording changes the answer',
      'Tell a clear prompt from a vague one',
    ],
    activity: {
      kind: 'bucket',
      title: 'Clear or Vague?',
      instructions: 'Tap each prompt and drop it into the right bucket. Which ones give the model a clear target?',
      config: {
        buckets: ['Clear prompt', 'Vague prompt'],
        items: [
          { label: '“Summarise this in 2 bullets”', bucket: 0 },
          { label: '“Write a 3-line thank-you note”', bucket: 0 },
          { label: '“List 5 healthy breakfast ideas”', bucket: 0 },
          { label: '“stuff”', bucket: 1 },
          { label: '“do the thing”', bucket: 1 },
          { label: '“help”', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'A prompt is the instruction you give the AI.',
      'The wording of the prompt shapes the answer.',
      'The model only knows what you actually tell it.',
    ],
    commonMistakes: [
      'Expecting the AI to guess what you meant.',
      'Typing one vague word and hoping for a perfect answer.',
    ],
    summary: 'A prompt is your instruction to the model — and clearer instructions get better answers.',
    prerequisiteLessonIds: ['w5-l6'],
    nextLessonId: 'w6-l2',
  },
  {
    id: 'w6-l2', worldId: W, order: 2,
    title: 'Clear Instructions Beat Clever Tricks',
    subtitle: 'Task, format, constraints',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 6,
    description: 'You don’t need secret tricks. The most reliable way to a great answer is to say plainly what to do, how to present it, and any limits.',
    explanation: 'Good prompts usually have three parts: the task (what to do), the format (how to show it), and constraints (any limits, like length or tone). State all three and the model can aim straight at what you want.',
    realWorld: 'Briefing a helper works the same way: “Write a note (task), as bullet points (format), under 50 words (constraint)” beats a mysterious “make it good”.',
    objectives: [
      'Break a prompt into task, format, and constraints',
      'Turn a vague prompt into a specific one',
      'Choose clarity over gimmicks',
    ],
    activity: {
      kind: 'bucket',
      title: 'What Kind of Detail?',
      instructions: 'Sort each snippet by which part of a prompt it is.',
      config: {
        buckets: ['Task', 'Format', 'Constraint'],
        items: [
          { label: '“Summarise this article”', bucket: 0 },
          { label: '“Write a reply”', bucket: 0 },
          { label: '“as a 5-item list”', bucket: 1 },
          { label: '“in a table”', bucket: 1 },
          { label: '“under 100 words”', bucket: 2 },
          { label: '“in a formal tone”', bucket: 2 },
        ],
      },
    },
    keyTakeaways: [
      'Clear beats clever — say plainly what you want.',
      'A strong prompt names the task, format, and constraints.',
      'If the format matters, state it explicitly.',
    ],
    commonMistakes: [
      'Leaving out the format, then being surprised by the shape of the answer.',
      'Using vague words like “better” without defining them.',
    ],
    summary: 'Task + format + constraints, stated plainly, is the reliable recipe for a good answer.',
    prerequisiteLessonIds: ['w6-l1'],
    nextLessonId: 'w6-l3',
  },
  {
    id: 'w6-l3', worldId: W, order: 3,
    title: 'Show, Don’t Just Tell: Few-Shot Examples',
    subtitle: 'Give examples to steer the output',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 60, coins: 8,
    description: 'Sometimes it’s easier to show the answer you want than to describe it. Including a few examples steers the model to copy that pattern.',
    explanation: 'A prompt with no examples is “zero-shot”. Add a couple of sample inputs and outputs and it becomes “few-shot”. Those examples teach the model the exact style and format to match — often better than words alone.',
    realWorld: 'Like showing a new teammate one finished report and saying “make the rest like this”. The example does the explaining for you.',
    objectives: [
      'Explain zero-shot vs few-shot prompting',
      'Use examples to lock in a style or format',
      'Know when showing beats telling',
    ],
    activity: {
      kind: 'steps',
      title: 'Build a Few-Shot Prompt',
      instructions: 'Drag the pieces into the order that builds a good few-shot prompt.',
      config: {
        steps: [
          'State the task you want done',
          'Give one example input',
          'Show the ideal output for it',
          'Provide the new input to process',
          'Let the model match the pattern',
        ],
      },
    },
    keyTakeaways: [
      'Zero-shot = no examples; few-shot = a few examples.',
      'Examples teach the model the style and format to copy.',
      'Even one or two good examples can help a lot.',
    ],
    commonMistakes: [
      'Describing a tricky format in words when one example would be clearer.',
      'Giving a messy or wrong example, which the model then copies.',
    ],
    summary: 'When style or format is hard to describe, show it — a few examples steer the output.',
    prerequisiteLessonIds: ['w6-l2'],
    nextLessonId: 'w6-l4',
  },
  {
    id: 'w6-l4', worldId: W, order: 4,
    title: 'Setting Role & Context',
    subtitle: '“Act as…” and give background',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Give the model a role (“act as a teacher”) and background about your situation, and its answers become far more relevant and tailored to you.',
    explanation: 'A role sets the model’s hat — a teacher explains, an editor fixes, a marketer persuades. Context tells it about your situation, level, and goal. The model only knows what you share, so a little background goes a long way.',
    realWorld: 'Asking a friendly librarian for a book is easier if you say “I’m new to cooking and want something quick” — the same detail helps the AI point you to the right answer.',
    objectives: [
      'Use a role to shape tone and style',
      'Add context that tailors the answer',
      'Combine role, context, and task',
    ],
    activity: {
      kind: 'bucket',
      title: 'Role, Context, or Task?',
      instructions: 'Sort each phrase by what it adds to a prompt.',
      config: {
        buckets: ['Role', 'Context', 'Task'],
        items: [
          { label: '“Act as a hiring manager”', bucket: 0 },
          { label: '“Act as a friendly tutor”', bucket: 0 },
          { label: '“I’m a beginner with a small kitchen”', bucket: 1 },
          { label: '“This is for a 5-year-old”', bucket: 1 },
          { label: '“Review my resume”', bucket: 2 },
          { label: '“Suggest a recipe”', bucket: 2 },
        ],
      },
    },
    keyTakeaways: [
      'A role shapes the tone, depth, and style of the answer.',
      'Context tailors the answer to your real situation.',
      'The model only knows the background you give it.',
    ],
    commonMistakes: [
      'Assuming the model knows details about you that you never wrote.',
      'Skipping context, then getting a generic, one-size-fits-all answer.',
    ],
    summary: 'Set a role and give context to turn generic answers into ones that fit your real need.',
    prerequisiteLessonIds: ['w6-l3'],
    nextLessonId: 'w6-l5',
  },
  {
    id: 'w6-l5', worldId: W, order: 5,
    title: 'Think Step by Step: Chain of Thought',
    subtitle: 'Ask for reasoning on hard problems',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'For tricky, multi-step problems, asking the model to “think step by step” and show its working often leads to a more accurate answer.',
    explanation: 'When a problem has several stages — math, logic, planning — jumping straight to an answer invites mistakes. Asking the model to reason step by step makes it work through each stage, which improves accuracy and lets you check the working. Save it for hard problems; simple tasks don’t need it.',
    realWorld: 'It’s like solving a math problem on paper instead of in your head. Writing each step makes errors easier to avoid — and easier to spot.',
    objectives: [
      'Explain what chain-of-thought prompting is',
      'Know when reasoning helps and when it’s overkill',
      'Use visible steps to check the answer',
    ],
    activity: {
      kind: 'steps',
      title: 'Order the Reasoning Flow',
      instructions: 'Arrange the steps of a good chain-of-thought prompt in order.',
      config: {
        steps: [
          'State the problem clearly',
          'Ask the model to think step by step',
          'Let it work through each step',
          'Have it state the final answer',
          'Check the reasoning makes sense',
        ],
      },
    },
    keyTakeaways: [
      'Ask for step-by-step reasoning on hard, multi-step problems.',
      'Visible steps improve accuracy and are easy to check.',
      'Skip it for simple tasks — it just adds clutter.',
    ],
    commonMistakes: [
      'Demanding an instant one-word answer to a multi-step problem.',
      'Adding “think step by step” to trivial prompts where it isn’t needed.',
    ],
    summary: 'On hard problems, asking the model to reason step by step boosts accuracy and lets you check its work.',
    prerequisiteLessonIds: ['w6-l4'],
    nextLessonId: 'w6-l6',
  },
  {
    id: 'w6-l6', worldId: W, order: 6,
    title: 'Common Prompting Mistakes',
    subtitle: 'What to avoid — and how to fix it',
    difficulty: 'intermediate', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Most disappointing answers trace back to a fixable prompt. Learn the four big mistakes and the simple fix for each.',
    explanation: 'The usual culprits: being too vague, overloading one prompt with many tasks, forgetting to name the format, and assuming the model knows your private context. Each has an easy fix — add specifics, split the request, state the format, and paste in the details it needs.',
    realWorld: 'It’s like a bad delivery order: too vague, five unrelated items, no address. Clear it up and the right thing arrives.',
    objectives: [
      'Recognise the four common prompting mistakes',
      'Apply the fix for each one',
      'Diagnose a weak answer by checking the prompt',
    ],
    activity: {
      kind: 'bucket',
      title: 'Good Prompt or Mistake?',
      instructions: 'Sort each prompt into a well-written one or a common mistake.',
      config: {
        buckets: ['Well-written prompt', 'Common mistake'],
        items: [
          { label: '“Rewrite the text below to be formal, under 80 words”', bucket: 0 },
          { label: '“Summarise this article in 3 bullet points”', bucket: 0 },
          { label: '“List 4 tips for a beginner runner”', bucket: 0 },
          { label: '“fix my writing”', bucket: 1 },
          { label: '“research, summarise, translate and format it all”', bucket: 1 },
          { label: '“the report from yesterday’s meeting”', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Vagueness and overloading are the top prompt-killers.',
      'Always state the format; never assume private context.',
      'When an answer disappoints, improve the prompt first.',
    ],
    commonMistakes: [
      'Cramming many unrelated tasks into one prompt.',
      'Referring to files or chats the model was never given.',
      'Blaming the model instead of sharpening the prompt.',
    ],
    summary: 'Be clear, specific, and complete — give the model the task, format, and context it needs.',
    prerequisiteLessonIds: ['w6-l5'],
    nextLessonId: 'w7-l1',
  },
];

export const WORLD6_QUESTIONS: Question[] = [
  ...w6l1Q, ...w6l2Q, ...w6l3Q,
  ...w6l4Q, ...w6l5Q, ...w6l6Q,
];
