import { ChoiceQuestion, Difficulty, Lesson, MatchQuestion, OrderQuestion, Question } from '../types';

/**
 * World 7 — Embeddings & Vector Search. Full lessons + question bank.
 * Structure mirrors world1.ts, the reference template for every world.
 */

const W = 'world-embeddings';

/** Per-lesson question builders — keep the bank DRY and readable. */
const bank = (lessonId: string, difficulty: Difficulty) => {
  let n = 0;
  const id = () => `${lessonId}-q${++n}`;
  return {
    mc: (
      topic: string,
      prompt: string,
      options: string[],
      correctIndex: number,
      explanation: string,
      type: ChoiceQuestion['type'] = 'multiple-choice',
    ): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type, prompt, options, correctIndex, explanation,
    }),
    tf: (topic: string, prompt: string, correct: boolean, explanation: string): ChoiceQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'true-false',
      prompt, options: ['True', 'False'], correctIndex: correct ? 0 : 1, explanation,
    }),
    match: (topic: string, prompt: string, pairs: { left: string; right: string }[], explanation: string): MatchQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'match', prompt, pairs, explanation,
    }),
    order: (topic: string, prompt: string, items: string[], explanation: string): OrderQuestion => ({
      id: id(), worldId: W, lessonId, difficulty, topic, type: 'order', prompt, items, explanation,
    }),
  };
};

/* ================================================================== *
 * Lesson 1 — Turning Meaning into Numbers
 * ================================================================== */
const l1 = bank('w7-l1', 'beginner');
const w7l1Q: Question[] = [
  l1.mc('definition', 'What is an “embedding” in AI?',
    ['A list of numbers that captures the meaning of something',
     'A picture stored on a hard drive',
     'A password for a website',
     'A type of computer chip'],
    0, 'An embedding turns a word, sentence or image into a list of numbers that stands for its meaning.'),
  l1.tf('why-numbers', 'Computers work with numbers far more easily than with raw words.', true,
    'Machines can’t compare meaning directly, so we translate text into numbers they can measure and compare.'),
  l1.mc('what-captured', 'The numbers in an embedding are meant to capture…',
    ['The meaning, so similar things get similar numbers',
     'The colour of the text',
     'How many letters a word has',
     'The file size of the document'],
    0, 'Embeddings are designed so that things with similar meaning end up with similar number-lists.'),
  l1.mc('example', '“Cat” and “kitten” would get embeddings that are…',
    ['Close to each other, because their meanings are close',
     'Completely random and unrelated',
     'Exactly the same as “car” and “truck”',
     'Just their spellings turned into numbers'],
    0, 'Related meanings map to nearby number-lists. “Cat” and “kitten” land close together.'),
  l1.tf('spelling', 'Embeddings are just the spelling of a word converted to numbers.', false,
    'Spelling isn’t meaning. “Bank” (river) and “bank” (money) spell the same but can mean different things.'),
  l1.match('vocab', 'Match each idea to its meaning.',
    [{ left: 'Embedding', right: 'A list of numbers standing for meaning' },
     { left: 'Meaning', right: 'What the embedding tries to capture' },
     { left: 'Similar meaning', right: 'Similar numbers' }],
    'An embedding encodes meaning as numbers, so similar meanings become similar numbers.'),
  l1.mc('what-not', 'Which of these can be turned into an embedding?',
    ['Words, sentences, images and more',
     'Only single letters',
     'Only numbers you type in yourself',
     'Nothing — it only works on code'],
    0, 'Text, images, audio and more can all be embedded — anything we want to compare by meaning.'),
  l1.tf('list', 'An embedding is usually a long list of many numbers, not just one.', true,
    'A single number can’t hold much meaning. Embeddings use dozens or hundreds of numbers together.'),
  l1.mc('scenario-search', 'You type “affordable eats” and get results for “cheap restaurants”. Embeddings helped by…',
    ['Turning both phrases into similar numbers because they mean similar things',
     'Matching the exact letters in your words',
     'Guessing randomly',
     'Sorting results alphabetically'],
    0, 'The phrases share meaning, so their embeddings are close — that’s how meaning-based matching works.', 'scenario'),
  l1.mc('goal', 'The whole point of embeddings is to…',
    ['Let computers compare things by meaning, not just exact text',
     'Make files smaller',
     'Replace the need for electricity',
     'Change the font of a document'],
    0, 'Once meaning is numbers, a computer can measure how close two things are in meaning.'),
  l1.tf('learned', 'Embeddings are learned by AI models from lots of examples.', true,
    'Models learn which meanings go together by reading huge amounts of text, then place them in number-space accordingly.'),
];

/* ================================================================== *
 * Lesson 2 — What Is a Vector?
 * ================================================================== */
const l2 = bank('w7-l2', 'beginner');
const w7l2Q: Question[] = [
  l2.mc('vector-def', 'In this context, a “vector” is basically…',
    ['A list of numbers that marks a point in “meaning space”',
     'A kind of virus',
     'A drawing tool',
     'A single yes/no answer'],
    0, 'A vector is just an ordered list of numbers. Here it names a point in a space of meaning.'),
  l2.tf('same-thing', 'An embedding is a vector — the two words describe the same thing here.', true,
    'An embedding is the meaning-vector for something. People use the words interchangeably.'),
  l2.mc('space', 'What does it mean that similar things “sit close together”?',
    ['Their points in meaning space are near each other',
     'They are stored in the same folder',
     'They were typed at the same time',
     'They have the same colour'],
    0, 'Closeness in this space means closeness in meaning — near points share meaning.'),
  l2.mc('map-analogy', 'Meaning space is a bit like a map where…',
    ['Related ideas are neighbours and unrelated ideas are far apart',
     'Everything is placed randomly',
     'Only cities can appear',
     'Distance means nothing at all'],
    0, 'Like a map places nearby towns close, meaning space places related ideas close.'),
  l2.tf('one-number', 'A vector for meaning is usually a single number.', false,
    'It’s many numbers together — each adds a little more room to separate different meanings.'),
  l2.match('space-terms', 'Match the term to its meaning.',
    [{ left: 'Vector', right: 'A list of numbers = a point in space' },
     { left: 'Meaning space', right: 'Where all the points live' },
     { left: 'Close points', right: 'Similar meanings' }],
    'Vectors are points, meaning space is where they live, and nearby points mean similar things.'),
  l2.mc('dimensions', 'Why use many numbers instead of just two?',
    ['More numbers give more room to separate subtle differences in meaning',
     'It looks more impressive',
     'Two numbers are illegal',
     'It makes the file heavier on purpose'],
    0, 'Meaning is rich. Extra numbers (dimensions) give space to keep different meanings apart.'),
  l2.tf('neighbours', 'If two vectors are neighbours, the things they represent probably mean similar things.', true,
    'Neighbouring vectors = similar meaning. That single idea powers most of vector search.'),
  l2.mc('scenario-words', '“Happy”, “joyful” and “cheerful” in meaning space would…',
    ['Cluster close together as neighbours',
     'Be spread as far apart as possible',
     'Sit next to “angry” and “sad”',
     'Have identical vectors to “table”'],
    0, 'Synonyms share meaning, so their vectors form a tight little cluster.', 'scenario'),
  l2.mc('far-apart', 'Which pair would sit FARTHEST apart in meaning space?',
    ['“Banana” and “democracy”',
     '“Dog” and “puppy”',
     '“Car” and “vehicle”',
     '“Ocean” and “sea”'],
    0, 'Unrelated meanings land far apart. The other pairs are close in meaning, so close in space.'),
  l2.tf('why', 'Turning meaning into points lets us use distance to measure similarity.', true,
    'Once ideas are points, “how similar?” becomes “how far apart?” — a question a computer can answer.'),
];

/* ================================================================== *
 * Lesson 3 — Measuring Similarity
 * ================================================================== */
const l3 = bank('w7-l3', 'beginner');
const w7l3Q: Question[] = [
  l3.mc('core-idea', 'How does a computer decide two things mean something similar?',
    ['It measures how close their vectors are',
     'It counts the letters they share',
     'It checks which is longer',
     'It asks a human every time'],
    0, 'Closeness of vectors is the measure of similarity — near means similar, far means different.'),
  l3.tf('closer', 'The closer two vectors are, the more similar their meanings.', true,
    'Small distance = similar meaning. Large distance = different meaning. That’s the whole trick.'),
  l3.mc('distance', 'A large distance between two vectors usually means…',
    ['Their meanings are quite different',
     'They are exactly the same',
     'The computer is broken',
     'They were saved on the same day'],
    0, 'Far apart in meaning space means far apart in meaning.'),
  l3.mc('similarity-score', 'A “similarity score” is a number that tells you…',
    ['How alike two things are in meaning',
     'How big a file is',
     'What time it is',
     'How many words are on a page'],
    0, 'Systems often turn distance into a similarity score: higher means more alike.'),
  l3.tf('exact', 'Two identical sentences would have vectors that are extremely close (basically on top of each other).', true,
    'Identical meaning gives near-identical vectors, so their distance is about zero.'),
  l3.order('search-flow', 'Put the steps of a meaning-based search in order.',
    ['Turn the query into a vector',
     'Compare it to the stored vectors',
     'Measure the distance to each',
     'Return the closest ones as results'],
    'Embed the query, compare, measure closeness, then return the nearest matches — that’s vector search.'),
  l3.match('sim-terms', 'Match the term to its meaning.',
    [{ left: 'Distance', right: 'How far apart two vectors are' },
     { left: 'Close', right: 'Similar meaning' },
     { left: 'Far', right: 'Different meaning' }],
    'Distance measures separation; close means similar, far means different.'),
  l3.mc('nearest', 'To find the item most similar to a query, you look for the vector that is…',
    ['Closest to the query’s vector',
     'Farthest from the query’s vector',
     'The oldest one stored',
     'The one with the longest text'],
    0, 'The nearest vector is the best match — that’s a “nearest neighbour” search.'),
  l3.mc('scenario-support', 'A help desk finds the FAQ answer closest in meaning to a user’s question. It works by…',
    ['Embedding the question and returning the nearest stored answer',
     'Matching only questions with identical wording',
     'Picking a random FAQ',
     'Showing the newest FAQ first'],
    0, 'The user’s question becomes a vector; the closest FAQ vector is the best-matching answer.', 'scenario'),
  l3.tf('threshold', 'Systems often set a threshold — only count matches closer than a certain distance.', true,
    'A threshold filters out weak matches, so only results similar enough to be useful get returned.'),
  l3.mc('why-useful', 'Measuring similarity by distance is powerful because it…',
    ['Compares meaning even when the exact words differ',
     'Only works on identical text',
     'Needs the two things to be the same length',
     'Ignores meaning entirely'],
    0, 'Different words, same meaning still land close — so distance catches matches keywords would miss.'),
];

/* ================================================================== *
 * Lesson 4 — Vector Databases
 * ================================================================== */
const l4 = bank('w7-l4', 'intermediate');
const w7l4Q: Question[] = [
  l4.mc('what-is', 'What is a vector database built to do?',
    ['Store lots of embeddings and quickly find the closest ones',
     'Store photos and play music',
     'Send emails',
     'Only store plain text with no search'],
    0, 'A vector database keeps millions of embeddings and is optimised to search them by closeness, fast.'),
  l4.tf('millions', 'Vector databases are designed to handle millions of vectors efficiently.', true,
    'Scanning millions one by one would be slow, so these databases use smart tricks to search quickly.'),
  l4.mc('why-special', 'Why not just use a normal database?',
    ['Normal databases are great at exact matches, not “nearest in meaning” searches',
     'Normal databases can’t store numbers',
     'Vector databases are always cheaper',
     'Normal databases are illegal for AI'],
    0, 'Regular databases find exact matches well. Finding the closest meaning needs special vector indexing.'),
  l4.mc('speed-trick', 'To stay fast, a vector database avoids…',
    ['Comparing the query to every single vector one by one',
     'Storing any vectors at all',
     'Returning results',
     'Using numbers'],
    0, 'Checking all vectors is slow at scale, so it uses an index to jump near the answer quickly.'),
  l4.tf('exact', 'A vector database usually returns the “about closest” matches, trading a tiny bit of accuracy for big speed.', true,
    'Approximate nearest-neighbour search gives almost-perfect matches far faster — a smart trade at scale.'),
  l4.order('build-flow', 'Put the steps of using a vector database in order.',
    ['Turn each item into an embedding',
     'Store the embeddings in the database',
     'Turn a new query into an embedding',
     'Search for the nearest stored embeddings'],
    'Embed and store your items, then embed each query and search for its nearest neighbours.'),
  l4.match('db-terms', 'Match the term to its meaning.',
    [{ left: 'Vector database', right: 'Stores embeddings for fast similarity search' },
     { left: 'Index', right: 'A structure that makes searching quick' },
     { left: 'Nearest neighbours', right: 'The closest matches to a query' }],
    'The database stores vectors, an index speeds up search, and neighbours are the closest matches.'),
  l4.mc('use-case', 'A vector database is a natural fit for…',
    ['A search feature that matches by meaning across millions of documents',
     'Adding two numbers together',
     'Storing a single short note',
     'Displaying the current time'],
    0, 'Large-scale meaning search is exactly what vector databases are built for.'),
  l4.mc('scenario-scale', 'An app has 10 million product descriptions and must find similar products instantly. It should…',
    ['Store embeddings in a vector database and search by nearest neighbours',
     'Compare the query text to all 10 million by hand',
     'Sort products alphabetically and hope',
     'Store no data and guess'],
    0, 'At that scale you need embeddings plus a vector database’s fast nearest-neighbour search.', 'scenario'),
  l4.tf('update', 'You can add new vectors to a vector database over time without rebuilding everything.', true,
    'Vector databases let you keep inserting new embeddings as your data grows.'),
  l4.mc('tradeoff', 'The main trade-off vector databases make is…',
    ['A tiny bit of accuracy for a huge gain in speed',
     'Speed for no results at all',
     'Storing less data to save the meaning',
     'Meaning for spelling'],
    0, 'Approximate search returns matches that are almost always right, but returns them far faster.'),
];

/* ================================================================== *
 * Lesson 5 — Semantic Search vs Keyword Search
 * ================================================================== */
const l5 = bank('w7-l5', 'intermediate');
const w7l5Q: Question[] = [
  l5.mc('keyword-def', 'Keyword search finds results by…',
    ['Matching the exact words you typed',
     'Understanding what you meant',
     'Reading your mind',
     'Guessing randomly'],
    0, 'Keyword search looks for the literal words. If they’re not present, it misses the result.'),
  l5.mc('semantic-def', 'Semantic (meaning-based) search finds results by…',
    ['Matching meaning using embeddings, even with different words',
     'Only matching exact letters',
     'Counting how long the text is',
     'Sorting by date'],
    0, 'Semantic search compares meaning via embeddings, so different wording still matches.'),
  l5.tf('synonyms', 'Keyword search can miss a great result just because it used a synonym.', true,
    'If you search “car” but the page says “automobile”, plain keyword search may skip it. Semantic search wouldn’t.'),
  l5.mc('example', 'You search “ways to cut spending”. Semantic search can also find a doc titled…',
    ['“How to reduce your expenses”',
     'Only pages containing the exact phrase “cut spending”',
     'Pages about cutting paper',
     'Nothing, unless words match exactly'],
    0, '“Reduce expenses” means the same as “cut spending”, so their embeddings are close — semantic search catches it.'),
  l5.tf('keyword-useless', 'Keyword search is always useless and should never be used.', false,
    'Keyword search is fast and perfect for exact terms like product codes or names. Each approach has its place.'),
  l5.match('compare', 'Match each search type to how it matches.',
    [{ left: 'Keyword search', right: 'Exact words must appear' },
     { left: 'Semantic search', right: 'Matches by meaning' },
     { left: 'Embeddings', right: 'What makes semantic search possible' }],
    'Keyword = exact words; semantic = meaning; embeddings are the engine behind semantic search.'),
  l5.mc('best-keyword', 'When is plain keyword search actually the BETTER choice?',
    ['Looking up an exact product code or specific name',
     'Finding documents about a vague idea',
     'Matching questions phrased in many ways',
     'Searching by overall meaning'],
    0, 'For exact identifiers, you want the literal match — meaning-matching could add noise.'),
  l5.tf('hybrid', 'Many real search systems combine keyword and semantic search.', true,
    'Hybrid search uses keywords for exactness and embeddings for meaning — the best of both.'),
  l5.mc('scenario-store', 'A shopper types “warm winter coat” and semantic search shows a “thermal parka”. This works because…',
    ['The phrases mean the same thing, so their embeddings are close',
     'The words match exactly',
     'The parka was added most recently',
     'The store sorts items alphabetically'],
    0, 'No shared keywords, but shared meaning — embeddings put them close, so semantic search finds it.', 'scenario'),
  l5.mc('why-better', 'The big advantage of semantic search is that it…',
    ['Understands intent, so it finds relevant results even with different wording',
     'Only ever returns exact-word matches',
     'Needs no data at all',
     'Runs without any model'],
    0, 'Matching meaning instead of exact words means far fewer missed-but-relevant results.'),
  l5.tf('embeddings-power', 'Embeddings are what let semantic search compare meaning.', true,
    'By turning text into meaning-vectors, embeddings make it possible to match by meaning rather than letters.'),
];

/* ================================================================== *
 * Lesson 6 — Embeddings in the Real World
 * ================================================================== */
const l6 = bank('w7-l6', 'intermediate');
const w7l6Q: Question[] = [
  l6.mc('recommendations', 'How can embeddings power recommendations?',
    ['Items close in meaning space are suggested as “similar” or “you might like”',
     'By picking items at random',
     'By showing only the newest item',
     'By sorting items alphabetically'],
    0, 'If a song, product or video sits near ones you liked, it’s a good recommendation candidate.'),
  l6.tf('dedup', 'Embeddings help spot near-duplicate content, even when the wording differs.', true,
    'Two texts that mean the same thing get very close vectors, so systems can flag them as duplicates.'),
  l6.mc('clustering', 'Grouping many items into themes by their embeddings is called…',
    ['Clustering',
     'Deleting',
     'Printing',
     'Encrypting'],
    0, 'Clustering gathers nearby vectors into groups, revealing natural themes in the data.'),
  l6.mc('search-again', 'A smart search bar that understands what you mean relies on…',
    ['Embeddings comparing your query’s meaning to stored content',
     'Only exact keyword matching',
     'A human reading every query',
     'Random guessing'],
    0, 'Meaning-based search uses embeddings to match intent, not just literal words.'),
  l6.tf('images', 'Embeddings work for images too, not only text.', true,
    'Images can be embedded, so you can find visually or conceptually similar pictures by closeness.'),
  l6.match('apps', 'Match each application to what embeddings do in it.',
    [{ left: 'Recommendations', right: 'Suggest items close in meaning' },
     { left: 'Deduplication', right: 'Spot near-identical content' },
     { left: 'Clustering', right: 'Group items into themes' }],
    'Recommend nearby items, flag duplicates, and cluster related items — all powered by closeness in meaning space.'),
  l6.mc('rag', 'Chatbots that fetch relevant documents before answering use embeddings to…',
    ['Find the passages closest in meaning to the question',
     'Change the font of the answer',
     'Delete the question',
     'Pick documents at random'],
    0, 'The question is embedded, and the closest stored passages are retrieved to help answer it.'),
  l6.tf('everywhere', 'Embeddings quietly power search, recommendations and grouping in many everyday apps.', true,
    'Much like other AI, embeddings run invisibly behind features you use daily.'),
  l6.mc('scenario-photos', 'A photo app groups your pictures into “beaches”, “pets” and “food” automatically. This is…',
    ['Clustering images by their embeddings',
     'A human sorting your photos',
     'Random grouping',
     'Sorting by file name only'],
    0, 'Similar images have nearby vectors, so clustering gathers them into natural themes.', 'scenario'),
  l6.mc('wrap', 'The big idea across World 7 is that…',
    ['Turning meaning into numbers lets computers compare and search by meaning',
     'Computers can only match exact words',
     'Meaning can never be measured',
     'Embeddings are just spellings'],
    0, 'Embeddings make meaning measurable — the foundation of semantic search, recommendations and more.'),
  l6.tf('foundation', 'Embeddings are a building block behind many modern AI features.', true,
    'From search to recommendations to smart chatbots, embeddings are a quiet, powerful foundation.'),
];

/* ================================================================== *
 * Lessons
 * ================================================================== */
export const WORLD7_LESSONS: Lesson[] = [
  {
    id: 'w7-l1', worldId: W, order: 1,
    title: 'Turning Meaning into Numbers',
    subtitle: 'How AI captures what things mean',
    difficulty: 'beginner', estimatedMinutes: 5, xp: 50, coins: 5,
    description: 'Computers can’t read meaning directly. Embeddings turn words, sentences and images into lists of numbers that stand for their meaning.',
    explanation: 'An embedding is just a list of numbers. It’s built so that things which mean similar things get similar numbers. That’s the trick that lets a computer compare meaning.',
    realWorld: 'Search “affordable eats” and get “cheap restaurants”. The words differ, but their meaning is the same — so their number-lists come out close, and the match just works.',
    objectives: [
      'Define what an embedding is',
      'Explain why we turn meaning into numbers',
      'See that similar meanings get similar numbers',
    ],
    activity: {
      kind: 'bucket',
      title: 'Similar Meaning or Not?',
      instructions: 'Embeddings put similar meanings close together. Sort each pair by whether they mean something similar.',
      config: {
        buckets: ['Similar meaning', 'Different meaning'],
        items: [
          { label: 'Cat / Kitten', bucket: 0 },
          { label: 'Happy / Joyful', bucket: 0 },
          { label: 'Car / Automobile', bucket: 0 },
          { label: 'Ocean / Sea', bucket: 0 },
          { label: 'Banana / Democracy', bucket: 1 },
          { label: 'Table / Thunder', bucket: 1 },
          { label: 'Guitar / Tax', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'An embedding is a list of numbers standing for meaning.',
      'Similar meanings get similar numbers.',
      'This lets computers compare things by meaning, not just exact text.',
    ],
    commonMistakes: [
      'Thinking embeddings are just the spelling turned into numbers — they capture meaning, not letters.',
      'Assuming one number is enough — embeddings use many numbers together.',
    ],
    summary: 'Embeddings translate meaning into numbers so computers can work with it.',
    prerequisiteLessonIds: ['w6-l6'],
    nextLessonId: 'w7-l2',
  },
  {
    id: 'w7-l2', worldId: W, order: 2,
    title: 'What Is a Vector?',
    subtitle: 'A point in “meaning space”',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 50, coins: 5,
    description: 'A vector is just a list of numbers — a point in a space of meaning. Similar things sit close together, like neighbours on a map.',
    explanation: 'Picture a giant map where every idea is a dot. Related ideas sit near each other; unrelated ideas sit far apart. Each dot’s position is its vector — its embedding.',
    realWorld: 'On a real map, nearby towns are close together. In meaning space, “happy”, “joyful” and “cheerful” cluster like neighbouring towns, while “banana” sits streets away.',
    objectives: [
      'Understand a vector as a point in meaning space',
      'See why similar things sit close together',
      'Explain why many numbers beat just two',
    ],
    activity: {
      kind: 'bucket',
      title: 'Neighbours in Meaning Space',
      instructions: 'Which words would sit close to “dog” in meaning space, and which would sit far away?',
      config: {
        buckets: ['Close to “dog”', 'Far from “dog”'],
        items: [
          { label: 'Puppy', bucket: 0 },
          { label: 'Pet', bucket: 0 },
          { label: 'Bark', bucket: 0 },
          { label: 'Poodle', bucket: 0 },
          { label: 'Spreadsheet', bucket: 1 },
          { label: 'Volcano', bucket: 1 },
          { label: 'Interest rate', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'A vector is a list of numbers = a point in meaning space.',
      'Close points mean similar things.',
      'Many numbers give room to separate subtle meanings.',
    ],
    commonMistakes: [
      'Thinking a vector is a single number — it’s a whole list.',
      'Believing points are placed randomly — position reflects meaning.',
    ],
    summary: 'Vectors are points in meaning space, and nearness means similar meaning.',
    prerequisiteLessonIds: ['w7-l1'],
    nextLessonId: 'w7-l3',
  },
  {
    id: 'w7-l3', worldId: W, order: 3,
    title: 'Measuring Similarity',
    subtitle: 'Closeness tells us what’s alike',
    difficulty: 'beginner', estimatedMinutes: 6, xp: 60, coins: 8,
    description: 'Once meaning is a point in space, “how similar?” becomes “how far apart?”. Small distance means similar meaning; large distance means different.',
    explanation: 'To compare two things, a computer measures the distance between their vectors. Close = similar. Far = different. To find the best match, it looks for the nearest vector.',
    realWorld: 'A help desk takes your question, turns it into a vector, and returns the FAQ answer whose vector is closest — the one that means most nearly the same thing.',
    objectives: [
      'Use distance to measure similarity',
      'Explain nearest-neighbour matching',
      'Describe the flow of a meaning-based search',
    ],
    activity: {
      kind: 'steps',
      title: 'Run a Similarity Search',
      instructions: 'Drag the steps into the order a meaning-based search actually runs.',
      config: {
        steps: [
          'Turn the query into a vector',
          'Compare it to the stored vectors',
          'Measure the distance to each',
          'Return the closest ones as results',
        ],
      },
    },
    keyTakeaways: [
      'Closer vectors mean more similar meaning.',
      'The nearest vector is the best match.',
      'A threshold can filter out weak matches.',
    ],
    commonMistakes: [
      'Thinking a large distance means a strong match — it’s the opposite.',
      'Assuming exact wording is needed — distance catches matches keywords miss.',
    ],
    summary: 'Similarity is distance: close means alike, far means different.',
    prerequisiteLessonIds: ['w7-l2'],
    nextLessonId: 'w7-l4',
  },
  {
    id: 'w7-l4', worldId: W, order: 4,
    title: 'Vector Databases',
    subtitle: 'Searching millions of meanings, fast',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'When you have millions of embeddings, you need a special store: a vector database, built to find the nearest matches quickly.',
    explanation: 'A vector database keeps embeddings and uses an index so it doesn’t have to check every one. It trades a tiny bit of accuracy for a huge gain in speed — near-perfect matches, fast.',
    realWorld: 'An app with 10 million product descriptions can’t compare a query to each one by hand. A vector database jumps straight to the nearest matches in a blink.',
    objectives: [
      'Explain what a vector database is for',
      'See why normal databases fall short here',
      'Understand the speed-vs-accuracy trade-off',
    ],
    activity: {
      kind: 'steps',
      title: 'Set Up Vector Search',
      instructions: 'Drag the steps into the order you’d use a vector database.',
      config: {
        steps: [
          'Turn each item into an embedding',
          'Store the embeddings in the database',
          'Turn a new query into an embedding',
          'Search for the nearest stored embeddings',
        ],
      },
    },
    keyTakeaways: [
      'Vector databases store embeddings and search them by closeness.',
      'An index keeps search fast even with millions of vectors.',
      'They trade a tiny bit of accuracy for a big speed gain.',
    ],
    commonMistakes: [
      'Assuming a normal database does “nearest in meaning” well — it’s built for exact matches.',
      'Thinking every vector must be scanned — an index avoids that.',
    ],
    summary: 'Vector databases store and search millions of embeddings fast.',
    prerequisiteLessonIds: ['w7-l3'],
    nextLessonId: 'w7-l5',
  },
  {
    id: 'w7-l5', worldId: W, order: 5,
    title: 'Semantic Search vs Keyword Search',
    subtitle: 'Matching meaning, not just words',
    difficulty: 'intermediate', estimatedMinutes: 7, xp: 70, coins: 10,
    description: 'Keyword search matches exact words. Semantic search matches meaning using embeddings — so different wording still finds the right result.',
    explanation: 'Keyword search needs the exact words to appear, so it can miss great results that used a synonym. Semantic search compares meaning, catching those matches. Many real systems combine both.',
    realWorld: 'Search “warm winter coat” and semantic search shows a “thermal parka” — no shared words, but the same meaning, so their embeddings sit close.',
    objectives: [
      'Contrast keyword and semantic search',
      'Explain when each is the better choice',
      'See why embeddings power semantic search',
    ],
    activity: {
      kind: 'bucket',
      title: 'Which Search Fits?',
      instructions: 'Sort each task by whether keyword search or semantic (meaning-based) search fits best.',
      config: {
        buckets: ['Keyword search fits', 'Semantic search fits'],
        items: [
          { label: 'Look up an exact product code', bucket: 0 },
          { label: 'Find a file by its precise name', bucket: 0 },
          { label: 'Search a specific serial number', bucket: 0 },
          { label: 'Find docs about a vague idea', bucket: 1 },
          { label: 'Match questions worded many ways', bucket: 1 },
          { label: 'Find “cut spending” tips titled “reduce expenses”', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Keyword search matches exact words; semantic search matches meaning.',
      'Keyword search is best for exact codes and names.',
      'Embeddings are what make semantic search possible.',
    ],
    commonMistakes: [
      'Thinking keyword search is always useless — it’s ideal for exact terms.',
      'Assuming semantic search only works when words match — it works on meaning.',
    ],
    summary: 'Semantic search matches meaning; keyword search matches exact words.',
    prerequisiteLessonIds: ['w7-l4'],
    nextLessonId: 'w7-l6',
  },
  {
    id: 'w7-l6', worldId: W, order: 6,
    title: 'Embeddings in the Real World',
    subtitle: 'Where all this shows up',
    difficulty: 'intermediate', estimatedMinutes: 8, xp: 80, coins: 12,
    description: 'Embeddings quietly power recommendations, smart search, duplicate detection and clustering — across text, images and more.',
    explanation: 'Because embeddings put similar things close together, you can recommend nearby items, flag near-duplicates, group items into themes (clustering), and fetch relevant passages for a chatbot.',
    realWorld: 'A photo app that sorts your pictures into “beaches”, “pets” and “food” is clustering images by their embeddings — similar photos land near each other, so they group naturally.',
    objectives: [
      'Recognise real uses of embeddings',
      'Connect closeness to recommendations, dedup and clustering',
      'See embeddings as a foundation of modern AI features',
    ],
    activity: {
      kind: 'bucket',
      title: 'Embedding Superpowers',
      instructions: 'Match each real-world job to what embeddings do. Sort each into the right use.',
      config: {
        buckets: ['Find similar items', 'Group items into themes'],
        items: [
          { label: 'Recommend a similar song', bucket: 0 },
          { label: 'Suggest a related product', bucket: 0 },
          { label: 'Spot a near-duplicate article', bucket: 0 },
          { label: 'Group photos into “pets”', bucket: 1 },
          { label: 'Sort news into topics', bucket: 1 },
          { label: 'Bundle reviews by theme', bucket: 1 },
        ],
      },
    },
    keyTakeaways: [
      'Nearby items power recommendations and duplicate detection.',
      'Clustering groups nearby vectors into themes.',
      'Embeddings are a quiet foundation behind search, feeds and chatbots.',
    ],
    commonMistakes: [
      'Thinking embeddings are only for text — they work on images and more.',
      'Assuming these features are hand-sorted by people — closeness in meaning does the work.',
    ],
    summary: 'Embeddings power search, recommendations, dedup and clustering in everyday apps.',
    prerequisiteLessonIds: ['w7-l5'],
    nextLessonId: 'w8-l1',
  },
];

export const WORLD7_QUESTIONS: Question[] = [
  ...w7l1Q, ...w7l2Q, ...w7l3Q,
  ...w7l4Q, ...w7l5Q, ...w7l6Q,
];
